/* -------------------------------------------------------------------

                   🗲 Storm Software - Cyclone UI

 This code was released as part of the Cyclone UI project. Cyclone UI
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/cyclone-ui.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/cyclone-ui
 Documentation:            https://docs.stormsoftware.com/projects/cyclone-ui
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

/**
 * Generates a Tamagui icon component for every icon in the Phosphor collection.
 *
 * @remarks
 * The SVG assets are read from the `@phosphor-icons/core` package and turned into `src/icons/*.tsx`, `src/index.ts`, and `src/all.ts` with a Power Plant generator. Run with `pnpm --filter @cyclone-ui/icons generate`.
 */

import type { GeneratedDocument } from "@power-plant/core";
import { defineGenerator, execute } from "@power-plant/core";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { findPackageJSON } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { format, resolveConfig } from "prettier";

const WEIGHTS = [
  "thin",
  "light",
  "regular",
  "bold",
  "fill",
  "duotone"
] as const;

type IconWeight = (typeof WEIGHTS)[number];

interface IconPath {
  d: string;
  opacity?: number;
}

interface IconSpec {
  name: string;
  component: string;
  weights: Record<IconWeight, IconPath[]>;
}

interface IconsSpec {
  version: string;
  icons: IconSpec[];
}

// Identifiers exported by the hand-written modules or used by the generated ones
const RESERVED = new Set([
  "ICON_WEIGHTS",
  "IconComponent",
  "IconProps",
  "IconWeight",
  "IconSize",
  "IconWeights",
  "SvgPath",
  "allIcons",
  "createIcon",
  "resolveIconSize"
]);

interface IconsOptions {
  root: string;
}

const HEADER = `/* -------------------------------------------------------------------

                   🗲 Storm Software - Cyclone UI

 This code was released as part of the Cyclone UI project. Cyclone UI
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/cyclone-ui.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/cyclone-ui
 Documentation:            https://docs.stormsoftware.com/projects/cyclone-ui
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */
`;

const GENERATED_NOTICE = (version: string) =>
  `// This file is generated by \`scripts/generate.ts\` from @phosphor-icons/core@${
    version
  } (MIT). Do not edit it manually.`;

const pathSchema = {
  type: "object",
  properties: {
    d: { type: "string" },
    opacity: { type: "number" }
  },
  required: ["d"]
};

const schema = {
  type: "object",
  title: "Phosphor Icons",
  description: "The SVG paths of every Phosphor icon, for each icon weight.",
  properties: {
    version: {
      type: "string",
      description:
        "The version of `@phosphor-icons/core` the icons were read from."
    },
    icons: {
      type: "array",
      items: {
        type: "object",
        properties: {
          name: { type: "string", description: "The Phosphor icon name." },
          component: {
            type: "string",
            description: "The generated component name."
          },
          weights: {
            type: "object",
            properties: Object.fromEntries(
              WEIGHTS.map(weight => [
                weight,
                { type: "array", items: pathSchema }
              ])
            ),
            required: [...WEIGHTS]
          }
        },
        required: ["name", "component", "weights"]
      }
    }
  },
  required: ["version", "icons"]
};

const toPascalCase = (name: string) =>
  name
    .split("-")
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

/**
 * Extract the `<path>` elements from a Phosphor SVG asset.
 *
 * @remarks
 * Phosphor assets only contain `<path>` elements with `d` and (for duotone) `opacity` attributes. Anything else fails loudly so upstream changes are not silently dropped.
 */
function parseSvg(svg: string, file: string): IconPath[] {
  const elements = [...svg.matchAll(/<([a-z]+)\b([^>]*?)\/?>/gi)].filter(
    ([, tag]) => tag !== "svg"
  );

  return elements.map(([element, tag, attributes]) => {
    if (tag !== "path") {
      throw new Error(`Unsupported <${tag}> element in ${file}: ${element}`);
    }

    const path: IconPath = { d: "" };
    for (const [, key, value] of attributes!.matchAll(/([\w-]+)="([^"]*)"/g)) {
      if (key === "d") {
        path.d = value!;
      } else if (key === "opacity") {
        path.opacity = Number(value);
      } else {
        throw new Error(`Unsupported "${key}" attribute in ${file}`);
      }
    }

    if (!path.d) {
      throw new Error(`Missing "d" attribute in ${file}`);
    }

    return path;
  });
}

const renderPaths = (paths: IconPath[]) => {
  const elements = paths.map(
    ({ d, opacity }) =>
      `<SvgPath d="${d}"${opacity === undefined ? "" : ` opacity={${opacity}}`} />`
  );

  return elements.length === 1
    ? `    ${elements[0]}`
    : `    <>\n${elements.map(element => `      ${element}`).join("\n")}\n    </>`;
};

const renderIcon = (icon: IconSpec, version: string) => `${HEADER}
${GENERATED_NOTICE(version)}

import { Path as SvgPath } from "react-native-svg";
import { createIcon } from "../create-icon";

/**
 * The Phosphor \`${icon.name}\` icon.
 *
 * @see https://phosphoricons.com/?q=${icon.name}
 */
export const ${icon.component} = createIcon("${icon.component}", {
${WEIGHTS.map(
  weight => `  ${weight}: (\n${renderPaths(icon.weights[weight])}\n  )`
).join(",\n")}
});
`;

const renderIndex = (spec: IconsSpec) => `${HEADER}
${GENERATED_NOTICE(spec.version)}

export * from "./all";
export * from "./create-icon";
export * from "./types";

${spec.icons
  .map(icon => `export { ${icon.component} } from "./icons/${icon.component}";`)
  .join("\n")}
`;

const renderAll = (spec: IconsSpec) => `${HEADER}
${GENERATED_NOTICE(spec.version)}

${spec.icons
  .map(icon => `import { ${icon.component} } from "./icons/${icon.component}";`)
  .join("\n")}
import type { IconComponent } from "./types";

/**
 * Every Phosphor icon component, keyed by component name.
 */
export const allIcons: { [component: string]: IconComponent } = {
${spec.icons.map(icon => `  ${icon.component}`).join(",\n")}
};
`;

const document = (path: string, content: string): GeneratedDocument => ({
  path,
  language: path.endsWith(".tsx") ? "tsx" : "ts",
  chunks: [{ content }]
});

export const generator = defineGenerator<IconsSpec, IconsOptions, string[]>({
  meta: {
    name: "phosphor-icons",
    title: "Phosphor Icons",
    description:
      "Generates a Tamagui icon component for every icon in the Phosphor collection.",
    links: ["https://phosphoricons.com"]
  },
  schema: {
    schema,
    meta: {
      name: "phosphor-icons",
      title: "Phosphor Icons",
      spec: "The SVG paths of every Phosphor icon, for each icon weight."
    }
  },
  input: {
    meta: {
      name: "phosphor-core-assets",
      title: "Phosphor Core Assets",
      readFrom: "The SVG assets shipped in the `@phosphor-icons/core` package."
    },
    input: async ({ root }) => {
      const packagePath = findPackageJSON(
        "@phosphor-icons/core",
        pathToFileURL(join(root, "package.json"))
      );
      if (!packagePath) {
        throw new Error("Unable to locate the `@phosphor-icons/core` package");
      }
      const packageDir = dirname(packagePath);
      const { version } = JSON.parse(await readFile(packagePath, "utf8"));

      const names = (await readdir(join(packageDir, "assets", "regular")))
        .filter(file => file.endsWith(".svg"))
        .map(file => file.slice(0, -".svg".length))
        .sort();

      const icons = await Promise.all(
        names.map(async name => {
          const entries = await Promise.all(
            WEIGHTS.map(async weight => {
              const file = join(
                packageDir,
                "assets",
                weight,
                weight === "regular" ? `${name}.svg` : `${name}-${weight}.svg`
              );

              return [weight, parseSvg(await readFile(file, "utf8"), file)];
            })
          );

          return {
            name,
            component: toPascalCase(name),
            weights: Object.fromEntries(entries)
          };
        })
      );

      return { version, icons };
    }
  },
  generator: spec => {
    const components = new Set<string>();
    for (const icon of spec.icons) {
      if (RESERVED.has(icon.component)) {
        throw new Error(`Reserved icon component name: ${icon.component}`);
      }
      if (components.has(icon.component)) {
        throw new Error(`Duplicate icon component name: ${icon.component}`);
      }
      components.add(icon.component);
    }

    return Object.fromEntries(
      [
        ...spec.icons.map(icon =>
          document(
            `src/icons/${icon.component}.tsx`,
            renderIcon(icon, spec.version)
          )
        ),
        document("src/index.ts", renderIndex(spec)),
        document("src/all.ts", renderAll(spec))
      ].map(doc => [doc.path, doc])
    );
  },
  output: {
    meta: {
      name: "file-system",
      title: "File System",
      description:
        "Formats and writes the generated documents to the package, and removes stale icon files."
    },
    output: async (_spec, { root }, documents) => {
      const iconsDir = join(root, "src", "icons");
      await mkdir(iconsDir, { recursive: true });

      const stale = (await readdir(iconsDir)).filter(
        file => !documents[`src/icons/${file}`]
      );
      await Promise.all(stale.map(async file => rm(join(iconsDir, file))));

      const paths = Object.keys(documents);
      const config = await resolveConfig(join(root, "src", "index.ts"));
      await Promise.all(
        Object.values(documents).map(async ({ path, chunks = [] }) => {
          const filepath = join(root, path);

          return writeFile(
            filepath,
            await format(chunks.map(chunk => chunk.content ?? "").join(""), {
              ...config,
              filepath
            })
          );
        })
      );

      return paths;
    }
  }
});

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const written = await execute(generator, {
  root,
  cwd: root,
  settings: { skipStorage: true }
});

console.log(
  ` ✔ Generated ${written.length - 2} Phosphor icon components in ${join(
    root,
    "src"
  )}`
);
