/**
 * A collection of utility functions that assist in displaying help information for the Completions - Fish Configuration command.
 *
 * @module shell-shock:help/completions/fish/config
 */

/* eslint-disable */
/* oxlint-disable */
// biome-ignore lint: disable

import {
  bold,
  inverse,
  link,
  table,
  textColors,
  writeLine
} from "shell-shock:console";

// Generated by Power Plant
// Please do not edit this file manually - it will be automatically overwritten
// the next time the generator is run.

/**
 * Utility functions for displaying help information for the Completions - Fish Configuration command.
 *
 * @remarks
 * This module contains utility functions that assist in displaying help information for the Completions - Fish Configuration command. The main function exported by this module is the `showHelp` function, which can be used to display help information for the specified command or application. This function can be called from within the command's handler or from any other part of the application where help information needs to be displayed.
 */
/**
 * Display help information for the Completions - Fish Configuration command.
 */
export function showHelp() {
  writeLine(
    `${bold(textColors.heading.secondary("Tags: "))} ${textColors.tags.utility ? textColors.tags.utility(inverse(" Utility ")) : textColors.tags.$default(inverse(" Utility "))}`,
    { padding: 0 }
  );
  writeLine("");

  writeLine(bold(textColors.heading.secondary("Usage:")));
  writeLine(
    textColors.body.secondary(
      `${textColors.usage.bin(">_ cyclone-ui")} ${textColors.usage.command("completions")} ${textColors.usage.command("fish")} ${textColors.usage.command("config")} ${textColors.usage.args("<path>")} ${textColors.usage.options("[options]")}`
    ),
    { padding: 0 }
  );

  writeLine(
    textColors.body.secondary(
      `${textColors.usage.bin(">_ cyclone-ui")} ${textColors.usage.command("completions")} ${textColors.usage.command("fish")} ${textColors.usage.command("config")} ${textColors.usage.options("[options]")} ${textColors.usage.args("<path>")}`
    ),
    { padding: 0 }
  );

  writeLine("");
  writeLine(bold(textColors.heading.secondary("Options:")));
  table([
    [
      {
        value: textColors.body.primary("--color, --colors"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Force colored terminal output (env: CYCLONE_UI_COLOR, default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("--no-color, --no-colors"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Force disable colored terminal output (env: CYCLONE_UI_NO_COLOR, default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("--display"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Should the generated completion script be written to console output instead of an actual file on disk? (default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("-?, -h, --help"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Show help information (default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("-i, --interact, --interactive"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Enable interactive mode - will be set to false if running in a CI pipeline (env: CYCLONE_UI_INTERACTIVE, default: true).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("--no-interactive, --non-interactive"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Disable interactive mode - will be set to true if running in a CI pipeline (env: CYCLONE_UI_NON_INTERACTIVE, default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("--hide-banner, --no-banner"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Do not display the application banner displayed while running the CLI - will be set to true if running in a CI pipeline (env: CYCLONE_UI_NO_BANNER, default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("--no-color, --no-colors"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Force disable colored terminal output (env: CYCLONE_UI_NO_COLOR, default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("--no-interactive, --non-interactive"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Disable interactive mode - will be set to true if running in a CI pipeline (env: CYCLONE_UI_NON_INTERACTIVE, default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("-V, --verbose"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Enable verbose output (env: CYCLONE_UI_VERBOSE, default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("-v, --version"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Show the version of the application (default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("-y, --yes"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Skip all prompts by answering yes to all of them - will be set to true if running in a CI pipeline (env: CYCLONE_UI_YES, default: false).`
        ),
        align: "left",
        border: "none"
      }
    ]
  ]);

  writeLine("");

  writeLine(
    textColors.body.tertiary(
      `More information can be found in the Completions - Fish Configuration command documentation at ${link("https://docs.stormsoftware.com/projects/cyclone-ui/reference/cli/completions/fish/config")}${textColors.body.tertiary(".")}`
    ),
    { padding: 0 }
  );
  writeLine("");
}
