import type { MessageType } from "@stryke/types/messages";
import type { ErrorValidationDetail as ErrorValidationDetails, HelpValidationDetail as HelpValidationDetails, InfoValidationDetail as InfoValidationDetails, SuccessValidationDetail as SuccessValidationDetails, ValidationDetail as ValidationDetails, WarningValidationDetail as WarningValidationDetails } from "@stryke/types/validations";
import type { Atom } from "jotai";
import type { InferFieldState, ValidationResults } from "../types";
export declare const getMessageType: <TMessageType extends MessageType, TValidationDetails extends ValidationDetails<TMessageType> = ValidationDetails<TMessageType>>(validationResults: ValidationResults, type: TMessageType) => TValidationDetails[];
export declare const getFieldsMessageTypes: <TFieldValue, TMessageType extends MessageType, TValidationDetails extends ValidationDetails<TMessageType> = ValidationDetails<TMessageType>>(messageMap: InferFieldState<TFieldValue, ValidationResults>, type: TMessageType) => InferFieldState<TFieldValue, TValidationDetails[]>;
export declare const atomWithFieldsMessageTypes: <TFieldValue, TMessageType extends MessageType, TValidationDetails extends ValidationDetails<TMessageType> = ValidationDetails<TMessageType>>(validationResultsAtom: Atom<InferFieldState<TFieldValue, ValidationResults>>, type: TMessageType) => Atom<InferFieldState<TFieldValue, TValidationDetails[]>>;
export declare const getFieldsMessageList: <TFieldValue, TMessageType extends MessageType, TValidationDetails extends ValidationDetails<TMessageType> = ValidationDetails<TMessageType>>(messageMap: InferFieldState<TFieldValue, ValidationResults>, type: TMessageType) => TValidationDetails[];
export declare const atomWithFieldsMessageList: <TFieldValue, TMessageType extends MessageType, TValidationDetails extends ValidationDetails<TMessageType> = ValidationDetails<TMessageType>>(validationResultsAtom: Atom<InferFieldState<TFieldValue, ValidationResults>>, type: TMessageType) => Atom<TValidationDetails[]>;
export declare const atomWithMessageTypes: <TMessageType extends MessageType, TValidationDetails extends ValidationDetails<TMessageType> = ValidationDetails<TMessageType>>(validationResultsAtom: Atom<ValidationResults>, type: TMessageType) => Atom<TValidationDetails[]>;
export declare const atomWithMessages: (errorMessagesAtom: Atom<ErrorValidationDetails[]>, warningMessagesAtom: Atom<WarningValidationDetails[]>, infoMessagesAtom: Atom<InfoValidationDetails[]>, helpMessagesAtom: Atom<HelpValidationDetails[]>, successMessagesAtom: Atom<SuccessValidationDetails[]>) => Atom<ValidationDetails[]>;
export declare const atomWithTheme: (optionsAtom: Atom<{
    theme?: string;
}>, errorMessagesAtom: Atom<ErrorValidationDetails[]>, warningMessagesAtom: Atom<WarningValidationDetails[]>, infoMessagesAtom: Atom<InfoValidationDetails[]>, helpMessagesAtom: Atom<HelpValidationDetails[]>, successMessagesAtom: Atom<SuccessValidationDetails[]>) => Atom<string>;
//# sourceMappingURL=atom-with-messages.d.ts.map