/* eslint-disable */
/* oxlint-disable */
// biome-ignore lint: disable

// Generated by @razorwind/shell-shock
// Please do not edit this file manually - it will be automatically overwritten
// the next time the generator is run.

import { isSearchError, plan } from "@razorwind/shell-shock/runtime";
import { designSystem } from "../razorwind/design-system";

/**
 * Options for the `plan` command.
 */
export interface PlanOptions {
  /**
   * Search terms for design tokens. Prefer at least two terms when known.
   */
  tokens?: string[];

  /**
   * Search terms for icons.
   */
  icons?: string[];

  /**
   * Search terms for components.
   */
  components?: string[];

  /**
   * Search terms for fonts.
   */
  fonts?: string[];

  /**
   * Maximum matches per term for each list.
   *
   * @defaultValue 2
   */
  limit?: number;
}

function print(result: unknown): void {
  process.stdout.write(
    `${typeof result === "string" ? result : JSON.stringify(result, null, 2)}\n`
  );
}

/**
 * Search the Cyclone UI tokens, icons, components and fonts in one pass.
 */
export default async function handler(options: PlanOptions) {
  const result = plan(designSystem, {
    tokens: options.tokens,
    icons: options.icons,
    components: options.components,
    fonts: options.fonts,
    limit: options.limit
  });

  print(result);
  if (isSearchError(result)) {
    process.exitCode = 1;
  }
}
