/* eslint-disable */
/* oxlint-disable */
// biome-ignore lint: disable

// Generated by @razorwind/shell-shock
// Please do not edit this file manually - it will be automatically overwritten
// the next time the generator is run.

import { analyzeA11y } from "@razorwind/shell-shock/runtime";
import { readFile } from "node:fs/promises";
import { designSystem } from "../razorwind/design-system";

/**
 * Options for the `analyze-a11y` command.
 */
export interface AnalyzeA11yOptions {
  /**
   * Source code of a React component or JSX snippet to analyze.
   */
  code?: string;

  /**
   * Path to a source file to analyze (alternative to --code).
   */
  file?: string;

  /**
   * Optional label for the component under review.
   */
  componentName?: string;

  /**
   * Optional usage context (for example "in a form" or "modal").
   */
  context?: string;

  /**
   * Run regex-based heuristics (unlabeled buttons, missing alt, …).
   *
   * @defaultValue true
   */
  patternAnalysis?: boolean;
}

function print(result: unknown): void {
  process.stdout.write(
    `${typeof result === "string" ? result : JSON.stringify(result, null, 2)}\n`
  );
}

/**
 * Analyze source code for accessibility issues against the Cyclone UI design system.
 */
export default async function handler(options: AnalyzeA11yOptions) {
  const code =
    options.code ??
    (options.file ? await readFile(options.file, "utf8") : undefined);
  if (!code) {
    print({ error: "Provide source code via --code or a path via --file." });
    process.exitCode = 1;
    return;
  }

  print(
    analyzeA11y(designSystem, code, {
      componentName: options.componentName,
      context: options.context,
      includePatternAnalysis: options.patternAnalysis !== false
    })
  );
}
