/* eslint-disable */
/* oxlint-disable */
// biome-ignore lint: disable

import { showBanner } from "shell-shock:banner/analyze-a11y";
import { textColors, writeLine } from "shell-shock:console";
import { env, isDebug, isDevelopment } from "shell-shock:env";
import { showHelp } from "shell-shock:help/analyze-a11y";
import {
  type GlobalOptions,
  hasFlag,
  isHelp,
  useArgs,
  useGlobalOptions,
  withCommand
} from "shell-shock:state";
import { executeUpdate } from "shell-shock:update";
import { isInteractive } from "shell-shock:utils";
import handleAnalyzeA11Y from "./command";

// Generated by Power Plant
// Please do not edit this file manually - it will be automatically overwritten
// the next time the generator is run.

export interface AnalyzeA11YOptions extends GlobalOptions {
  /**
   * Source code of a React component or JSX snippet to analyze.
   */
  code?: string | undefined;
  /**
   * Path to a source file to analyze (alternative to --code).
   */
  file?: string | undefined;
  /**
   * Optional label for the component under review.
   */
  componentName?: string | undefined;
  /**
   * Optional usage context (for example "in a form" or "modal").
   */
  context?: string | undefined;
  /**
   * Run regex-based heuristics (unlabeled buttons, missing alt, …).
   */
  patternAnalysis?: boolean | undefined;
}

/**
 * The Analyze Accessibility (cyclone-ui analyze-a11y) command.
 *
 * @remarks
 * Analyze a React/JSX source string (or file) for likely accessibility issues and hard-coded colors, suggesting the nearest design tokens for each color.
 *
 * @title Analyze Accessibility
 *
 * @param args - The command-line arguments passed to the command.
 */
export async function handler(args: string[] = useArgs()) {
  const options = {
    ...useGlobalOptions(),
    patternAnalysis: true
  } as unknown as AnalyzeA11YOptions;

  for (let i = 0; i < args.slice(0).length; i++) {
    const arg: string =
      args[i].length > 3 && args[i].startsWith("--")
        ? `--${args[i].slice(2).replaceAll("-", "").toLowerCase().replaceAll("-", "").replaceAll("_", "")}`
        : args[i].length > 2 && args[i].startsWith("-")
          ? `-${args[i].slice(1).replaceAll("-", "")}`
          : args[i];
    if (
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("code=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "code" ||
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("code=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "code"
    ) {
      if (
        /^--?(code)=/.test(
          "-" + arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
        )
      ) {
        options.code = arg
          .replace(/^--?(code)=/, "")
          .trim()
          .replace(/^("|')/, "")
          .replace(/("|')$/, "");
      } else if (args.length > i + 1) {
        options.code = args[++i]
          .trim()
          .replace(/^("|')/, "")
          .replace(/("|')$/, "");
      }
    } else if (
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("file=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "file" ||
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("file=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "file"
    ) {
      if (
        /^--?(file)=/.test(
          "-" + arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
        )
      ) {
        options.file = arg
          .replace(/^--?(file)=/, "")
          .trim()
          .replace(/^("|')/, "")
          .replace(/("|')$/, "");
      } else if (args.length > i + 1) {
        options.file = args[++i]
          .trim()
          .replace(/^("|')/, "")
          .replace(/("|')$/, "");
      }
    } else if (
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("componentname=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") ===
        "componentname" ||
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("componentname=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") ===
        "componentname"
    ) {
      if (
        /^--?(componentname)=/.test(
          "-" + arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
        )
      ) {
        options.componentName = arg
          .replace(/^--?(componentname)=/, "")
          .trim()
          .replace(/^("|')/, "")
          .replace(/("|')$/, "");
      } else if (args.length > i + 1) {
        options.componentName = args[++i]
          .trim()
          .replace(/^("|')/, "")
          .replace(/("|')$/, "");
      }
    } else if (
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("context=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "context" ||
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("context=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "context"
    ) {
      if (
        /^--?(context)=/.test(
          "-" + arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
        )
      ) {
        options.context = arg
          .replace(/^--?(context)=/, "")
          .trim()
          .replace(/^("|')/, "")
          .replace(/("|')$/, "");
      } else if (args.length > i + 1) {
        options.context = args[++i]
          .trim()
          .replace(/^("|')/, "")
          .replace(/("|')$/, "");
      }
    } else if (
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("patternanalysis=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") ===
        "patternanalysis" ||
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("patternanalysis=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") ===
        "patternanalysis"
    ) {
      if (
        /^--?(patternanalysis)=/.test(
          "-" + arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
        )
      ) {
        const value = arg
          .replace(/^--?(patternanalysis)=/, "")
          .trim()
          .replace(/^("|')/, "")
          .replace(/("|')$/, "")
          .toLowerCase();
        options.patternAnalysis =
          !!value &&
          value.toLowerCase() !== "false" &&
          value.toLowerCase() !== "f" &&
          value.toLowerCase() !== "no" &&
          value !== "n" &&
          value.toLowerCase() !== "0" &&
          value.toLowerCase() !== "off" &&
          value !== "disable" &&
          value.toLowerCase() !== "disabled" &&
          value.toLowerCase() !== "never" &&
          (Number.isNaN(Number.parseFloat(value)) ||
            Number.parseFloat(value) > 0);
      } else {
        options.patternAnalysis = true;
      }
    }
  }

  if (!hasFlag("quiet")) {
    await showBanner();
    await executeUpdate();
  }

  if (!isHelp() && !hasFlag("quiet")) {
    writeLine("");
    if (isDevelopment || isDebug || env.LOG_LEVEL === "debug") {
      writeLine(
        textColors.body.tertiary(
          "Debug mode is enabled. Additional debug information may be logged to the console."
        )
      );
    }
  }

  if (!isInteractive) {
    const failures: string[] = [];
  }

  if (options.help) {
    return showHelp();
  } else {
    return withCommand(
      "analyze-a11y",
      ["analyze-a11y"],
      [options],
      handleAnalyzeA11Y
    );
  }
}
