/* eslint-disable */
/* oxlint-disable */
// biome-ignore lint: disable

import { showBanner } from "shell-shock:banner/completions/fish/config";
import { error, italic, textColors, writeLine } from "shell-shock:console";
import { env, isDebug, isDevelopment } from "shell-shock:env";
import { showHelp } from "shell-shock:help/completions/fish/config";
import { isCancel, text } from "shell-shock:prompts";
import {
  type GlobalOptions,
  isHelp,
  useArgs,
  useGlobalOptions,
  withCommand
} from "shell-shock:state";
import { executeUpdate } from "shell-shock:update";
import { isInteractive } from "shell-shock:utils";
import handleConfig from "./command";

// Generated by Shell Shock
// Do not edit this file manually - it will be overwritten automatically.
// Automatic overwrites can be disabled by using the `output.overwrite` option.

export interface ConfigOptions extends GlobalOptions {
  /**
   * Should the generated completion script be written to console output instead of an actual file on disk? This is useful for debugging purposes or if you want to manually handle the output.
   */
  display?: boolean | undefined;
}

/**
 * The Completions - Fish Configuration (powerlines completions fish config) command.
 *
 * @remarks
 * Update the current system's Fish shell configuration to include completions for the Powerlines command-line interface.
 *
 * @title Completions - Fish Configuration
 *
 * @param args - The command-line arguments passed to the command.
 */
export async function handler(args: string[] = useArgs()) {
  const options = {
    ...useGlobalOptions(),
    display: true
  } as unknown as ConfigOptions;

  for (let i = 0; i < args.slice(0).length; i++) {
    const arg: string =
      args[i].length > 3 && args[i].startsWith("--")
        ? `--${args[i].slice(2).replaceAll("-", "").toLowerCase().replaceAll("-", "").replaceAll("_", "")}`
        : args[i].length > 2 && args[i].startsWith("-")
          ? `-${args[i].slice(1).replaceAll("-", "")}`
          : args[i];
    if (
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("display=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "display" ||
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("display=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "display"
    ) {
      if (
        /^--?(display)=/.test(
          "-" + arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
        )
      ) {
        const value = arg
          .replace(/^--?(display)=/, "")
          .trim()
          .replace(/^("|')/, "")
          .replace(/("|')$/, "")
          .toLowerCase();
        options.display =
          !!value &&
          value.toLowerCase() !== "false" &&
          value.toLowerCase() !== "f" &&
          value.toLowerCase() !== "no" &&
          value !== "n" &&
          value.toLowerCase() !== "0" &&
          value.toLowerCase() !== "off" &&
          value !== "disable" &&
          value.toLowerCase() !== "disabled" &&
          value.toLowerCase() !== "never" &&
          (Number.isNaN(Number.parseFloat(value)) ||
            Number.parseFloat(value) > 0);
      } else {
        options.display = true;
      }
    }
  }

  let optionsIndex: number =
    Math.max(
      0,
      args
        .slice(4)
        .findIndex(
          arg =>
            arg.startsWith("-") &&
            /^(display)=?.*$/.test(
              arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
            )
        )
    ) + 4;

  let argsIndex: number =
    optionsIndex > 4
      ? 4
      : Math.max(
          0,
          args
            .slice(optionsIndex)
            .findLastIndex(
              arg =>
                arg.startsWith("-") &&
                /^(display)=?.*$/.test(
                  arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
                )
            )
        ) + 4;

  let path: string = "~/.config/fish/config.fish" as string;

  if (argsIndex + 0 < args.length && argsIndex + 0 !== optionsIndex) {
    path = args[argsIndex + 0] as string;
  }

  await showBanner();
  await executeUpdate();

  if (!isHelp()) {
    writeLine("");
    if (isDevelopment || isDebug || env.LOG_LEVEL === "debug") {
      writeLine(
        textColors.body.tertiary(
          "Debug mode is enabled. Additional debug information may be logged to the console."
        )
      );
    }
  }

  if (!isInteractive) {
    const failures: string[] = [];

    if (!path) {
      failures.push('Missing required "path" positional argument');
    }
  } else if (!isHelp() && path === undefined) {
    writeLine("");

    if (!path) {
      const value = await text({
        message: `Please provide a value for the ${italic("path")} argument`,
        description: `An argument that allows the user to specify a custom Path s...`,
        validate(val) {
          if (!val || val.trim() === "") {
            return "A value must be provided for this argument";
          }

          return null;
        }
      });
      if (isCancel(value)) {
        return;
      }

      path = value;
    }
    writeLine("");

    const failures: string[] = [];

    if (!path) {
      failures.push('Missing required "path" positional argument');
    }
    if (failures.length > 0) {
      error(
        `The following validation failures were found while processing the user provided input, and must be corrected before the ${italic("Completions - Fish Configuration")} command can be executed: \n\n${failures.map(failure => " - " + failure).join("\n")}`
      );
      options.help = true;
    }
  }

  if (options.help) {
    return showHelp();
  } else {
    return withCommand(
      "completions/fish/config",
      ["completions", "fish", "config"],
      [options, path],
      handleConfig
    );
  }
}
