/* eslint-disable */
/* oxlint-disable */
// biome-ignore lint: disable

// Generated by Power Plant
// Please do not edit this file manually - it will be automatically overwritten
// the next time the generator is run.

/**
 * Options for the Update command.
 */
export interface UpdateOptions {
  /**
   * Whether to update to the latest version.
   *
   * @remarks
   * If set to `true`, the command will attempt to update to the latest version. This option takes precedence over the `version` option.
   * @defaultValue false
   */
  latest?: boolean;

  /**
   * A specific application version to update to.
   *
   * @remarks
   * The command will attempt to update to the specified version. The version should be a valid semantic version string, or `latest` to update to the latest version.
   * @defaultValue "latest"
   */
  version?: string;
}

/**
 * Handler logic for the \`update\` command.
 */
export default async function handler(options: UpdateOptions) {
  return;
}
