import type { Meta, StoryObj } from "@storybook/react";
import { Input } from "./Input";
declare const meta: Meta<typeof Input>;
export default meta;
type Story = StoryObj<typeof Input>;
export declare const Base: Story;
export declare const Required: Story;
export declare const Disabled: Story;
export declare const Primary: Story;
export declare const PrimaryOutlined: Story;
export declare const Secondary: Story;
export declare const SecondaryOutlined: Story;
export declare const Tertiary: Story;
export declare const TertiaryOutlined: Story;
export declare const Error: Story;
export declare const ErrorOutlined: Story;
export declare const Warning: Story;
export declare const WarningOutlined: Story;
export declare const Info: Story;
export declare const InfoOutlined: Story;
export declare const Success: Story;
export declare const SuccessOutlined: Story;
export declare const Accent: Story;
export declare const AccentOutlined: Story;
//# sourceMappingURL=Input.stories.d.ts.map