/* eslint-disable */
/* oxlint-disable */
// biome-ignore lint: disable

import { showBanner } from "shell-shock:banner/list-icons";
import { textColors, writeLine } from "shell-shock:console";
import { env, isDebug, isDevelopment } from "shell-shock:env";
import { showHelp } from "shell-shock:help/list-icons";
import {
  type GlobalOptions,
  hasFlag,
  isHelp,
  useArgs,
  useGlobalOptions,
  withCommand
} from "shell-shock:state";
import { executeUpdate } from "shell-shock:update";
import { isInteractive } from "shell-shock:utils";
import handleListIcons from "./command";

// Generated by Power Plant
// Please do not edit this file manually - it will be automatically overwritten
// the next time the generator is run.

export interface ListIconsOptions extends GlobalOptions {}

/**
 * The List Icons (cyclone-ui list-icons) command.
 *
 * @remarks
 * Return every design-system icon record. Large output - prefer search-icons for normal use.
 *
 * @title List Icons
 *
 * @param args - The command-line arguments passed to the command.
 */
export async function handler(args: string[] = useArgs()) {
  const options = {
    ...useGlobalOptions()
  } as unknown as ListIconsOptions;

  for (let i = 0; i < args.slice(0).length; i++) {
    const arg: string =
      args[i].length > 3 && args[i].startsWith("--")
        ? `--${args[i].slice(2).replaceAll("-", "").toLowerCase().replaceAll("-", "").replaceAll("_", "")}`
        : args[i].length > 2 && args[i].startsWith("-")
          ? `-${args[i].slice(1).replaceAll("-", "")}`
          : args[i];
  }

  if (!hasFlag("quiet")) {
    await showBanner();
    await executeUpdate();
  }

  if (!isHelp() && !hasFlag("quiet")) {
    writeLine("");
    if (isDevelopment || isDebug || env.LOG_LEVEL === "debug") {
      writeLine(
        textColors.body.tertiary(
          "Debug mode is enabled. Additional debug information may be logged to the console."
        )
      );
    }
  }

  if (!isInteractive) {
    const failures: string[] = [];
  }

  if (options.help) {
    return showHelp();
  } else {
    return withCommand("list-icons", ["list-icons"], [], handleListIcons);
  }
}
