/* eslint-disable */
/* oxlint-disable */
// biome-ignore lint: disable

import { readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import { join } from "node:path";
import {
  bold,
  help,
  inlineCode,
  success,
  warn,
  writeLine
} from "shell-shock:console";
import { SHELL_COMPLETIONS, SHELL_COMPLETIONS_DISPLAY } from "../shared";

// Generated by Shell Shock
// Do not edit this file manually - it will be overwritten automatically.
// Automatic overwrites can be disabled by using the `output.overwrite` option.

/**
 * Options for the Bash Completions - Configuration command.
 */
export interface BashConfigCompletionsOptions {
  /**
   * Should the generated completion script be written to console output instead of an actual file on disk? This is useful for debugging purposes or if you want to manually handle the output.
   *
   * @defaultValue false
   */
  display?: boolean;
}

/**
 * Handler logic for the \`completions bash config\` command.
 */
export default async function handler(
  options: BashConfigCompletionsOptions = {},
  path: string = "~/.bashrc"
) {
  if (options.display !== true) {
    let configPath: string = path.includes(".") ? path : join(path, ".bashrc");

    if (configPath.startsWith("~")) {
      configPath = join(os.homedir(), configPath.replace("~", ""));
    }

    let content: string = "";

    try {
      content = await readFile(configPath, "utf8");
    } catch (error) {
      if (
        typeof error === "object" &&
        error !== null &&
        "code" in error &&
        error.code === "ENOENT"
      ) {
        // If the file doesn't exist, we can create it later when writing the completion script.
        warn(
          `Configuration file ${bold(configPath)} does not exist. It will be created when the completion script is written.`
        );
      } else {
        return { error };
      }
    }

    await writeFile(
      configPath,
      `${content}\n\n### Begin - Powerlines Shell Completions ###\n\n${SHELL_COMPLETIONS} \n\n### End - Powerlines Bash Completions ###`
    );

    success(
      `Powerlines shell completions have been applied to Bash configuration file at ${bold(configPath)}. Please restart your terminal or run ${inlineCode(`source ${configPath}`)} for the changes to take effect.`
    );
  } else {
    writeLine(" ------------------------------------------------- ");
    writeLine("");
    writeLine(`### Begin - Powerlines Bash Completions ###`);
    writeLine("");
    SHELL_COMPLETIONS_DISPLAY.split("\n").map(line => writeLine(line));
    writeLine("");
    writeLine(`### End - Powerlines Bash Completions ###`);
    writeLine("");
    writeLine(" ------------------------------------------------- ");

    writeLine("");
    help(`To enable these completions, perform one of the following actions:

    1) Copy and paste the above script into your shell configuration file (e.g., ~/.bashrc)
    2) Save the above script to a file and source it from your shell configuration file `);
  }
}
