/* eslint-disable */
/* oxlint-disable */
// biome-ignore lint: disable

import { showHelp } from "help";
import { showHelp as showHelpAdd } from "help/add";
import { showHelp as showHelpBuild } from "help/build";
import { showHelp as showHelpCompletions } from "help/completions";
import { showHelp as showHelpCompletionsBash } from "help/completions/bash";
import { showHelp as showHelpCompletionsBashConfig } from "help/completions/bash/config";
import { showHelp as showHelpCompletionsBashScript } from "help/completions/bash/script";
import { showHelp as showHelpCompletionsFish } from "help/completions/fish";
import { showHelp as showHelpCompletionsFishConfig } from "help/completions/fish/config";
import { showHelp as showHelpCompletionsFishScript } from "help/completions/fish/script";
import { showHelp as showHelpCompletionsPowershell } from "help/completions/powershell";
import { showHelp as showHelpCompletionsPowershellConfig } from "help/completions/powershell/config";
import { showHelp as showHelpCompletionsPowershellScript } from "help/completions/powershell/script";
import { showHelp as showHelpCompletionsZsh } from "help/completions/zsh";
import { showHelp as showHelpCompletionsZshConfig } from "help/completions/zsh/config";
import { showHelp as showHelpCompletionsZshScript } from "help/completions/zsh/script";
import { showHelp as showHelpDiff } from "help/diff";
import { showHelp as showHelpDocs } from "help/docs";
import { showHelp as showHelpHelp } from "help/help";
import { showHelp as showHelpInfo } from "help/info";
import { showHelp as showHelpInit } from "help/init";
import { showHelp as showHelpRegistry } from "help/registry";
import { showHelp as showHelpRegistryValidate } from "help/registry/validate";
import { showHelp as showHelpSearch } from "help/search";
import { showHelp as showHelpUpdate } from "help/update";
import { showHelp as showHelpView } from "help/view";

// Generated by Power Plant
// Please do not edit this file manually - it will be automatically overwritten
// the next time the generator is run.

/**
 * Display command usage details and other useful information to the user.
 *
 * @param commands - The command segments for the command to show help for. This
 *   is used to determine which command's help information to display. If no
 *   commands are provided, general help information about the CLI application
 *   will be displayed.
 */
export default async function handler(commands: string[] = []) {
  if (commands.join("/").toLowerCase() === "add") {
    showHelpAdd();
  } else if (commands.join("/").toLowerCase() === "build") {
    showHelpBuild();
  } else if (commands.join("/").toLowerCase() === "completions") {
    showHelpCompletions();
  } else if (commands.join("/").toLowerCase() === "completions/bash") {
    showHelpCompletionsBash();
  } else if (commands.join("/").toLowerCase() === "completions/bash/config") {
    showHelpCompletionsBashConfig();
  } else if (commands.join("/").toLowerCase() === "completions/bash/script") {
    showHelpCompletionsBashScript();
  } else if (commands.join("/").toLowerCase() === "completions/fish") {
    showHelpCompletionsFish();
  } else if (commands.join("/").toLowerCase() === "completions/fish/config") {
    showHelpCompletionsFishConfig();
  } else if (commands.join("/").toLowerCase() === "completions/fish/script") {
    showHelpCompletionsFishScript();
  } else if (commands.join("/").toLowerCase() === "completions/powershell") {
    showHelpCompletionsPowershell();
  } else if (
    commands.join("/").toLowerCase() === "completions/powershell/config"
  ) {
    showHelpCompletionsPowershellConfig();
  } else if (
    commands.join("/").toLowerCase() === "completions/powershell/script"
  ) {
    showHelpCompletionsPowershellScript();
  } else if (commands.join("/").toLowerCase() === "completions/zsh") {
    showHelpCompletionsZsh();
  } else if (commands.join("/").toLowerCase() === "completions/zsh/config") {
    showHelpCompletionsZshConfig();
  } else if (commands.join("/").toLowerCase() === "completions/zsh/script") {
    showHelpCompletionsZshScript();
  } else if (commands.join("/").toLowerCase() === "diff") {
    showHelpDiff();
  } else if (commands.join("/").toLowerCase() === "docs") {
    showHelpDocs();
  } else if (commands.join("/").toLowerCase() === "help") {
    showHelpHelp();
  } else if (commands.join("/").toLowerCase() === "info") {
    showHelpInfo();
  } else if (commands.join("/").toLowerCase() === "init") {
    showHelpInit();
  } else if (commands.join("/").toLowerCase() === "registry") {
    showHelpRegistry();
  } else if (commands.join("/").toLowerCase() === "registry/validate") {
    showHelpRegistryValidate();
  } else if (commands.join("/").toLowerCase() === "search") {
    showHelpSearch();
  } else if (commands.join("/").toLowerCase() === "update") {
    showHelpUpdate();
  } else if (commands.join("/").toLowerCase() === "view") {
    showHelpView();
  } else {
    showHelp();
  }
}
