/* eslint-disable */
/* oxlint-disable */
// biome-ignore lint: disable

import { showHelp } from "shell-shock:help";
import { showHelp as showHelpBuild } from "shell-shock:help/build";
import { showHelp as showHelpChangelog } from "shell-shock:help/changelog";
import { showHelp as showHelpClean } from "shell-shock:help/clean";
import { showHelp as showHelpCompletions } from "shell-shock:help/completions";
import { showHelp as showHelpCompletionsBash } from "shell-shock:help/completions/bash";
import { showHelp as showHelpCompletionsBashConfig } from "shell-shock:help/completions/bash/config";
import { showHelp as showHelpCompletionsBashScript } from "shell-shock:help/completions/bash/script";
import { showHelp as showHelpCompletionsFish } from "shell-shock:help/completions/fish";
import { showHelp as showHelpCompletionsFishConfig } from "shell-shock:help/completions/fish/config";
import { showHelp as showHelpCompletionsFishScript } from "shell-shock:help/completions/fish/script";
import { showHelp as showHelpCompletionsPowershell } from "shell-shock:help/completions/powershell";
import { showHelp as showHelpCompletionsPowershellConfig } from "shell-shock:help/completions/powershell/config";
import { showHelp as showHelpCompletionsPowershellScript } from "shell-shock:help/completions/powershell/script";
import { showHelp as showHelpCompletionsZsh } from "shell-shock:help/completions/zsh";
import { showHelp as showHelpCompletionsZshConfig } from "shell-shock:help/completions/zsh/config";
import { showHelp as showHelpCompletionsZshScript } from "shell-shock:help/completions/zsh/script";
import { showHelp as showHelpCreate } from "shell-shock:help/create";
import { showHelp as showHelpDeploy } from "shell-shock:help/deploy";
import { showHelp as showHelpDocs } from "shell-shock:help/docs";
import { showHelp as showHelpGC } from "shell-shock:help/gc";
import { showHelp as showHelpHelp } from "shell-shock:help/help";
import { showHelp as showHelpLint } from "shell-shock:help/lint";
import { showHelp as showHelpPrepare } from "shell-shock:help/prepare";
import { showHelp as showHelpTypes } from "shell-shock:help/types";
import { showHelp as showHelpUpdate } from "shell-shock:help/update";

// Generated by Shell Shock
// Do not edit this file manually - it will be overwritten automatically.
// Automatic overwrites can be disabled by using the `output.overwrite` option.

/**
 * Display command usage details and other useful information to the user.
 *
 * @param commands - The command segments for the command to show help for. This
 *   is used to determine which command's help information to display. If no
 *   commands are provided, general help information about the CLI application
 *   will be displayed.
 */
export default async function handler(commands: string[] = []) {
  if (commands.join("/").toLowerCase() === "build") {
    showHelpBuild();
  } else if (commands.join("/").toLowerCase() === "changelog") {
    showHelpChangelog();
  } else if (commands.join("/").toLowerCase() === "clean") {
    showHelpClean();
  } else if (commands.join("/").toLowerCase() === "completions") {
    showHelpCompletions();
  } else if (commands.join("/").toLowerCase() === "completions/bash") {
    showHelpCompletionsBash();
  } else if (commands.join("/").toLowerCase() === "completions/bash/config") {
    showHelpCompletionsBashConfig();
  } else if (commands.join("/").toLowerCase() === "completions/bash/script") {
    showHelpCompletionsBashScript();
  } else if (commands.join("/").toLowerCase() === "completions/fish") {
    showHelpCompletionsFish();
  } else if (commands.join("/").toLowerCase() === "completions/fish/config") {
    showHelpCompletionsFishConfig();
  } else if (commands.join("/").toLowerCase() === "completions/fish/script") {
    showHelpCompletionsFishScript();
  } else if (commands.join("/").toLowerCase() === "completions/powershell") {
    showHelpCompletionsPowershell();
  } else if (
    commands.join("/").toLowerCase() === "completions/powershell/config"
  ) {
    showHelpCompletionsPowershellConfig();
  } else if (
    commands.join("/").toLowerCase() === "completions/powershell/script"
  ) {
    showHelpCompletionsPowershellScript();
  } else if (commands.join("/").toLowerCase() === "completions/zsh") {
    showHelpCompletionsZsh();
  } else if (commands.join("/").toLowerCase() === "completions/zsh/config") {
    showHelpCompletionsZshConfig();
  } else if (commands.join("/").toLowerCase() === "completions/zsh/script") {
    showHelpCompletionsZshScript();
  } else if (commands.join("/").toLowerCase() === "create") {
    showHelpCreate();
  } else if (commands.join("/").toLowerCase() === "deploy") {
    showHelpDeploy();
  } else if (commands.join("/").toLowerCase() === "docs") {
    showHelpDocs();
  } else if (commands.join("/").toLowerCase() === "gc") {
    showHelpGC();
  } else if (commands.join("/").toLowerCase() === "help") {
    showHelpHelp();
  } else if (commands.join("/").toLowerCase() === "lint") {
    showHelpLint();
  } else if (commands.join("/").toLowerCase() === "prepare") {
    showHelpPrepare();
  } else if (commands.join("/").toLowerCase() === "types") {
    showHelpTypes();
  } else if (commands.join("/").toLowerCase() === "update") {
    showHelpUpdate();
  } else {
    showHelp();
  }
}
