/* eslint-disable */
/* oxlint-disable */
// biome-ignore lint: disable

import { showBanner } from "shell-shock:banner/help";
import { textColors, writeLine } from "shell-shock:console";
import { env, isDebug, isDevelopment } from "shell-shock:env";
import { showHelp } from "shell-shock:help/help";
import {
  type GlobalOptions,
  isHelp,
  useArgs,
  useGlobalOptions,
  withCommand
} from "shell-shock:state";
import { executeUpdate } from "shell-shock:update";
import { isInteractive } from "shell-shock:utils";
import handleHelp from "./command";

// Generated by Power Plant
// Please do not edit this file manually - it will be automatically overwritten
// the next time the generator is run.

export interface HelpOptions extends GlobalOptions {}

/**
 * The Help (cyclone-ui help) command.
 *
 * @remarks
 * Display command usage details and other useful information to the user.
 *
 * @title Help
 *
 * @param args - The command-line arguments passed to the command.
 */
export async function handler(args: string[] = useArgs()) {
  const options = {
    ...useGlobalOptions()
  } as unknown as HelpOptions;

  for (let i = 0; i < args.slice(0).length; i++) {
    const arg: string =
      args[i].length > 3 && args[i].startsWith("--")
        ? `--${args[i].slice(2).replaceAll("-", "").toLowerCase().replaceAll("-", "").replaceAll("_", "")}`
        : args[i].length > 2 && args[i].startsWith("-")
          ? `-${args[i].slice(1).replaceAll("-", "")}`
          : args[i];
  }

  let optionsIndex: number =
    Math.max(
      0,
      args
        .slice(2)
        .findIndex(
          arg =>
            arg.startsWith("-") &&
            /^()=?.*$/.test(
              arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
            )
        )
    ) + 2;

  let argsIndex: number =
    optionsIndex > 2
      ? 2
      : Math.max(
          0,
          args
            .slice(optionsIndex)
            .findLastIndex(
              arg =>
                arg.startsWith("-") &&
                /^()=?.*$/.test(
                  arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
                )
            )
        ) + 2;

  let commands: string[] | undefined = [] as string[] | undefined;

  if (argsIndex + 0 < args.length && argsIndex + 0 !== optionsIndex) {
    commands = args
      .slice(
        argsIndex + 0,
        (optionsIndex > argsIndex ? optionsIndex : args.length) - 1
      )
      .join(" ")
      .split(",")
      .map(item =>
        item
          .trim()
          .replace(/^("|')/, "")
          .replace(/("|')$/, "")
      )
      .filter(Boolean) as string[] | undefined;
  }

  await showBanner();
  await executeUpdate();

  if (!isHelp()) {
    writeLine("");
    if (isDevelopment || isDebug || env.LOG_LEVEL === "debug") {
      writeLine(
        textColors.body.tertiary(
          "Debug mode is enabled. Additional debug information may be logged to the console."
        )
      );
    }
  }

  if (!isInteractive) {
    const failures: string[] = [];
  }

  if (options.help) {
    return showHelp();
  } else {
    return withCommand("help", ["help"], [commands], handleHelp);
  }
}
