/* eslint-disable */
/* oxlint-disable */
// biome-ignore lint: disable

import { showBanner } from "shell-shock:banner/help";
import { error, italic, textColors, writeLine } from "shell-shock:console";
import { env, isDebug, isDevelopment } from "shell-shock:env";
import { showHelp } from "shell-shock:help/help";
import { isCancel, text } from "shell-shock:prompts";
import {
  type GlobalOptions,
  isHelp,
  useArgs,
  useGlobalOptions,
  withCommand
} from "shell-shock:state";
import { executeUpdate } from "shell-shock:update";
import { isInteractive } from "shell-shock:utils";
import handleHelp from "./command";

// Generated by Shell Shock
// Do not edit this file manually - it will be overwritten automatically.
// Automatic overwrites can be disabled by using the `output.overwrite` option.

export interface HelpOptions extends GlobalOptions {}

/**
 * The Help (powerlines help) command.
 *
 * @remarks
 * Display command usage details and other useful information to the user.
 *
 * @title Help
 *
 * @param args - The command-line arguments passed to the command.
 */
export async function handler(args: string[] = useArgs()) {
  const options = {
    ...useGlobalOptions()
  } as unknown as HelpOptions;

  for (let i = 0; i < args.slice(0).length; i++) {
    const arg: string =
      args[i].length > 3 && args[i].startsWith("--")
        ? `--${args[i].slice(2).replaceAll("-", "").toLowerCase().replaceAll("-", "").replaceAll("_", "")}`
        : args[i].length > 2 && args[i].startsWith("-")
          ? `-${args[i].slice(1).replaceAll("-", "")}`
          : args[i];
  }

  let optionsIndex: number =
    Math.max(
      0,
      args
        .slice(2)
        .findIndex(
          arg =>
            arg.startsWith("-") &&
            /^()=?.*$/.test(
              arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
            )
        )
    ) + 2;

  let argsIndex: number =
    optionsIndex > 2
      ? 2
      : Math.max(
          0,
          args
            .slice(optionsIndex)
            .findLastIndex(
              arg =>
                arg.startsWith("-") &&
                /^()=?.*$/.test(
                  arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
                )
            )
        ) + 2;

  let commands: string[] = [] as string[];

  if (argsIndex + 0 < args.length && argsIndex + 0 !== optionsIndex) {
    commands = args
      .slice(
        argsIndex + 0,
        (optionsIndex > argsIndex ? optionsIndex : args.length) - 1
      )
      .join(" ")
      .split(",")
      .map(item =>
        item
          .trim()
          .replace(/^("|')/, "")
          .replace(/("|')$/, "")
      )
      .filter(Boolean) as string[];
  }

  await showBanner();
  await executeUpdate();

  if (!isHelp()) {
    writeLine("");
    if (isDevelopment || isDebug || env.LOG_LEVEL === "debug") {
      writeLine(
        textColors.body.tertiary(
          "Debug mode is enabled. Additional debug information may be logged to the console."
        )
      );
    }
  }

  if (!isInteractive) {
    const failures: string[] = [];

    if (!commands) {
      failures.push('Missing required "commands" positional argument');
    } else if (commands.length === 0) {
      failures.push(
        'No values were provided to the required "commands" array positional argument'
      );
    }
  } else if (!isHelp() && (!commands || commands.length === 0)) {
    writeLine("");

    if (!commands) {
      const value = await text({
        message: `Please provide a value for the ${italic("commands")} argument`,
        description: `An argument that allows the user to specify custom Commands...`,
        validate(val) {
          if (!val || val.trim() === "") {
            return "A value must be provided for this argument";
          }

          return null;
        }
      });
      if (isCancel(value)) {
        return;
      }

      commands = value;
    } else if (commands.length === 0) {
      const value = await text({
        message: `Please provide one or more values for the ${italic("commands")} argument (values are separated by a \",\" character)`,
        description: `An argument that allows the user to specify custom Commands...`,
        validate(val) {
          if (!val || val.trim() === "") {
            return "A value must be provided for this argument";
          }
          if (
            val
              .split(",")
              .map(v => v.trim())
              .filter(Boolean).length === 0
          ) {
            return "At least one value must be provided for this argument";
          }

          return undefined;
        }
      });
      if (isCancel(value)) {
        return;
      }

      commands = value
        .split(",")
        .map(value => value.trim())
        .filter(Boolean);
    }
    writeLine("");

    const failures: string[] = [];

    if (!commands) {
      failures.push('Missing required "commands" positional argument');
    } else if (commands.length === 0) {
      failures.push(
        'No values were provided to the required "commands" array positional argument'
      );
    }
    if (failures.length > 0) {
      error(
        `The following validation failures were found while processing the user provided input, and must be corrected before the ${italic("Help")} command can be executed: \n\n${failures.map(failure => " - " + failure).join("\n")}`
      );
      options.help = true;
    }
  }

  if (options.help) {
    return showHelp();
  } else {
    return withCommand("help", ["help"], [commands], handleHelp);
  }
}
