/**
 * A collection of utility functions that assist in displaying help information for the Analyze Accessibility command.
 *
 * @module shell-shock:help/analyze-a11y
 */

/* eslint-disable */
/* oxlint-disable */
// biome-ignore lint: disable

import {
  bold,
  inverse,
  link,
  table,
  textColors,
  writeLine
} from "shell-shock:console";

// Generated by Power Plant
// Please do not edit this file manually - it will be automatically overwritten
// the next time the generator is run.

/**
 * Utility functions for displaying help information for the Analyze Accessibility command.
 *
 * @remarks
 * This module contains utility functions that assist in displaying help information for the Analyze Accessibility command. The main function exported by this module is the `showHelp` function, which can be used to display help information for the specified command or application. This function can be called from within the command's handler or from any other part of the application where help information needs to be displayed.
 */
/**
 * Display help information for the Analyze Accessibility command.
 */
export function showHelp() {
  writeLine(
    `${bold(textColors.heading.secondary("Tags: "))} ${textColors.tags.designSystem ? textColors.tags.designSystem(inverse(" Design System ")) : textColors.tags.default(inverse(" Design System "))} ${textColors.tags.accessibility ? textColors.tags.accessibility(inverse(" Accessibility ")) : textColors.tags.default(inverse(" Accessibility "))}`,
    { padding: 0 }
  );
  writeLine("");

  writeLine(bold(textColors.heading.secondary("Usage:")));
  writeLine(
    textColors.body.secondary(
      `${textColors.usage.bin(">_ cyclone-ui")} ${textColors.usage.command("analyze-a11y")} ${textColors.usage.options("[options]")}`
    ),
    { padding: 0 }
  );

  writeLine("");
  writeLine(bold(textColors.heading.secondary("Options:")));
  table([
    [
      {
        value: textColors.body.primary("--code <code>"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Source code of a React component or JSX snippet to analyze.`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("--color, --colors"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Force colored terminal output (env: CYCLONE_UI_COLOR, default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("--no-color, --no-colors"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Force disable colored terminal output (env: CYCLONE_UI_NO_COLOR, default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("--component-name <component_name>"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Optional label for the component under review.`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("--context <context>"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Optional usage context (for example \"in a form\" or \"modal\").`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("--file <file>"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Path to a source file to analyze (alternative to --code).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("-?, -h, --help"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Show help information (default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("-i, --interact, --interactive"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Enable interactive mode - will be set to false if running in a CI pipeline (env: CYCLONE_UI_INTERACTIVE, default: true).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("--no-interactive, --non-interactive"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Disable interactive mode - will be set to true if running in a CI pipeline (env: CYCLONE_UI_NON_INTERACTIVE, default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("--hide-banner, --no-banner"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Do not display the application banner displayed while running the CLI - will be set to true if running in a CI pipeline (env: CYCLONE_UI_NO_BANNER, default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("--no-color, --no-colors"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Force disable colored terminal output (env: CYCLONE_UI_NO_COLOR, default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("--no-interactive, --non-interactive"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Disable interactive mode - will be set to true if running in a CI pipeline (env: CYCLONE_UI_NON_INTERACTIVE, default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("--pattern-analysis"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Run regex-based heuristics (unlabeled buttons, missing alt, …) (default: true).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("--quiet"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Suppress command decorations and diagnostic messages (default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("-V, --verbose"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Enable verbose output (env: CYCLONE_UI_VERBOSE, default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("-v, --version"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Show the version of the application (default: false).`
        ),
        align: "left",
        border: "none"
      }
    ],
    [
      {
        value: textColors.body.primary("-y, --yes"),
        align: "right",
        border: "none",
        maxWidth: "1/3"
      },
      {
        value: textColors.body.tertiary(
          `Skip all prompts by answering yes to all of them - will be set to true if running in a CI pipeline (env: CYCLONE_UI_YES, default: false).`
        ),
        align: "left",
        border: "none"
      }
    ]
  ]);

  writeLine("");

  writeLine(
    textColors.body.tertiary(
      `More information can be found in the Analyze Accessibility command documentation at ${link("https://docs.cyclone-ui.com/reference/cli/analyze-a11y")}${textColors.body.tertiary(".")}`
    ),
    { padding: 0 }
  );
  writeLine("");
}
