/* eslint-disable */
/* oxlint-disable */
// biome-ignore lint: disable

import { showBanner } from "shell-shock:banner/search-icons";
import { error, italic, textColors, writeLine } from "shell-shock:console";
import { env, isDebug, isDevelopment } from "shell-shock:env";
import { showHelp } from "shell-shock:help/search-icons";
import { isCancel, text } from "shell-shock:prompts";
import {
  type GlobalOptions,
  hasFlag,
  isHelp,
  useArgs,
  useGlobalOptions,
  withCommand
} from "shell-shock:state";
import { executeUpdate } from "shell-shock:update";
import { isInteractive } from "shell-shock:utils";
import handleSearchIcons from "./command";

// Generated by Power Plant
// Please do not edit this file manually - it will be automatically overwritten
// the next time the generator is run.

export interface SearchIconsOptions extends GlobalOptions {
  /**
   * One or more search terms (fuzzy match). Example: ["search", "folder", "user"].
   */
  terms: string[];
  /**
   * Maximum matches per term.
   */
  limit?: number | undefined;
}

/**
 * The Search Icons (cyclone-ui search-icons) command.
 *
 * @remarks
 * Search design-system icons by name, title, aliases, tags and category. Returns name and asset files for each match.
 *
 * @title Search Icons
 *
 * @param args - The command-line arguments passed to the command.
 */
export async function handler(args: string[] = useArgs()) {
  const options = {
    ...useGlobalOptions(),
    terms: [],
    limit: 2
  } as unknown as SearchIconsOptions;

  for (let i = 0; i < args.slice(0).length; i++) {
    const arg: string =
      args[i].length > 3 && args[i].startsWith("--")
        ? `--${args[i].slice(2).replaceAll("-", "").toLowerCase().replaceAll("-", "").replaceAll("_", "")}`
        : args[i].length > 2 && args[i].startsWith("-")
          ? `-${args[i].slice(1).replaceAll("-", "")}`
          : args[i];
    if (
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("terms=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "terms" ||
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("terms=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "terms"
    ) {
      options.terms ??= [];
      if (
        /^--?(terms)=/.test(
          "-" + arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
        )
      ) {
        options.terms.push(
          ...arg
            .replace(/^--?(terms)=/, "")
            .split(",")
            .map(item =>
              item
                .trim()
                .replace(/^("|')/, "")
                .replace(/("|')$/, "")
            )
            .filter(Boolean)
        );
      } else if (args.length > i + 1) {
        options.terms.push(
          ...args[++i]
            .split(",")
            .map(item =>
              item
                .trim()
                .replace(/^("|')/, "")
                .replace(/("|')$/, "")
            )
            .filter(Boolean)
        );
      }
    } else if (
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("limit=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "limit" ||
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("limit=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "limit"
    ) {
      if (
        /^--?(limit)=/.test(
          "-" + arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
        )
      ) {
        const value = Number(
          arg
            .replace(/^--?(limit)=/, "")
            .trim()
            .replace(/^("|')/, "")
            .replace(/("|')$/, "")
        );
        if (!Number.isNaN(value)) {
          options.limit = value;
        }
      } else if (args.length > i + 1) {
        const value = Number(
          args[++i]
            .trim()
            .replace(/^("|')/, "")
            .replace(/("|')$/, "")
        );
        if (!Number.isNaN(value)) {
          options.limit = value;
        }
      }
    }
  }

  if (!hasFlag("quiet")) {
    await showBanner();
    await executeUpdate();
  }

  if (!isHelp() && !hasFlag("quiet")) {
    writeLine("");
    if (isDevelopment || isDebug || env.LOG_LEVEL === "debug") {
      writeLine(
        textColors.body.tertiary(
          "Debug mode is enabled. Additional debug information may be logged to the console."
        )
      );
    }
  }

  if (!isInteractive) {
    const failures: string[] = [];
    if (!options.terms) {
      failures.push('Missing required "terms" option');
    } else if (options.terms.length === 0) {
      failures.push(
        'No values were provided to the required "terms" array option'
      );
    }

    if (options.limit && Number.isNaN(options.limit)) {
      failures.push('Invalid numeric value provided for the "limit" option');
    }
  } else if (!isHelp() && (!options.terms || options.terms.length === 0)) {
    writeLine("");

    if (!options.terms) {
      const value = await text({
        message: `Please provide a value for the ${italic("terms")} option`,
        description: `One or more search terms (fuzzy match). Example: [\"search\", \"folder\", \"user\"].`,
        validate(val) {
          if (!val || val.trim() === "") {
            return "A value must be provided for this option";
          }

          return null;
        }
      });
      if (isCancel(value)) {
        return;
      }

      options.terms = value;
    } else if (options.terms.length === 0) {
      const value = await text({
        message: `Please provide one or more values for the ${italic("terms")} option (values are separated by a \",\" character)`,
        description: `One or more search terms (fuzzy match). Example: [\"search\", \"folder\", \"user\"].`,
        validate(val) {
          if (!val || val.trim() === "") {
            return "A value must be provided for this option";
          }
          if (
            val
              .split(",")
              .map(v => v.trim())
              .filter(Boolean).length === 0
          ) {
            return "At least one value must be provided for this option";
          }

          return undefined;
        }
      });
      if (isCancel(value)) {
        return;
      }

      options.terms = value
        .split(",")
        .map(value => value.trim())
        .filter(Boolean);
    }

    writeLine("");

    const failures: string[] = [];
    if (!options.terms) {
      failures.push('Missing required "terms" option');
    } else if (options.terms.length === 0) {
      failures.push(
        'No values were provided to the required "terms" array option'
      );
    }

    if (options.limit && Number.isNaN(options.limit)) {
      failures.push('Invalid numeric value provided for the "limit" option');
    }

    if (failures.length > 0) {
      error(
        `The following validation failures were found while processing the user provided input, and must be corrected before the ${italic("Search Icons")} command can be executed: \n\n${failures.map(failure => " - " + failure).join("\n")}`
      );
      options.help = true;
    }
  }

  if (options.help) {
    return showHelp();
  } else {
    return withCommand(
      "search-icons",
      ["search-icons"],
      [options],
      handleSearchIcons
    );
  }
}
