/* -------------------------------------------------------------------

                   🗲 Storm Software - Powerlines

 This code was released as part of the Powerlines project. Powerlines
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/powerlines.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/powerlines
 Documentation:            https://docs.stormsoftware.com/projects/powerlines
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import type { CommandMetadata } from "@shell-shock/core";
import { removeDirectory } from "@stryke/fs";
import { createPowerlines } from "../../utilities/create-powerlines";

export const metadata = {
  title: "Garbage Collection",
  description:
    "Perform garbage collection to clean up unnecessary system files based on the specified options. This can help free up disk space and improve system performance. Please note: the actual types of environment paths available for cleanup may vary based on the project's configuration and the underlying system's operating system.",
  icon: "🗶",
  tags: ["Utility"],
  alias: ["garbage-collection"]
} satisfies CommandMetadata;

export interface GarbageCollectionOptions {
  /**
   * The type of environment paths to clean up. Can be "data", "cache", "logs", "temp", or "all" to clean all types.
   *
   * @remarks
   * This option allows you to specify which types of environment paths should be targeted for garbage collection. Depending on the project's configuration and the underlying system's operating system, the actual types of environment paths available for cleanup may vary. Common types include:
   * - "data": User-specific data files.
   * - "cache": Temporary files used for caching purposes.
   * - "logs": Log files generated by the application.
   * - "temp": Temporary files that may not fit into the other categories.
   * - "all": Clean all types of environment paths.
   */
  type?: "data" | "cache" | "logs" | "temp" | "all";
}

/**
 * Perform garbage collection to clean up unnecessary system files based on the specified options. This can help free up disk space and improve system performance.
 *
 * @param options - The options for garbage collection.
 * @param type - The type of environment paths to clean up. Can be "data", "cache", "logs", "temp", or "all" to clean all types.
 * @returns A promise that resolves when the garbage collection process is complete.
 */
async function handler(
  options: GarbageCollectionOptions = {},
  type: "data" | "cache" | "logs" | "temp" | "all" = "all"
) {
  const engine = await createPowerlines({ root: process.cwd(), ...options });

  const envPaths = [] as string[];
  if (type === "all" || type === "data") {
    envPaths.push(engine.context.envPaths.data);
  }
  if (type === "all" || type === "cache") {
    envPaths.push(engine.context.envPaths.cache);
  }
  if (type === "all" || type === "logs") {
    envPaths.push(engine.context.envPaths.log);
  }
  if (type === "all" || type === "temp") {
    envPaths.push(engine.context.envPaths.temp);
  }

  await Promise.all(
    envPaths.map(async path => {
      await removeDirectory(path);
    })
  );
}

export default handler;
