import { create } from "storybook/theming";

/**
 * Storybook UI themes generated by `@razorwind/storybook`.
 *
 * @see https://storybook.js.org/docs/configure/user-interface/theming
 */
export default {
  dark: create({
    brandTarget: "_blank",
    base: "dark",
    barBg: {"$type":"color","colorSpace":"display-p3","$value":"{color.base.1}","$description":"The primary foreground color for the dark theme","filePath":"/home/development/repos/cyclone-ui/packages/themes/src/tokens/semantic/dark.tokens.json","isSource":true},
    barHoverColor: {"$type":"color","colorSpace":"display-p3","$value":"{color.base.8}","$description":"The secondary foreground color for the dark theme","filePath":"/home/development/repos/cyclone-ui/packages/themes/src/tokens/semantic/dark.tokens.json","isSource":true},
    brandImage: "https://public.storm-cdn.com/cyclone-ui/assets/dark-logo.svg",
    brandTitle: "Cyclone UI",
    brandUrl: "https://cyclone-ui.com"
  }),
  light: create({
    brandTarget: "_blank",
    base: "light",
    barBg: {"$type":"color","colorSpace":"display-p3","$value":"{color.base.1}","$description":"The primary foreground color for the light theme","filePath":"/home/development/repos/cyclone-ui/packages/themes/src/tokens/semantic/light.tokens.json","isSource":true},
    barHoverColor: {"$type":"color","colorSpace":"display-p3","$value":"{color.base.8}","$description":"The secondary foreground color for the light theme","filePath":"/home/development/repos/cyclone-ui/packages/themes/src/tokens/semantic/light.tokens.json","isSource":true},
    brandImage: "https://public.storm-cdn.com/cyclone-ui/assets/light-logo.svg",
    brandTitle: "Cyclone UI",
    brandUrl: "https://cyclone-ui.com"
  })
};
