import { create } from "storybook/theming";

/**
 * Storybook UI themes generated by `@razorwind/storybook`.
 *
 * @see https://storybook.js.org/docs/configure/user-interface/theming
 */
export default {
  dark: create({
    brandTarget: "_blank",
    base: "dark",
    colorPrimary: "#fafafa",
    colorSecondary: "#3a3a3a",
    textColor: "#fafafa",
    appBg: "#1f1f21",
    appContentBg: "#1f1f21",
    appPreviewBg: "#1f1f21",
    appBorderColor: "#616161",
    barTextColor: "#fafafa",
    barSelectedColor: "#2dbc9c",
    barBg: "#2b2c30",
    barHoverColor: "#3a3a3a",
    buttonBg: "#242528",
    buttonBorder: "#616161",
    inputBg: "#242528",
    inputBorder: "#616161",
    inputTextColor: "#fafafa",
    booleanBg: "#242528",
    booleanSelectedBg: "#3a3a3a",
    brandImage: "https://public.storm-cdn.com/cyclone-ui/assets/dark-logo.svg",
    brandTitle: "Cyclone UI",
    brandUrl: "https://cyclone-ui.com"
  }),
  light: create({
    brandTarget: "_blank",
    base: "light",
    colorPrimary: "#f1f1f1",
    colorSecondary: "#242528",
    textColor: "#f1f1f1",
    appBg: "#eaeaea",
    appContentBg: "#eaeaea",
    appPreviewBg: "#eaeaea",
    appBorderColor: "#3a3a3a",
    barTextColor: "#f1f1f1",
    barSelectedColor: "#166855",
    barBg: "#fafafa",
    barHoverColor: "#242528",
    buttonBg: "#f1f1f1",
    buttonBorder: "#3a3a3a",
    inputBg: "#f1f1f1",
    inputBorder: "#3a3a3a",
    inputTextColor: "#f1f1f1",
    booleanBg: "#f1f1f1",
    booleanSelectedBg: "#242528",
    brandImage: "https://public.storm-cdn.com/cyclone-ui/assets/light-logo.svg",
    brandTitle: "Cyclone UI",
    brandUrl: "https://cyclone-ui.com"
  })
};
