import { create } from "storybook/theming";

/**
 * Storybook UI themes generated by `@razorwind/storybook`.
 *
 * @see https://storybook.js.org/docs/configure/user-interface/theming
 */
export default {
  dark: create({
    brandTarget: "_blank",
    base: "dark",
    colorPrimary: "#ffffff",
    colorSecondary: "#e8e9e9",
    textColor: "#ffffff",
    appBg: "#0d0c07",
    appContentBg: "#0d0c07",
    appPreviewBg: "#0d0c07",
    appBorderColor: "#74787c",
    barTextColor: "#ffffff",
    barSelectedColor: "#36dec0",
    barBg: "#2a2c33",
    barHoverColor: "#8b8f92",
    buttonBg: "#212121",
    buttonBorder: "#74787c",
    inputBg: "#212121",
    inputBorder: "#74787c",
    inputTextColor: "#ffffff",
    booleanBg: "#212121",
    booleanSelectedBg: "#8b8f92",
    brandImage: "https://public.storm-cdn.com/cyclone-ui/assets/dark-logo.svg",
    brandTitle: "Cyclone UI",
    brandUrl: "https://cyclone-ui.com"
  }),
  light: create({
    brandTarget: "_blank",
    base: "light",
    colorPrimary: "#f4f4f4",
    colorSecondary: "#1fb2a6",
    textColor: "#f4f4f4",
    appBg: "#ffffff",
    appContentBg: "#ffffff",
    appPreviewBg: "#ffffff",
    appBorderColor: "#262626",
    barTextColor: "#f4f4f4",
    barSelectedColor: "#1fb2a6",
    barBg: "#e8e7e6",
    barHoverColor: "#f4f4f4",
    buttonBg: "#f4f4f3",
    buttonBorder: "#262626",
    inputBg: "#f4f4f3",
    inputBorder: "#262626",
    inputTextColor: "#f4f4f4",
    booleanBg: "#f4f4f3",
    booleanSelectedBg: "#f4f4f4",
    brandImage: "https://public.storm-cdn.com/cyclone-ui/assets/light-logo.svg",
    brandTitle: "Cyclone UI",
    brandUrl: "https://cyclone-ui.com"
  })
};
