/* eslint-disable */

/*
 * Generated by @razorwind/tamagui — Do not edit by hand.
 * 
 * @see https://tamagui.dev/docs/core/configuration
 * @see https://tamagui.dev/docs/intro/themes
 * @see https://tamagui.dev/docs/guides/theme-builder
 */

import { isWeb } from '@tamagui/constants';
import { animations } from "@tamagui/config/v5-motion";
import userConfig from "./default-config";
import { createThemes } from "@tamagui/theme-builder";
import { createTamagui, px, createTokens, createFont } from "@tamagui/core";

const tokens = createTokens({
  color: {
    blue1: "#abcaff",
    blue2: "#8cb6ff",
    blue3: "#6da2ff",
    blue4: "#4d8eff",
    blue5: "#2e7aff",
    blue6: "#2768d9",
    blue7: "#2055b3",
    blue8: "#19438c",
    blue9: "#123166",
    green1: "#d1f1d6",
    green2: "#a2e3b6",
    green3: "#74d59f",
    green4: "#45c791",
    green5: "#38a97e",
    green6: "#2c8a69",
    green7: "#216b53",
    green8: "#164a3c",
    green9: "#0c2a22",
    neutral1: "#fafafa",
    neutral2: "#f1f1f1",
    neutral3: "#eaeaea",
    neutral4: "#e1e1e1",
    neutral5: "#cacacb",
    neutral6: "#b0b0b1",
    neutral7: "#959698",
    neutral8: "#7b7b7e",
    neutral9: "#606164",
    neutral10: "#46464a",
    neutral11: "#2b2c30",
    neutral12: "#242528",
    neutral13: "#1f1f21",
    neutral14: "#151518",
    orange1: "#f6c3a7",
    orange2: "#f4b18c",
    orange3: "#f19f71",
    orange4: "#ef8c56",
    orange5: "#ec7a3b",
    orange6: "#df6520",
    orange7: "#bf520b",
    orange8: "#9f4000",
    orange9: "#803000",
    pink1: "#f5c7e4",
    pink2: "#f49ed1",
    pink3: "#eb89c5",
    pink4: "#e774bb",
    pink5: "#e171b7",
    pink6: "#df6db3",
    pink7: "#c25c9b",
    pink8: "#904272",
    pink9: "#482039",
    purple1: "#cec2ee",
    purple2: "#baa9e8",
    purple3: "#a690e1",
    purple4: "#9277da",
    purple5: "#7f64c4",
    purple6: "#6c53ad",
    purple7: "#594395",
    purple8: "#47347c",
    purple9: "#362661",
    red1: "#e2819a",
    red2: "#dd6c89",
    red3: "#d95778",
    red4: "#d44267",
    red5: "#cf2d56",
    red6: "#ae284a",
    red7: "#8e223e",
    red8: "#6f1c31",
    red9: "#501524",
    yellow1: "#facd7b",
    yellow2: "#f9c25e",
    yellow3: "#f8b740",
    yellow4: "#f7ac23",
    yellow5: "#f0a824",
    yellow6: "#df9d24",
    yellow7: "#c58c22",
    yellow8: "#a2731e",
    yellow9: "#765417"
  },
  space: {
    "2xl": 10,
    "3xl": 13,
    "4xl": 16,
    "5xl": 18,
    "6xl": 21,
    "7xl": 24,
    "8xl": 32,
    "9xl": 39,
    "10xl": 46,
    "11xl": 53,
    "12xl": 60,
    "13xl": 74,
    "14xl": 88,
    "15xl": 102,
    "16xl": 116,
    "17xl": 130,
    "18xl": 144,
    "19xl": 144,
    "20xl": 158,
    "21xl": 172,
    "22xl": 186,
    lg: 4,
    md: 2,
    sm: 1.5,
    xl: 7,
    xs: 1,
    xxs: 0.5,
    zero: 0
  },
  size: {
    "2xl": 16,
    "3xl": 18,
    "4xl": 20,
    "5xl": 22,
    "6xl": 24,
    "7xl": 26,
    "8xl": 32,
    "9xl": 37,
    "10xl": 42,
    "11xl": 47,
    "12xl": 52,
    "13xl": 62,
    "14xl": 72,
    "15xl": 82,
    "16xl": 92,
    "17xl": 102,
    "18xl": 112,
    "19xl": 112,
    "20xl": 122,
    "21xl": 132,
    "22xl": 142,
    "23xl": 152,
    "24xl": 162,
    "25xl": 172,
    "26xl": 182,
    "27xl": 192,
    "28xl": 202,
    "29xl": 212,
    "30xl": 222,
    "31xl": 232,
    "32xl": 242,
    "33xl": 252,
    "34xl": 262,
    "35xl": 272,
    "36xl": 282,
    "37xl": 284,
    lg: 12,
    md: 10,
    sm: 8,
    xl: 14,
    xs: 4,
    xxs: 2,
    zero: 0
  },
  radius: {
    "2xl": 16,
    "3xl": 24,
    "4xl": 32,
    button: 8,
    card: 6,
    checkbox: 6,
    container: 8,
    control: 8,
    dialog: 12,
    drawer: 32,
    full: "100%",
    lg: 8,
    md: 6,
    popover: 6,
    sheet: 0,
    sm: 4,
    tooltip: 6,
    xl: 12,
    xs: 2,
    zero: 0
  },
  zIndex: {
    "0": 0,
    "10": 100,
    "20": 200,
    "30": 300,
    "40": 400,
    "50": 500,
    "60": 600,
    "70": 700,
    "80": 800,
    "90": 900
  },
  blur: {
    "2xl": px(40),
    "3xl": px(64),
    lg: px(16),
    md: px(12),
    sm: px(8),
    xl: px(24),
    xs: px(4)
  },
  fontSize: {
    "2xl": px(30),
    "3xl": px(36),
    "4xl": px(48),
    "5xl": px(60),
    "6xl": px(72),
    "7xl": px(96),
    "8xl": px(128),
    "9xl": px(160),
    "10xl": px(192),
    "11xl": px(224),
    "12xl": px(256),
    "13xl": px(288),
    "14xl": px(320),
    "15xl": px(384),
    lg: px(20),
    md: px(18),
    sm: px(16),
    xl: px(24),
    xs: px(14),
    xxs: px(12)
  },
  shadow: {
    "2xl": "0px 25px 50px -12px #00000040",
    "2xs": "0px 1px 0px 0px #0000000d",
    lg: "0px 10px 15px -3px #0000001a, 0px 4px 6px -4px #0000001a",
    md: "0px 4px 6px -1px #0000001a, 0px 2px 4px -2px #0000001a",
    sm: "0px 1px 3px 0px #0000001a, 0px 1px 2px -1px #0000001a",
    xl: "0px 20px 25px -5px #0000001a, 0px 8px 10px -6px #0000001a",
    xs: "0px 1px 2px 0px #0000000d"
  },
  insetShadow: {
    "2xs": "inset 0px 1px 0px 0px #0000000d",
    sm: "inset 0px 2px 4px 0px #0000000d",
    xs: "inset 0px 1px 1px 0px #0000000d"
  },
  dropShadow: {
    "2xl": "drop-shadow(0px 25px 25px #00000026)",
    lg: "drop-shadow(0px 4px 4px #00000026)",
    md: "drop-shadow(0px 3px 3px #0000001f)",
    sm: "drop-shadow(0px 1px 2px #00000026)",
    xl: "drop-shadow(0px 9px 7px #0000001a)",
    xs: "drop-shadow(0px 1px 1px #0000000d)"
  },
  textShadow: {
    "2xs": "0px 1px 0px 0px #00000026",
    lg: "0px 1px 2px 0px #0000001a, 0px 3px 2px 0px #0000001a, 0px 4px 8px 0px #0000001a",
    md: "0px 1px 1px 0px #0000001a, 0px 1px 2px 0px #0000001a, 0px 2px 4px 0px #0000001a",
    sm: "0px 1px 0px 0px #00000013, 0px 1px 1px 0px #00000013, 0px 2px 2px 0px #00000013",
    xs: "0px 1px 1px 0px #00000033"
  },
  fontWeight: {
    black: 900,
    bold: 700,
    extrabold: 800,
    extralight: 200,
    light: 300,
    medium: 500,
    normal: 400,
    semibold: 600,
    thin: 100
  }
});

const childThemeExtras: {
  light: Record<string, Record<string, string>>;
  dark: Record<string, Record<string, string>>;
} = {
  light: {
    base: {
      accent: tokens.color.neutral14.val,
      accentActive: "#0c0c0d",
      accentDisabled: "#151517",
      accentHover: "#232326",
      accentInactive: "#030303",
      muted: tokens.color.neutral3.val,
      mutedActive: "#cacaca",
      mutedDisabled: "#eaeaea66",
      mutedHover: "#919191",
      mutedInactive: "#030303",
      onAccent: tokens.color.neutral2.val,
      onAccentActive: "#0c0c0d",
      onAccentDisabled: "#f1f1f166",
      onAccentHover: "#959595",
      onAccentInactive: "#030303",
      onMuted: tokens.color.neutral14.val,
      onMutedActive: "#0c0c0d",
      onMutedDisabled: "#151517",
      onMutedHover: "#232326",
      onMutedInactive: "#030303",
      ring: "0px 0px 0px 3px #15151814",
      ringOffset: "0px 0px 0px 3px #f1f1f1, 0px 0px 0px 6px #15151814",
      ringSubtle: "0px 0px 0px 1px #15151814",
      ringSubtleOffset: "0px 0px 0px 3px #f1f1f1, 0px 0px 0px 4px #15151814"
    },
    brand: {
      accent: "#1fb2a6",
      accentActive: "#008a7f",
      accentDisabled: "#4daea4",
      accentHover: "#008277",
      accentInactive: "#5ddfd2",
      muted: "#68e8db",
      mutedActive: "#25b4a8",
      mutedDisabled: "#84e3d9",
      mutedHover: "#08a99e",
      mutedInactive: "#9bffff",
      onAccent: "#FAFAFA",
      onAccentActive: "#bebebe",
      onAccentDisabled: "#fafafa66",
      onAccentHover: "#b2b2b2",
      onAccentInactive: "#ffffff",
      onMuted: "#1fb2a6",
      onMutedActive: "#008a7f",
      onMutedDisabled: "#4daea4",
      onMutedHover: "#008277",
      onMutedInactive: "#5ddfd2",
      ring: "0px 0px 0px 3px #1fb2a626",
      ringOffset: "0px 0px 0px 3px #f1f1f1, 0px 0px 0px 6px #1fb2a626",
      ringSubtle: "0px 0px 0px 1px #1fb2a626",
      ringSubtleOffset: "0px 0px 0px 3px #f1f1f1, 0px 0px 0px 4px #1fb2a626"
    },
    danger: {
      accent: tokens.color.red7.val,
      accentActive: "#730029",
      accentDisabled: "#843142",
      accentHover: "#6e0025",
      accentInactive: "#ab3e56",
      muted: "#e37085",
      mutedActive: "#b74960",
      mutedDisabled: "#d67a89",
      mutedHover: "#ae4158",
      mutedInactive: "#ff9baf",
      onAccent: "#FAFAFA",
      onAccentActive: "#bebebe",
      onAccentDisabled: "#fafafa66",
      onAccentHover: "#b2b2b2",
      onAccentInactive: "#ffffff",
      onMuted: "#2f000c",
      onMutedActive: "#390714",
      onMutedDisabled: "#2b050e",
      onMutedHover: "#3b0916",
      onMutedInactive: "#240005",
      ring: "0px 0px 0px 3px #8e223e26",
      ringOffset: "0px 0px 0px 3px #f1f1f1, 0px 0px 0px 6px #8e223e26",
      ringSubtle: "0px 0px 0px 1px #8e223e26",
      ringSubtleOffset: "0px 0px 0px 3px #f1f1f1, 0px 0px 0px 4px #8e223e26"
    },
    discovery: {
      accent: tokens.color.purple7.val,
      accentActive: "#432b7b",
      accentDisabled: "#584889",
      accentHover: "#3f2676",
      accentInactive: "#725db2",
      muted: "#9e8ae4",
      mutedActive: "#7863ba",
      mutedDisabled: "#9d8ed6",
      mutedHover: "#715bb1",
      mutedInactive: "#c9b5ff",
      onAccent: "#FAFAFA",
      onAccentActive: "#bebebe",
      onAccentDisabled: "#fafafa66",
      onAccentHover: "#b2b2b2",
      onAccentInactive: "#ffffff",
      onMuted: "#20004c",
      onMutedActive: "#290d58",
      onMutedDisabled: "#1e0a42",
      onMutedHover: "#2b105a",
      onMutedInactive: "#17003f",
      ring: "0px 0px 0px 3px #59439526",
      ringOffset: "0px 0px 0px 3px #f1f1f1, 0px 0px 0px 6px #59439526",
      ringSubtle: "0px 0px 0px 1px #59439526",
      ringSubtleOffset: "0px 0px 0px 3px #f1f1f1, 0px 0px 0px 4px #59439526"
    },
    info: {
      accent: tokens.color.blue7.val,
      accentActive: "#033a96",
      accentDisabled: "#2f58a2",
      accentHover: "#003590",
      accentInactive: "#3b72d3",
      muted: "#659dff",
      mutedActive: "#3f74d3",
      mutedDisabled: "#729fec",
      mutedHover: "#376cc9",
      mutedInactive: "#90cbff",
      onAccent: "#FAFAFA",
      onAccentActive: "#bebebe",
      onAccentDisabled: "#fafafa66",
      onAccentHover: "#b2b2b2",
      onAccentInactive: "#ffffff",
      onMuted: "#001c54",
      onMutedActive: "#000f47",
      onMutedDisabled: "#071f4a",
      onMutedHover: "#000c44",
      onMutedInactive: "#0a2a63",
      ring: "0px 0px 0px 3px #2055b326",
      ringOffset: "0px 0px 0px 3px #f1f1f1, 0px 0px 0px 6px #2055b326",
      ringSubtle: "0px 0px 0px 1px #2055b326",
      ringSubtleOffset: "0px 0px 0px 3px #f1f1f1, 0px 0px 0px 4px #2055b326"
    },
    negative: {
      accent: tokens.color.red7.val,
      accentActive: "#730029",
      accentDisabled: "#843142",
      accentHover: "#6e0025",
      accentInactive: "#ab3e56",
      muted: "#e37085",
      mutedActive: "#b74960",
      mutedDisabled: "#d67a89",
      mutedHover: "#ae4158",
      mutedInactive: "#ff9baf",
      onAccent: "#FAFAFA",
      onAccentActive: "#bebebe",
      onAccentDisabled: "#fafafa66",
      onAccentHover: "#b2b2b2",
      onAccentInactive: "#ffffff",
      onMuted: "#2f000c",
      onMutedActive: "#390714",
      onMutedDisabled: "#2b050e",
      onMutedHover: "#3b0916",
      onMutedInactive: "#240005",
      ring: "0px 0px 0px 3px #8e223e26",
      ringOffset: "0px 0px 0px 3px #f1f1f1, 0px 0px 0px 6px #8e223e26",
      ringSubtle: "0px 0px 0px 1px #8e223e26",
      ringSubtleOffset: "0px 0px 0px 3px #f1f1f1, 0px 0px 0px 4px #8e223e26"
    },
    positive: {
      accent: tokens.color.green7.val,
      accentActive: "#00523b",
      accentDisabled: "#336855",
      accentHover: "#004d36",
      accentInactive: "#40876e",
      muted: "#6ab196",
      mutedActive: "#41896f",
      mutedDisabled: "#77ae98",
      mutedHover: "#388067",
      mutedInactive: "#96dfc2",
      onAccent: "#FAFAFA",
      onAccentActive: "#bebebe",
      onAccentDisabled: "#fafafa66",
      onAccentHover: "#b2b2b2",
      onAccentInactive: "#ffffff",
      onMuted: "#002b1e",
      onMutedActive: "#001f13",
      onMutedDisabled: "#0b2a1f",
      onMutedHover: "#001d11",
      onMutedInactive: "#0f382a",
      ring: "0px 0px 0px 3px #216b5326",
      ringOffset: "0px 0px 0px 3px #f1f1f1, 0px 0px 0px 6px #216b5326",
      ringSubtle: "0px 0px 0px 1px #216b5326",
      ringSubtleOffset: "0px 0px 0px 3px #f1f1f1, 0px 0px 0px 4px #216b5326"
    },
    success: {
      accent: tokens.color.green7.val,
      accentActive: "#00523b",
      accentDisabled: "#336855",
      accentHover: "#004d36",
      accentInactive: "#40876e",
      muted: "#6ab196",
      mutedActive: "#41896f",
      mutedDisabled: "#77ae98",
      mutedHover: "#388067",
      mutedInactive: "#96dfc2",
      onAccent: "#FAFAFA",
      onAccentActive: "#bebebe",
      onAccentDisabled: "#fafafa66",
      onAccentHover: "#b2b2b2",
      onAccentInactive: "#ffffff",
      onMuted: "#002b1e",
      onMutedActive: "#001f13",
      onMutedDisabled: "#0b2a1f",
      onMutedHover: "#001d11",
      onMutedInactive: "#0f382a",
      ring: "0px 0px 0px 3px #216b5326",
      ringOffset: "0px 0px 0px 3px #f1f1f1, 0px 0px 0px 6px #216b5326",
      ringSubtle: "0px 0px 0px 1px #216b5326",
      ringSubtleOffset: "0px 0px 0px 3px #f1f1f1, 0px 0px 0px 4px #216b5326"
    },
    warning: {
      accent: tokens.color.yellow9.val,
      accentActive: "#5d3c00",
      accentDisabled: "#71562a",
      accentHover: "#573700",
      accentInactive: "#926f36",
      muted: "#bd985e",
      mutedActive: "#947137",
      mutedDisabled: "#b79a6d",
      mutedHover: "#8c692e",
      mutedInactive: "#ebc489",
      onAccent: "#FAFAFA",
      onAccentActive: "#bebebe",
      onAccentDisabled: "#fafafa66",
      onAccentHover: "#b2b2b2",
      onAccentInactive: "#ffffff",
      onMuted: "#2d1c00",
      onMutedActive: "#392709",
      onMutedDisabled: "#2a1d07",
      onMutedHover: "#3b290c",
      onMutedInactive: "#211100",
      ring: "0px 0px 0px 3px #76541726",
      ringOffset: "0px 0px 0px 3px #f1f1f1, 0px 0px 0px 6px #76541726",
      ringSubtle: "0px 0px 0px 1px #76541726",
      ringSubtleOffset: "0px 0px 0px 3px #f1f1f1, 0px 0px 0px 4px #76541726"
    }
  },
  dark: {
    base: {
      accent: tokens.color.neutral1.val,
      accentActive: "#ffffff",
      accentDisabled: "#fafafa66",
      accentHover: "#9b9b9b",
      accentInactive: "#808080",
      muted: tokens.color.neutral11.val,
      mutedActive: "#333438",
      mutedDisabled: "#2b2c2f",
      mutedHover: "#414347",
      mutedInactive: "#808080",
      onAccent: tokens.color.neutral14.val,
      onAccentActive: "#ffffff",
      onAccentDisabled: "#151517",
      onAccentHover: "#232326",
      onAccentInactive: "#808080",
      onMuted: tokens.color.neutral1.val,
      onMutedActive: "#ffffff",
      onMutedDisabled: "#fafafa66",
      onMutedHover: "#9b9b9b",
      onMutedInactive: "#808080",
      ring: "0px 0px 0px 3px #fafafa14",
      ringOffset: "0px 0px 0px 3px #1f1f21, 0px 0px 0px 6px #fafafa14",
      ringSubtle: "0px 0px 0px 1px #fafafa14",
      ringSubtleOffset: "0px 0px 0px 3px #1f1f21, 0px 0px 0px 4px #fafafa14"
    },
    brand: {
      accent: "#3be4be",
      accentActive: "#00b28f",
      accentDisabled: "#6adfc0",
      accentHover: "#00a785",
      accentInactive: "#81fff4",
      muted: "#007e5e",
      mutedActive: "#359c7a",
      mutedDisabled: "#2f7b61",
      mutedHover: "#3da280",
      mutedInactive: "#005f41",
      onAccent: "#151518",
      onAccentActive: "#1d1d20",
      onAccentDisabled: "#151517",
      onAccentHover: "#1f1f22",
      onAccentInactive: "#0c0c0f",
      onMuted: "#3be4be",
      onMutedActive: "#00b28f",
      onMutedDisabled: "#6adfc0",
      onMutedHover: "#00a785",
      onMutedInactive: "#81fff4",
      ring: "0px 0px 0px 3px #3be4be26",
      ringOffset: "0px 0px 0px 3px #1f1f21, 0px 0px 0px 6px #3be4be26",
      ringSubtle: "0px 0px 0px 1px #3be4be26",
      ringSubtleOffset: "0px 0px 0px 3px #1f1f21, 0px 0px 0px 4px #3be4be26"
    },
    danger: {
      accent: tokens.color.red5.val,
      accentActive: "#f55474",
      accentDisabled: "#c0455d",
      accentHover: "#fd5b7b",
      accentInactive: "#a70037",
      muted: "#6b0023",
      mutedActive: "#7f1b33",
      mutedDisabled: "#621727",
      mutedHover: "#842036",
      mutedInactive: "#550013",
      onAccent: "#FAFAFA",
      onAccentActive: "#bebebe",
      onAccentDisabled: "#fafafa66",
      onAccentHover: "#b2b2b2",
      onAccentInactive: "#ffffff",
      onMuted: "#ff96a3",
      onMutedActive: "#cd6977",
      onMutedDisabled: "#f39ea7",
      onMutedHover: "#c2606e",
      onMutedInactive: "#ffc9d5",
      ring: "0px 0px 0px 3px #cf2d5626",
      ringOffset: "0px 0px 0px 3px #1f1f21, 0px 0px 0px 6px #cf2d5626",
      ringSubtle: "0px 0px 0px 1px #cf2d5626",
      ringSubtleOffset: "0px 0px 0px 3px #1f1f21, 0px 0px 0px 4px #cf2d5626"
    },
    discovery: {
      accent: tokens.color.purple4.val,
      accentActive: "#b69cff",
      accentDisabled: "#907ccb",
      accentHover: "#bea4ff",
      accentInactive: "#6d51b0",
      muted: "#51328f",
      mutedActive: "#6548a7",
      mutedDisabled: "#4f3982",
      mutedHover: "#6a4dac",
      mutedInactive: "#3c1875",
      onAccent: "#FAFAFA",
      onAccentActive: "#bebebe",
      onAccentDisabled: "#fafafa66",
      onAccentHover: "#b2b2b2",
      onAccentInactive: "#ffffff",
      onMuted: "#d3c7ff",
      onMutedActive: "#a195ca",
      onMutedDisabled: "#d2c9f6",
      onMutedHover: "#968bbf",
      onMutedInactive: "#fff6ff",
      ring: "0px 0px 0px 3px #9277da26",
      ringOffset: "0px 0px 0px 3px #1f1f21, 0px 0px 0px 6px #9277da26",
      ringSubtle: "0px 0px 0px 1px #9277da26",
      ringSubtleOffset: "0px 0px 0px 3px #1f1f21, 0px 0px 0px 4px #9277da26"
    },
    info: {
      accent: tokens.color.blue4.val,
      accentActive: "#72b6ff",
      accentDisabled: "#5d91ea",
      accentHover: "#7abeff",
      accentInactive: "#2564d1",
      muted: "#0146b0",
      mutedActive: "#205fcb",
      mutedDisabled: "#1b4b9d",
      mutedHover: "#2564d1",
      mutedInactive: "#002a94",
      onAccent: "#FAFAFA",
      onAccentActive: "#bebebe",
      onAccentDisabled: "#fafafa66",
      onAccentHover: "#b2b2b2",
      onAccentInactive: "#ffffff",
      onMuted: "#c7dcff",
      onMutedActive: "#93a7c9",
      onMutedDisabled: "#cbdcf8",
      onMutedHover: "#899cbd",
      onMutedInactive: "#ebffff",
      ring: "0px 0px 0px 3px #4d8eff26",
      ringOffset: "0px 0px 0px 3px #1f1f21, 0px 0px 0px 6px #4d8eff26",
      ringSubtle: "0px 0px 0px 1px #4d8eff26",
      ringSubtleOffset: "0px 0px 0px 3px #1f1f21, 0px 0px 0px 4px #4d8eff26"
    },
    negative: {
      accent: tokens.color.red5.val,
      accentActive: "#f55474",
      accentDisabled: "#c0455d",
      accentHover: "#fd5b7b",
      accentInactive: "#a70037",
      muted: "#6b0023",
      mutedActive: "#7f1b33",
      mutedDisabled: "#621727",
      mutedHover: "#842036",
      mutedInactive: "#550013",
      onAccent: "#FAFAFA",
      onAccentActive: "#bebebe",
      onAccentDisabled: "#fafafa66",
      onAccentHover: "#b2b2b2",
      onAccentInactive: "#ffffff",
      onMuted: "#ff96a3",
      onMutedActive: "#cd6977",
      onMutedDisabled: "#f39ea7",
      onMutedHover: "#c2606e",
      onMutedInactive: "#ffc9d5",
      ring: "0px 0px 0px 3px #cf2d5626",
      ringOffset: "0px 0px 0px 3px #1f1f21, 0px 0px 0px 6px #cf2d5626",
      ringSubtle: "0px 0px 0px 1px #cf2d5626",
      ringSubtleOffset: "0px 0px 0px 3px #1f1f21, 0px 0px 0px 4px #cf2d5626"
    },
    positive: {
      accent: tokens.color.green4.val,
      accentActive: "#78f5bc",
      accentDisabled: "#64c297",
      accentHover: "#82ffc6",
      accentInactive: "#009865",
      muted: "#00714c",
      mutedActive: "#2f8c65",
      mutedDisabled: "#296e50",
      mutedHover: "#36926b",
      mutedInactive: "#005532",
      onAccent: "#FAFAFA",
      onAccentActive: "#bebebe",
      onAccentDisabled: "#fafafa66",
      onAccentHover: "#b2b2b2",
      onAccentInactive: "#ffffff",
      onMuted: "#ffffff",
      onMutedActive: "#c2c2c2",
      onMutedDisabled: "#ffffff66",
      onMutedHover: "#b6b6b6",
      onMutedInactive: "#ffffff",
      ring: "0px 0px 0px 3px #45c79126",
      ringOffset: "0px 0px 0px 3px #1f1f21, 0px 0px 0px 6px #45c79126",
      ringSubtle: "0px 0px 0px 1px #45c79126",
      ringSubtleOffset: "0px 0px 0px 3px #1f1f21, 0px 0px 0px 4px #45c79126"
    },
    success: {
      accent: tokens.color.green4.val,
      accentActive: "#78f5bc",
      accentDisabled: "#64c297",
      accentHover: "#82ffc6",
      accentInactive: "#009865",
      muted: "#00714c",
      mutedActive: "#2f8c65",
      mutedDisabled: "#296e50",
      mutedHover: "#36926b",
      mutedInactive: "#005532",
      onAccent: "#FAFAFA",
      onAccentActive: "#bebebe",
      onAccentDisabled: "#fafafa66",
      onAccentHover: "#b2b2b2",
      onAccentInactive: "#ffffff",
      onMuted: "#ffffff",
      onMutedActive: "#c2c2c2",
      onMutedDisabled: "#ffffff66",
      onMutedHover: "#b6b6b6",
      onMutedInactive: "#ffffff",
      ring: "0px 0px 0px 3px #45c79126",
      ringOffset: "0px 0px 0px 3px #1f1f21, 0px 0px 0px 6px #45c79126",
      ringSubtle: "0px 0px 0px 1px #45c79126",
      ringSubtleOffset: "0px 0px 0px 3px #1f1f21, 0px 0px 0px 4px #45c79126"
    },
    warning: {
      accent: tokens.color.yellow4.val,
      accentActive: "#c67d00",
      accentDisabled: "#ecb055",
      accentHover: "#bb7400",
      accentInactive: "#ffe067",
      muted: "#845800",
      mutedActive: "#a0732a",
      mutedDisabled: "#7e5b25",
      mutedHover: "#a77931",
      mutedInactive: "#663c00",
      onAccent: "#151518",
      onAccentActive: "#1d1d20",
      onAccentDisabled: "#151517",
      onAccentHover: "#1f1f22",
      onAccentInactive: "#0c0c0f",
      onMuted: "#ffffff",
      onMutedActive: "#c2c2c2",
      onMutedDisabled: "#ffffff66",
      onMutedHover: "#b6b6b6",
      onMutedInactive: "#ffffff",
      ring: "0px 0px 0px 3px #f7ac2326",
      ringOffset: "0px 0px 0px 3px #1f1f21, 0px 0px 0px 6px #f7ac2326",
      ringSubtle: "0px 0px 0px 1px #f7ac2326",
      ringSubtleOffset: "0px 0px 0px 3px #1f1f21, 0px 0px 0px 4px #f7ac2326"
    }
  }
};

const themes = createThemes({
  componentThemes: false,
  base: {
    palette: {
      light: [
        tokens.color.neutral1.val,
        tokens.color.neutral2.val,
        tokens.color.neutral3.val,
        tokens.color.neutral4.val,
        tokens.color.neutral5.val,
        tokens.color.neutral6.val,
        tokens.color.neutral7.val,
        tokens.color.neutral8.val,
        tokens.color.neutral9.val,
        tokens.color.neutral10.val,
        tokens.color.neutral11.val,
        tokens.color.neutral12.val,
        tokens.color.neutral13.val,
        tokens.color.neutral14.val
      ],
      dark: [
        tokens.color.neutral14.val,
        tokens.color.neutral13.val,
        tokens.color.neutral12.val,
        tokens.color.neutral11.val,
        tokens.color.neutral10.val,
        tokens.color.neutral9.val,
        tokens.color.neutral8.val,
        tokens.color.neutral7.val,
        tokens.color.neutral6.val,
        tokens.color.neutral5.val,
        tokens.color.neutral4.val,
        tokens.color.neutral3.val,
        tokens.color.neutral2.val,
        tokens.color.neutral1.val
      ]
    },
    extra: {
      light: {
        black: "#0c0c0d",
        dataBlueEmphasis: tokens.color.blue7.val,
        dataBlueSubtle: tokens.color.blue3.val,
        dataBrandEmphasis: tokens.color.blue7.val,
        dataBrandSubtle: tokens.color.blue3.val,
        dataGreenEmphasis: tokens.color.green7.val,
        dataGreenSubtle: tokens.color.green3.val,
        dataNeutralEmphasis: tokens.color.neutral9.val,
        dataNeutralSubtle: tokens.color.neutral3.val,
        dataOrangeEmphasis: tokens.color.orange8.val,
        dataOrangeSubtle: tokens.color.orange3.val,
        dataPinkEmphasis: tokens.color.pink8.val,
        dataPinkSubtle: tokens.color.pink3.val,
        dataPurpleEmphasis: tokens.color.purple7.val,
        dataPurpleSubtle: tokens.color.purple3.val,
        dataRedEmphasis: tokens.color.red7.val,
        dataRedSubtle: tokens.color.red2.val,
        dataYellowEmphasis: tokens.color.yellow9.val,
        dataYellowSubtle: tokens.color.yellow3.val,
        hairline: tokens.color.neutral6.val,
        hairlineActive: "#9d9d9e",
        hairlineHover: "#7c7c7d",
        hairlineInactive: "#e1e1e2",
        inkBody: tokens.color.neutral9.val,
        inkEmphasis: tokens.color.neutral11.val,
        inkSubtle: tokens.color.neutral6.val,
        inkSubtlest: tokens.color.neutral5.val,
        link: tokens.color.blue7.val,
        linkActive: "#033a96",
        linkHover: "#003590",
        linkInactive: "#3b72d3",
        overlayBackdrop: "#1a1c1f66",
        overlayBackground: "#ffffff",
        overlayBorder: tokens.color.neutral6.val,
        required: tokens.color.red7.val,
        selectionBackground: "#1fb2a6",
        selectionForeground: "#FAFAFA",
        surfaceCanvas: tokens.color.neutral3.val,
        surfaceCanvasActive: "#b2b2b2",
        surfaceCanvasDisabled: "#eaeaea66",
        surfaceCanvasHover: "#a6a6a6",
        surfaceCanvasInactive: "#ffffff",
        surfaceElevated: tokens.color.neutral2.val,
        surfaceElevatedActive: "#b7b7b7",
        surfaceElevatedDisabled: "#f1f1f166",
        surfaceElevatedHover: "#ababab",
        surfaceElevatedInactive: "#ffffff",
        surfaceFloating: tokens.color.neutral1.val,
        surfaceFloatingActive: "#bebebe",
        surfaceFloatingDisabled: "#fafafa66",
        surfaceFloatingHover: "#b2b2b2",
        surfaceFloatingInactive: "#ffffff",
        surfaceOverlay: "#ffffff",
        surfaceOverlayActive: "#c2c2c2",
        surfaceOverlayDisabled: "#ffffff66",
        surfaceOverlayHover: "#b6b6b6",
        surfaceOverlayInactive: "#ffffff",
        surfaceSunken: tokens.color.neutral4.val,
        surfaceSunkenActive: "#ababab",
        surfaceSunkenDisabled: "#e1e1e166",
        surfaceSunkenHover: "#a0a0a0",
        surfaceSunkenInactive: "#ffffff",
        transparent: "#ffffff00",
        white: "#ffffff"
      },
      dark: {
        black: "#0c0c0d",
        dataBlueEmphasis: tokens.color.blue7.val,
        dataBlueSubtle: tokens.color.blue9.val,
        dataBrandEmphasis: tokens.color.blue2.val,
        dataBrandSubtle: tokens.color.blue4.val,
        dataGreenEmphasis: tokens.color.green6.val,
        dataGreenSubtle: tokens.color.green7.val,
        dataNeutralEmphasis: tokens.color.neutral1.val,
        dataNeutralSubtle: tokens.color.neutral14.val,
        dataOrangeEmphasis: tokens.color.orange6.val,
        dataOrangeSubtle: tokens.color.orange9.val,
        dataPinkEmphasis: tokens.color.pink6.val,
        dataPinkSubtle: tokens.color.pink9.val,
        dataPurpleEmphasis: tokens.color.purple6.val,
        dataPurpleSubtle: tokens.color.purple9.val,
        dataRedEmphasis: tokens.color.red7.val,
        dataRedSubtle: tokens.color.red9.val,
        dataYellowEmphasis: tokens.color.yellow5.val,
        dataYellowSubtle: tokens.color.yellow9.val,
        hairline: tokens.color.neutral9.val,
        hairlineActive: "#6b6c6f",
        hairlineHover: "#808184",
        hairlineInactive: "#454649",
        inkBody: tokens.color.neutral5.val,
        inkEmphasis: tokens.color.neutral4.val,
        inkSubtle: tokens.color.neutral7.val,
        inkSubtlest: tokens.color.neutral8.val,
        link: tokens.color.blue3.val,
        linkActive: "#95cdff",
        linkHover: "#9ed6ff",
        linkInactive: "#4375ce",
        overlayBackdrop: "#0d0c0766",
        overlayBackground: tokens.color.neutral11.val,
        overlayBorder: tokens.color.neutral8.val,
        required: tokens.color.red5.val,
        selectionBackground: "#3be4be",
        selectionForeground: "#151518",
        surfaceCanvas: tokens.color.neutral14.val,
        surfaceCanvasActive: "#1d1d20",
        surfaceCanvasDisabled: "#151517",
        surfaceCanvasHover: "#1f1f22",
        surfaceCanvasInactive: "#0c0c0f",
        surfaceElevated: tokens.color.neutral13.val,
        surfaceElevatedActive: "#2a2a2c",
        surfaceElevatedDisabled: "#1f1f21",
        surfaceElevatedHover: "#2c2c2e",
        surfaceElevatedInactive: "#141416",
        surfaceFloating: tokens.color.neutral12.val,
        surfaceFloatingActive: "#303134",
        surfaceFloatingDisabled: "#242527",
        surfaceFloatingHover: "#333437",
        surfaceFloatingInactive: "#18191b",
        surfaceOverlay: tokens.color.neutral11.val,
        surfaceOverlayActive: "#393a3e",
        surfaceOverlayDisabled: "#2b2c2f",
        surfaceOverlayHover: "#3c3d41",
        surfaceOverlayInactive: "#1d1e22",
        surfaceSunken: "#0c0c0d",
        surfaceSunkenActive: "#121213",
        surfaceSunkenDisabled: "#0c0c0d",
        surfaceSunkenHover: "#141415",
        surfaceSunkenInactive: "#060607",
        transparent: "#ffffff00",
        white: "#ffffff"
      }
    }
  },
  childrenThemes: {
    base: {},
    brand: {},
    danger: {},
    discovery: {},
    info: {},
    negative: {},
    positive: {},
    success: {},
    warning: {}
  },
  getTheme: ({ name, theme, scheme }) => {
    const child = name.replace(/^(?:light|dark)_/, "");
    if (child === name) {
      return theme;
    }

    const extras = childThemeExtras[scheme ?? "light"][child];

    return extras ? { ...theme, ...extras } : theme;
  }
});

const bodyMdFont = createFont({
  family: isWeb ? "\"Storm Sans\"" : "Storm Sans",
  size: {
    md: 18,
    true: 18
  },
  lineHeight: {
    md: 24.75,
    normal: 24.75,
    true: 24.75
  },
  weight: {
    md: "400",
    normal: "400",
    true: "400"
  },
  face: {
    100: { normal: "StormSans-Thin", italic: "StormSans-ThinItalic" },
    200: { normal: "StormSans-ExtraLight", italic: "StormSans-ExtraLightItalic" },
    300: { normal: "StormSans-Light", italic: "StormSans-LightItalic" },
    400: { normal: "StormSans-Regular", italic: "StormSans-Italic" },
    450: { normal: "StormSans-Text", italic: "StormSans-TextItalic" },
    500: { normal: "StormSans-Medium", italic: "StormSans-MediumItalic" },
    600: { normal: "StormSans-SemiBold", italic: "StormSans-SemiBoldItalic" },
    700: { normal: "StormSans-Bold", italic: "StormSans-BoldItalic" }
  }
});

const bodySmFont = createFont({
  family: isWeb ? "\"Storm Sans\"" : "Storm Sans",
  size: {
    sm: 16,
    true: 16
  },
  lineHeight: {
    normal: 22,
    sm: 22,
    true: 22
  },
  weight: {
    normal: "400",
    sm: "400",
    true: "400"
  },
  face: {
    100: { normal: "StormSans-Thin", italic: "StormSans-ThinItalic" },
    200: { normal: "StormSans-ExtraLight", italic: "StormSans-ExtraLightItalic" },
    300: { normal: "StormSans-Light", italic: "StormSans-LightItalic" },
    400: { normal: "StormSans-Regular", italic: "StormSans-Italic" },
    450: { normal: "StormSans-Text", italic: "StormSans-TextItalic" },
    500: { normal: "StormSans-Medium", italic: "StormSans-MediumItalic" },
    600: { normal: "StormSans-SemiBold", italic: "StormSans-SemiBoldItalic" },
    700: { normal: "StormSans-Bold", italic: "StormSans-BoldItalic" }
  }
});

const buttonFont = createFont({
  family: isWeb ? "\"Storm Sans\"" : "Storm Sans",
  size: {
    md: 18,
    true: 18
  },
  lineHeight: {
    md: 18,
    tight: 18,
    true: 18
  },
  weight: {
    md: "600",
    semibold: "600",
    true: "600"
  },
  face: {
    100: { normal: "StormSans-Thin", italic: "StormSans-ThinItalic" },
    200: { normal: "StormSans-ExtraLight", italic: "StormSans-ExtraLightItalic" },
    300: { normal: "StormSans-Light", italic: "StormSans-LightItalic" },
    400: { normal: "StormSans-Regular", italic: "StormSans-Italic" },
    450: { normal: "StormSans-Text", italic: "StormSans-TextItalic" },
    500: { normal: "StormSans-Medium", italic: "StormSans-MediumItalic" },
    600: { normal: "StormSans-SemiBold", italic: "StormSans-SemiBoldItalic" },
    700: { normal: "StormSans-Bold", italic: "StormSans-BoldItalic" }
  }
});

const captionFont = createFont({
  family: isWeb ? "\"Storm Sans\"" : "Storm Sans",
  size: {
    sm: 16,
    true: 16
  },
  lineHeight: {
    sm: 16,
    tight: 16,
    true: 16
  },
  weight: {
    normal: "400",
    sm: "400",
    true: "400"
  },
  face: {
    100: { normal: "StormSans-Thin", italic: "StormSans-ThinItalic" },
    200: { normal: "StormSans-ExtraLight", italic: "StormSans-ExtraLightItalic" },
    300: { normal: "StormSans-Light", italic: "StormSans-LightItalic" },
    400: { normal: "StormSans-Regular", italic: "StormSans-Italic" },
    450: { normal: "StormSans-Text", italic: "StormSans-TextItalic" },
    500: { normal: "StormSans-Medium", italic: "StormSans-MediumItalic" },
    600: { normal: "StormSans-SemiBold", italic: "StormSans-SemiBoldItalic" },
    700: { normal: "StormSans-Bold", italic: "StormSans-BoldItalic" }
  }
});

const codeFont = createFont({
  family: "Google Sans Code",
  size: {
    lg: 20,
    true: 20
  },
  lineHeight: {
    lg: 25,
    snug: 25,
    true: 25
  },
  weight: {
    lg: "400",
    normal: "400",
    true: "400"
  }
});

const displayHeroFont = createFont({
  family: isWeb ? "\"Storm Sans\"" : "Storm Sans",
  size: {
    "5xl": 60,
    true: 60
  },
  lineHeight: {
    "5xl": 75,
    snug: 75,
    true: 75
  },
  weight: {
    "5xl": "600",
    semibold: "600",
    true: "600"
  },
  face: {
    100: { normal: "StormSans-Thin", italic: "StormSans-ThinItalic" },
    200: { normal: "StormSans-ExtraLight", italic: "StormSans-ExtraLightItalic" },
    300: { normal: "StormSans-Light", italic: "StormSans-LightItalic" },
    400: { normal: "StormSans-Regular", italic: "StormSans-Italic" },
    450: { normal: "StormSans-Text", italic: "StormSans-TextItalic" },
    500: { normal: "StormSans-Medium", italic: "StormSans-MediumItalic" },
    600: { normal: "StormSans-SemiBold", italic: "StormSans-SemiBoldItalic" },
    700: { normal: "StormSans-Bold", italic: "StormSans-BoldItalic" }
  }
});

const displayLgFont = createFont({
  family: isWeb ? "\"Storm Sans\"" : "Storm Sans",
  size: {
    "3xl": 36,
    true: 36
  },
  lineHeight: {
    "3xl": 45,
    snug: 45,
    true: 45
  },
  weight: {
    "3xl": "600",
    semibold: "600",
    true: "600"
  },
  face: {
    100: { normal: "StormSans-Thin", italic: "StormSans-ThinItalic" },
    200: { normal: "StormSans-ExtraLight", italic: "StormSans-ExtraLightItalic" },
    300: { normal: "StormSans-Light", italic: "StormSans-LightItalic" },
    400: { normal: "StormSans-Regular", italic: "StormSans-Italic" },
    450: { normal: "StormSans-Text", italic: "StormSans-TextItalic" },
    500: { normal: "StormSans-Medium", italic: "StormSans-MediumItalic" },
    600: { normal: "StormSans-SemiBold", italic: "StormSans-SemiBoldItalic" },
    700: { normal: "StormSans-Bold", italic: "StormSans-BoldItalic" }
  }
});

const displayMdFont = createFont({
  family: isWeb ? "\"Storm Sans\"" : "Storm Sans",
  size: {
    true: 24,
    xl: 24
  },
  lineHeight: {
    snug: 30,
    true: 30,
    xl: 30
  },
  weight: {
    bold: "700",
    true: "700",
    xl: "700"
  },
  face: {
    100: { normal: "StormSans-Thin", italic: "StormSans-ThinItalic" },
    200: { normal: "StormSans-ExtraLight", italic: "StormSans-ExtraLightItalic" },
    300: { normal: "StormSans-Light", italic: "StormSans-LightItalic" },
    400: { normal: "StormSans-Regular", italic: "StormSans-Italic" },
    450: { normal: "StormSans-Text", italic: "StormSans-TextItalic" },
    500: { normal: "StormSans-Medium", italic: "StormSans-MediumItalic" },
    600: { normal: "StormSans-SemiBold", italic: "StormSans-SemiBoldItalic" },
    700: { normal: "StormSans-Bold", italic: "StormSans-BoldItalic" }
  }
});

const displaySmFont = createFont({
  family: isWeb ? "\"Storm Sans\"" : "Storm Sans",
  size: {
    lg: 20,
    true: 20
  },
  lineHeight: {
    lg: 25,
    snug: 25,
    true: 25
  },
  weight: {
    bold: "700",
    lg: "700",
    true: "700"
  },
  face: {
    100: { normal: "StormSans-Thin", italic: "StormSans-ThinItalic" },
    200: { normal: "StormSans-ExtraLight", italic: "StormSans-ExtraLightItalic" },
    300: { normal: "StormSans-Light", italic: "StormSans-LightItalic" },
    400: { normal: "StormSans-Regular", italic: "StormSans-Italic" },
    450: { normal: "StormSans-Text", italic: "StormSans-TextItalic" },
    500: { normal: "StormSans-Medium", italic: "StormSans-MediumItalic" },
    600: { normal: "StormSans-SemiBold", italic: "StormSans-SemiBoldItalic" },
    700: { normal: "StormSans-Bold", italic: "StormSans-BoldItalic" }
  }
});

const editorialHeroFont = createFont({
  family: isWeb ? "\"Storm Serif\"" : "Storm Serif",
  size: {
    "5xl": 60,
    true: 60
  },
  lineHeight: {
    "5xl": 75,
    snug: 75,
    true: 75
  },
  weight: {
    "5xl": "600",
    semibold: "600",
    true: "600"
  },
  face: {
    200: { normal: "StormSerif-ExtraLight", italic: "StormSerif-ExtraLightItalic" },
    300: { normal: "StormSerif-Light", italic: "StormSerif-LightItalic" },
    400: { normal: "StormSerif-Regular", italic: "StormSerif-Italic" },
    500: { normal: "StormSerif-Medium", italic: "StormSerif-MediumItalic" },
    600: { normal: "StormSerif-SemiBold", italic: "StormSerif-SemiBoldItalic" },
    700: { normal: "StormSerif-Bold", italic: "StormSerif-BoldItalic" },
    800: { normal: "StormSerif-ExtraBold", italic: "StormSerif-ExtraBoldItalic" }
  }
});

const editorialLgFont = createFont({
  family: isWeb ? "\"Storm Serif\"" : "Storm Serif",
  size: {
    "3xl": 36,
    true: 36
  },
  lineHeight: {
    "3xl": 45,
    snug: 45,
    true: 45
  },
  weight: {
    "3xl": "600",
    semibold: "600",
    true: "600"
  },
  face: {
    200: { normal: "StormSerif-ExtraLight", italic: "StormSerif-ExtraLightItalic" },
    300: { normal: "StormSerif-Light", italic: "StormSerif-LightItalic" },
    400: { normal: "StormSerif-Regular", italic: "StormSerif-Italic" },
    500: { normal: "StormSerif-Medium", italic: "StormSerif-MediumItalic" },
    600: { normal: "StormSerif-SemiBold", italic: "StormSerif-SemiBoldItalic" },
    700: { normal: "StormSerif-Bold", italic: "StormSerif-BoldItalic" },
    800: { normal: "StormSerif-ExtraBold", italic: "StormSerif-ExtraBoldItalic" }
  }
});

const editorialMdFont = createFont({
  family: isWeb ? "\"Storm Serif\"" : "Storm Serif",
  size: {
    true: 24,
    xl: 24
  },
  lineHeight: {
    snug: 30,
    true: 30,
    xl: 30
  },
  weight: {
    bold: "700",
    true: "700",
    xl: "700"
  },
  face: {
    200: { normal: "StormSerif-ExtraLight", italic: "StormSerif-ExtraLightItalic" },
    300: { normal: "StormSerif-Light", italic: "StormSerif-LightItalic" },
    400: { normal: "StormSerif-Regular", italic: "StormSerif-Italic" },
    500: { normal: "StormSerif-Medium", italic: "StormSerif-MediumItalic" },
    600: { normal: "StormSerif-SemiBold", italic: "StormSerif-SemiBoldItalic" },
    700: { normal: "StormSerif-Bold", italic: "StormSerif-BoldItalic" },
    800: { normal: "StormSerif-ExtraBold", italic: "StormSerif-ExtraBoldItalic" }
  }
});

const editorialSmFont = createFont({
  family: isWeb ? "\"Storm Serif\"" : "Storm Serif",
  size: {
    lg: 20,
    true: 20
  },
  lineHeight: {
    lg: 25,
    snug: 25,
    true: 25
  },
  weight: {
    bold: "700",
    lg: "700",
    true: "700"
  },
  face: {
    200: { normal: "StormSerif-ExtraLight", italic: "StormSerif-ExtraLightItalic" },
    300: { normal: "StormSerif-Light", italic: "StormSerif-LightItalic" },
    400: { normal: "StormSerif-Regular", italic: "StormSerif-Italic" },
    500: { normal: "StormSerif-Medium", italic: "StormSerif-MediumItalic" },
    600: { normal: "StormSerif-SemiBold", italic: "StormSerif-SemiBoldItalic" },
    700: { normal: "StormSerif-Bold", italic: "StormSerif-BoldItalic" },
    800: { normal: "StormSerif-ExtraBold", italic: "StormSerif-ExtraBoldItalic" }
  }
});

const eyebrowFont = createFont({
  family: isWeb ? "\"Storm Sans\"" : "Storm Sans",
  size: {
    md: 18,
    true: 18
  },
  lineHeight: {
    md: 18,
    tight: 18,
    true: 18
  },
  weight: {
    md: "600",
    semibold: "600",
    true: "600"
  },
  face: {
    100: { normal: "StormSans-Thin", italic: "StormSans-ThinItalic" },
    200: { normal: "StormSans-ExtraLight", italic: "StormSans-ExtraLightItalic" },
    300: { normal: "StormSans-Light", italic: "StormSans-LightItalic" },
    400: { normal: "StormSans-Regular", italic: "StormSans-Italic" },
    450: { normal: "StormSans-Text", italic: "StormSans-TextItalic" },
    500: { normal: "StormSans-Medium", italic: "StormSans-MediumItalic" },
    600: { normal: "StormSans-SemiBold", italic: "StormSans-SemiBoldItalic" },
    700: { normal: "StormSans-Bold", italic: "StormSans-BoldItalic" }
  }
});

const stormSansFont = createFont({
  family: isWeb ? "\"Storm Sans\"" : "Storm Sans",
  size: {
    1: 12,
    2: 14,
    3: 16,
    4: 18,
    5: 20,
    6: 24,
    7: 28,
    8: 32,
    9: 40,
    10: 48
  },
  face: {
    100: { normal: "StormSans-Thin", italic: "StormSans-ThinItalic" },
    200: { normal: "StormSans-ExtraLight", italic: "StormSans-ExtraLightItalic" },
    300: { normal: "StormSans-Light", italic: "StormSans-LightItalic" },
    400: { normal: "StormSans-Regular", italic: "StormSans-Italic" },
    450: { normal: "StormSans-Text", italic: "StormSans-TextItalic" },
    500: { normal: "StormSans-Medium", italic: "StormSans-MediumItalic" },
    600: { normal: "StormSans-SemiBold", italic: "StormSans-SemiBoldItalic" },
    700: { normal: "StormSans-Bold", italic: "StormSans-BoldItalic" }
  }
});

const stormSerifFont = createFont({
  family: isWeb ? "\"Storm Serif\"" : "Storm Serif",
  size: {
    1: 12,
    2: 14,
    3: 16,
    4: 18,
    5: 20,
    6: 24,
    7: 28,
    8: 32,
    9: 40,
    10: 48
  },
  face: {
    200: { normal: "StormSerif-ExtraLight", italic: "StormSerif-ExtraLightItalic" },
    300: { normal: "StormSerif-Light", italic: "StormSerif-LightItalic" },
    400: { normal: "StormSerif-Regular", italic: "StormSerif-Italic" },
    500: { normal: "StormSerif-Medium", italic: "StormSerif-MediumItalic" },
    600: { normal: "StormSerif-SemiBold", italic: "StormSerif-SemiBoldItalic" },
    700: { normal: "StormSerif-Bold", italic: "StormSerif-BoldItalic" },
    800: { normal: "StormSerif-ExtraBold", italic: "StormSerif-ExtraBoldItalic" }
  }
});

const titleLgFont = createFont({
  family: isWeb ? "\"Storm Sans\"" : "Storm Sans",
  size: {
    md: 18,
    true: 18
  },
  lineHeight: {
    md: 22.5,
    snug: 22.5,
    true: 22.5
  },
  weight: {
    md: "500",
    medium: "500",
    true: "500"
  },
  face: {
    100: { normal: "StormSans-Thin", italic: "StormSans-ThinItalic" },
    200: { normal: "StormSans-ExtraLight", italic: "StormSans-ExtraLightItalic" },
    300: { normal: "StormSans-Light", italic: "StormSans-LightItalic" },
    400: { normal: "StormSans-Regular", italic: "StormSans-Italic" },
    450: { normal: "StormSans-Text", italic: "StormSans-TextItalic" },
    500: { normal: "StormSans-Medium", italic: "StormSans-MediumItalic" },
    600: { normal: "StormSans-SemiBold", italic: "StormSans-SemiBoldItalic" },
    700: { normal: "StormSans-Bold", italic: "StormSans-BoldItalic" }
  }
});

const titleSmFont = createFont({
  family: isWeb ? "\"Storm Sans\"" : "Storm Sans",
  size: {
    true: 12,
    xxs: 12
  },
  lineHeight: {
    snug: 15,
    true: 15,
    xxs: 15
  },
  weight: {
    normal: "400",
    true: "400",
    xxs: "400"
  },
  face: {
    100: { normal: "StormSans-Thin", italic: "StormSans-ThinItalic" },
    200: { normal: "StormSans-ExtraLight", italic: "StormSans-ExtraLightItalic" },
    300: { normal: "StormSans-Light", italic: "StormSans-LightItalic" },
    400: { normal: "StormSans-Regular", italic: "StormSans-Italic" },
    450: { normal: "StormSans-Text", italic: "StormSans-TextItalic" },
    500: { normal: "StormSans-Medium", italic: "StormSans-MediumItalic" },
    600: { normal: "StormSans-SemiBold", italic: "StormSans-SemiBoldItalic" },
    700: { normal: "StormSans-Bold", italic: "StormSans-BoldItalic" }
  }
});


/**
 * Theme values available on `useTheme()` and `$` style props for the cyclone-ui.
 *
 * Derived from semantic color tokens mapped by `createThemes`. Nested
 * themes (`light_primary`, `dark_danger`, …) come from each token's
 * `theme` / `$theme` property.
 *
 * @see https://tamagui.dev/docs/intro/themes
 */
export interface AppTheme {
  accent: string;
  accentActive: string;
  accentDisabled: string;
  accentHover: string;
  accentInactive: string;
  black: string;
  dataBlueEmphasis: string;
  dataBlueSubtle: string;
  dataBrandEmphasis: string;
  dataBrandSubtle: string;
  dataGreenEmphasis: string;
  dataGreenSubtle: string;
  dataNeutralEmphasis: string;
  dataNeutralSubtle: string;
  dataOrangeEmphasis: string;
  dataOrangeSubtle: string;
  dataPinkEmphasis: string;
  dataPinkSubtle: string;
  dataPurpleEmphasis: string;
  dataPurpleSubtle: string;
  dataRedEmphasis: string;
  dataRedSubtle: string;
  dataYellowEmphasis: string;
  dataYellowSubtle: string;
  hairline: string;
  hairlineActive: string;
  hairlineHover: string;
  hairlineInactive: string;
  inkBody: string;
  inkEmphasis: string;
  inkSubtle: string;
  inkSubtlest: string;
  link: string;
  linkActive: string;
  linkHover: string;
  linkInactive: string;
  muted: string;
  mutedActive: string;
  mutedDisabled: string;
  mutedHover: string;
  mutedInactive: string;
  onAccent: string;
  onAccentActive: string;
  onAccentDisabled: string;
  onAccentHover: string;
  onAccentInactive: string;
  onMuted: string;
  onMutedActive: string;
  onMutedDisabled: string;
  onMutedHover: string;
  onMutedInactive: string;
  overlayBackdrop: string;
  overlayBackground: string;
  overlayBorder: string;
  required: string;
  ring: string;
  ringOffset: string;
  ringSubtle: string;
  ringSubtleOffset: string;
  selectionBackground: string;
  selectionForeground: string;
  surfaceCanvas: string;
  surfaceCanvasActive: string;
  surfaceCanvasDisabled: string;
  surfaceCanvasHover: string;
  surfaceCanvasInactive: string;
  surfaceElevated: string;
  surfaceElevatedActive: string;
  surfaceElevatedDisabled: string;
  surfaceElevatedHover: string;
  surfaceElevatedInactive: string;
  surfaceFloating: string;
  surfaceFloatingActive: string;
  surfaceFloatingDisabled: string;
  surfaceFloatingHover: string;
  surfaceFloatingInactive: string;
  surfaceOverlay: string;
  surfaceOverlayActive: string;
  surfaceOverlayDisabled: string;
  surfaceOverlayHover: string;
  surfaceOverlayInactive: string;
  surfaceSunken: string;
  surfaceSunkenActive: string;
  surfaceSunkenDisabled: string;
  surfaceSunkenHover: string;
  surfaceSunkenInactive: string;
  transparent: string;
  white: string;
}

/**
 * The Tamagui config for the cyclone-ui.
 *
 * @see https://tamagui.dev/docs/core/configuration
 */
export const config = createTamagui({
  animations,
  tokens,
  themes,
  fonts: {
     "body-md": bodyMdFont,
    "body-sm": bodySmFont,
    button: buttonFont,
    caption: captionFont,
    code: codeFont,
    "display-hero": displayHeroFont,
    "display-lg": displayLgFont,
    "display-md": displayMdFont,
    "display-sm": displaySmFont,
    "editorial-hero": editorialHeroFont,
    "editorial-lg": editorialLgFont,
    "editorial-md": editorialMdFont,
    "editorial-sm": editorialSmFont,
    eyebrow: eyebrowFont,
    stormSans: stormSansFont,
    stormSerif: stormSerifFont,
    "title-lg": titleLgFont,
    "title-sm": titleSmFont
   },
  defaultFont: "body-md",
  settings: { styleValueSyntax: "string", legacyConditionObjects: false }
, ...userConfig 
});

export type AppConfig = typeof config;

declare module "tamagui" {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface TamaguiCustomConfig extends AppConfig {}
}

export default config;
