/* eslint-disable */

/*
 * Generated by @razorwind/tamagui — Do not edit by hand.
 * 
 * @see https://tamagui.dev/docs/core/config-v5
 */

import { isWeb } from '@tamagui/constants';
import { createV5Theme, type CreateV5ThemeOptions } from "@tamagui/config/v5";
import { animations } from "@tamagui/config/v5-motion";
import userConfig from "./default-config";
import { createTamagui, px, createTokens, createFont } from "@tamagui/core";

const tokens = createTokens({
  color: {
    darkBackgroundAccent: "#36dec0",
    darkBackgroundAccentDisabled: "#36dec099",
    darkBackgroundAccentHover: "#009c82",
    darkBackgroundAccentSubtle: "#003832",
    darkBackgroundAccentSubtleDisabled: "#00383299",
    darkBackgroundAccentSubtleHover: "#1b4c46",
    darkBackgroundDanger: "#f57377",
    darkBackgroundDangerDisabled: "#f5737799",
    darkBackgroundDangerHover: "#b73a44",
    darkBackgroundDangerSubtle: "#b75357",
    darkBackgroundDangerSubtleDisabled: "#b7535799",
    darkBackgroundDangerSubtleHover: "#882830",
    darkBackgroundDiscovery: "#908ffe",
    darkBackgroundDiscoveryDisabled: "#908ffe99",
    darkBackgroundDiscoveryHover: "#5f59c2",
    darkBackgroundDiscoverySubtle: "#6c6bc1",
    darkBackgroundDiscoverySubtleDisabled: "#6c6bc199",
    darkBackgroundDiscoverySubtleHover: "#464193",
    darkBackgroundElevated: "#181b1b",
    darkBackgroundElevatedDisabled: "#181b1b99",
    darkBackgroundElevatedHover: "#252828",
    darkBackgroundFloating: "#222424",
    darkBackgroundFloatingDisabled: "#22242499",
    darkBackgroundFloatingHover: "#323434",
    darkBackgroundHighest: "#2e3030",
    darkBackgroundHighestDisabled: "#2e303099",
    darkBackgroundHighestHover: "#424444",
    darkBackgroundInfo: "#5ccbeb",
    darkBackgroundInfoDisabled: "#5ccbeb99",
    darkBackgroundInfoHover: "#008cab",
    darkBackgroundInfoSubtle: "#0081a5",
    darkBackgroundInfoSubtleDisabled: "#0081a599",
    darkBackgroundInfoSubtleHover: "#00587a",
    darkBackgroundLink: "#529cfc",
    darkBackgroundLinkDisabled: "#529cfc99",
    darkBackgroundLinkHover: "#1866c1",
    darkBackgroundPage: "#000101",
    darkBackgroundPageDisabled: "#00010199",
    darkBackgroundPageHover: "#000202",
    darkBackgroundPrimary: "#fafafa",
    darkBackgroundPrimaryDisabled: "#fafafa99",
    darkBackgroundPrimaryHover: "#aaaaaa",
    darkBackgroundSecondary: "#090c0c",
    darkBackgroundSecondaryDisabled: "#090c0c99",
    darkBackgroundSecondaryHover: "#111414",
    darkBackgroundSuccess: "#3bb974",
    darkBackgroundSuccessDisabled: "#3bb97499",
    darkBackgroundSuccessHover: "#008241",
    darkBackgroundSuccessSubtle: "#14874e",
    darkBackgroundSuccessSubtleDisabled: "#14874e99",
    darkBackgroundSuccessSubtleHover: "#005e28",
    darkBackgroundTertiary: "#090b0c",
    darkBackgroundTertiaryDisabled: "#090b0c99",
    darkBackgroundTertiaryHover: "#111314",
    darkBackgroundWarning: "#dfaf56",
    darkBackgroundWarningDisabled: "#dfaf5699",
    darkBackgroundWarningHover: "#a07302",
    darkBackgroundWarningSubtle: "#9b6a00",
    darkBackgroundWarningSubtleDisabled: "#9b6a0099",
    darkBackgroundWarningSubtleHover: "#704200",
    darkBase1: "#fafafa",
    darkBase2: "#abacac",
    darkBase3: "#6f7070",
    darkBase4: "#444646",
    darkBase5: "#27292a",
    darkBase6: "#161819",
    darkBase7: "#0d0f10",
    darkBase8: "#090c0c",
    darkBase9: "#090b0c",
    darkBlack: "#0c0c0d",
    darkBlue1: "#afd4ff",
    darkBlue2: "#a1caff",
    darkBlue3: "#8ec1ff",
    darkBlue4: "#80b7ff",
    darkBlue5: "#70b0ff",
    darkBlue6: "#61a6ff",
    darkBlue7: "#529cfc",
    darkBlue8: "#4f93ec",
    darkBlue9: "#3c75bf",
    darkBorderAccent: "#36dec0",
    darkBorderAccentDisabled: "#36dec099",
    darkBorderAccentHover: "#009c82",
    darkBorderAccentSubtle: "#003832",
    darkBorderAccentSubtleDisabled: "#00383299",
    darkBorderAccentSubtleHover: "#1b4c46",
    darkBorderDanger: "#f57377",
    darkBorderDangerDisabled: "#f5737799",
    darkBorderDangerHover: "#b73a44",
    darkBorderDangerSubtle: "#b75357",
    darkBorderDangerSubtleDisabled: "#b7535799",
    darkBorderDangerSubtleHover: "#882830",
    darkBorderDiscovery: "#908ffe",
    darkBorderDiscoveryDisabled: "#908ffe99",
    darkBorderDiscoveryHover: "#5f59c2",
    darkBorderDiscoverySubtle: "#6c6bc1",
    darkBorderDiscoverySubtleDisabled: "#6c6bc199",
    darkBorderDiscoverySubtleHover: "#464193",
    darkBorderInfo: "#5ccbeb",
    darkBorderInfoDisabled: "#5ccbeb99",
    darkBorderInfoHover: "#008cab",
    darkBorderInfoSubtle: "#0081a5",
    darkBorderInfoSubtleDisabled: "#0081a599",
    darkBorderInfoSubtleHover: "#00587a",
    darkBorderPrimary: "#27292a",
    darkBorderPrimaryDisabled: "#27292a99",
    darkBorderPrimaryHover: "#383b3c",
    darkBorderSecondary: "#161819",
    darkBorderSecondaryDisabled: "#16181999",
    darkBorderSecondaryHover: "#222425",
    darkBorderSuccess: "#3bb974",
    darkBorderSuccessDisabled: "#3bb97499",
    darkBorderSuccessHover: "#008241",
    darkBorderSuccessSubtle: "#14874e",
    darkBorderSuccessSubtleDisabled: "#14874e99",
    darkBorderSuccessSubtleHover: "#005e28",
    darkBorderTertiary: "#0d0f10",
    darkBorderTertiaryDisabled: "#0d0f1099",
    darkBorderTertiaryHover: "#161819",
    darkBorderWarning: "#dfaf56",
    darkBorderWarningDisabled: "#dfaf5699",
    darkBorderWarningHover: "#a07302",
    darkBorderWarningSubtle: "#9b6a00",
    darkBorderWarningSubtleDisabled: "#9b6a0099",
    darkBorderWarningSubtleHover: "#704200",
    darkBrand1: "#36dec0",
    darkBrand2: "#003832",
    darkDataBaseEmphasis: "#fafafa",
    darkDataBaseSubtle: "#090c0c",
    darkDataBlueEmphasis: "#70b0ff",
    darkDataBlueSubtle: "#3c75bf",
    darkDataBrandEmphasis: "#36dec0",
    darkDataBrandSubtle: "#003832",
    darkDataGreenEmphasis: "#52c180",
    darkDataGreenSubtle: "#14874e",
    darkDataOrangeEmphasis: "#f9935f",
    darkDataOrangeSubtle: "#b45b2b",
    darkDataPinkEmphasis: "#f98cb7",
    darkDataPinkSubtle: "#b4567d",
    darkDataPurpleEmphasis: "#a4a5ff",
    darkDataPurpleSubtle: "#6c6bc1",
    darkDataRedEmphasis: "#ff8d8f",
    darkDataRedSubtle: "#b75357",
    darkDataSkyEmphasis: "#00bee7",
    darkDataSkySubtle: "#0081a5",
    darkDataYellowEmphasis: "#dba330",
    darkDataYellowSubtle: "#9b6a00",
    darkForegroundAccent: "#36dec0",
    darkForegroundAccentDisabled: "#36dec099",
    darkForegroundAccentHover: "#009c82",
    darkForegroundBody: "#abacac",
    darkForegroundBodyDisabled: "#abacac99",
    darkForegroundBodyHover: "#737474",
    darkForegroundDanger: "#f57377",
    darkForegroundDangerDisabled: "#f5737799",
    darkForegroundDangerHover: "#b73a44",
    darkForegroundDiscovery: "#908ffe",
    darkForegroundDiscoveryDisabled: "#908ffe99",
    darkForegroundDiscoveryHover: "#5f59c2",
    darkForegroundInfo: "#5ccbeb",
    darkForegroundInfoDisabled: "#5ccbeb99",
    darkForegroundInfoHover: "#008cab",
    darkForegroundLink: "#529cfc",
    darkForegroundLinkDisabled: "#529cfc99",
    darkForegroundLinkHover: "#1866c1",
    darkForegroundOnAccent: "#fafafa",
    darkForegroundOnAccentDisabled: "#fafafa99",
    darkForegroundOnAccentHover: "#aaaaaa",
    darkForegroundOnDanger: "#fafafa",
    darkForegroundOnDangerDisabled: "#fafafa99",
    darkForegroundOnDangerHover: "#aaaaaa",
    darkForegroundOnDiscovery: "#fafafa",
    darkForegroundOnDiscoveryDisabled: "#fafafa99",
    darkForegroundOnDiscoveryHover: "#aaaaaa",
    darkForegroundOnInfo: "#fafafa",
    darkForegroundOnInfoDisabled: "#fafafa99",
    darkForegroundOnInfoHover: "#aaaaaa",
    darkForegroundOnPrimary: "#090b0c",
    darkForegroundOnPrimaryDisabled: "#090b0c99",
    darkForegroundOnPrimaryHover: "#111314",
    darkForegroundOnSecondary: "#fafafa",
    darkForegroundOnSecondaryDisabled: "#fafafa99",
    darkForegroundOnSecondaryHover: "#aaaaaa",
    darkForegroundOnSuccess: "#fafafa",
    darkForegroundOnSuccessDisabled: "#fafafa99",
    darkForegroundOnSuccessHover: "#aaaaaa",
    darkForegroundOnTertiary: "#fafafa",
    darkForegroundOnTertiaryDisabled: "#fafafa99",
    darkForegroundOnTertiaryHover: "#aaaaaa",
    darkForegroundOnWarning: "#090b0c",
    darkForegroundOnWarningDisabled: "#090b0c99",
    darkForegroundOnWarningHover: "#111314",
    darkForegroundPrimary: "#fafafa",
    darkForegroundPrimaryDisabled: "#fafafa99",
    darkForegroundPrimaryHover: "#aaaaaa",
    darkForegroundSecondary: "#27292a",
    darkForegroundSecondaryDisabled: "#27292a99",
    darkForegroundSecondaryHover: "#383b3c",
    darkForegroundSuccess: "#3bb974",
    darkForegroundSuccessDisabled: "#3bb97499",
    darkForegroundSuccessHover: "#008241",
    darkForegroundTertiary: "#161819",
    darkForegroundTertiaryDisabled: "#16181999",
    darkForegroundTertiaryHover: "#222425",
    darkForegroundWarning: "#dfaf56",
    darkForegroundWarningDisabled: "#dfaf5699",
    darkForegroundWarningHover: "#a07302",
    darkGreen1: "#a4deb7",
    darkGreen2: "#95d6ab",
    darkGreen3: "#7bcc98",
    darkGreen4: "#6dc88f",
    darkGreen5: "#52c180",
    darkGreen6: "#3bb974",
    darkGreen7: "#19b168",
    darkGreen8: "#1ea662",
    darkGreen9: "#14874e",
    darkOrange1: "#ffc5a8",
    darkOrange2: "#fcb998",
    darkOrange3: "#fcab83",
    darkOrange4: "#f69f73",
    darkOrange5: "#f9935f",
    darkOrange6: "#f3874e",
    darkOrange7: "#ec7a3b",
    darkOrange8: "#de743a",
    darkOrange9: "#b45b2b",
    darkOverlayBackdrop: "#0c0c0d66",
    darkOverlayBackground: "#222424",
    darkOverlayBackgroundDisabled: "#22242499",
    darkOverlayBackgroundHover: "#323434",
    darkOverlayBorder: "#27292a",
    darkOverlayBorderDisabled: "#27292a99",
    darkOverlayBorderHover: "#383b3c",
    darkPink1: "#ffbfd6",
    darkPink2: "#fbb2cc",
    darkPink3: "#faa3c3",
    darkPink4: "#f899bd",
    darkPink5: "#f98cb7",
    darkPink6: "#f37fae",
    darkPink7: "#ed72a5",
    darkPink8: "#de6d9b",
    darkPink9: "#b4567d",
    darkPurple1: "#c8cbff",
    darkPurple2: "#bdc1ff",
    darkPurple3: "#b2b5ff",
    darkPurple4: "#abaeff",
    darkPurple5: "#a4a5ff",
    darkPurple6: "#9a9aff",
    darkPurple7: "#908ffe",
    darkPurple8: "#8887ee",
    darkPurple9: "#6c6bc1",
    darkRed1: "#ffc0bf",
    darkRed2: "#ffb3b2",
    darkRed3: "#ffa4a3",
    darkRed4: "#fe9a9a",
    darkRed5: "#ff8d8f",
    darkRed6: "#fb8083",
    darkRed7: "#f57377",
    darkRed8: "#e66d71",
    darkRed9: "#b75357",
    darkSky1: "#91dbf2",
    darkSky2: "#7ed2ed",
    darkSky3: "#5ccbeb",
    darkSky4: "#42c2e6",
    darkSky5: "#00bee7",
    darkSky6: "#00b5e2",
    darkSky7: "#00a9d8",
    darkSky8: "#009fca",
    darkSky9: "#0081a5",
    darkSurface1: "#000101",
    darkSurface2: "#181b1b",
    darkSurface3: "#222424",
    darkSurface4: "#2e3030",
    darkTransparent: "#ffffff00",
    darkWhite: "#ffffff",
    darkYellow1: "#eccc95",
    darkYellow2: "#e5c283",
    darkYellow3: "#e2b667",
    darkYellow4: "#dfaf56",
    darkYellow5: "#dba330",
    darkYellow6: "#d79c05",
    darkYellow7: "#cd8e00",
    darkYellow8: "#c08600",
    darkYellow9: "#9b6a00",
    lightBackgroundAccent: "#1fb2a6",
    lightBackgroundAccentDisabled: "#1fb2a699",
    lightBackgroundAccentHover: "#007c72",
    lightBackgroundAccentSubtle: "#003832",
    lightBackgroundAccentSubtleDisabled: "#00383299",
    lightBackgroundAccentSubtleHover: "#1b4c46",
    lightBackgroundDanger: "#d86164",
    lightBackgroundDangerDisabled: "#d8616499",
    lightBackgroundDangerHover: "#a12e37",
    lightBackgroundDangerSubtle: "#a94e50",
    lightBackgroundDangerSubtleDisabled: "#a94e5099",
    lightBackgroundDangerSubtleHover: "#7d262c",
    lightBackgroundDiscovery: "#7f7ee4",
    lightBackgroundDiscoveryDisabled: "#7f7ee499",
    lightBackgroundDiscoveryHover: "#534dae",
    lightBackgroundDiscoverySubtle: "#6261af",
    lightBackgroundDiscoverySubtleDisabled: "#6261af99",
    lightBackgroundDiscoverySubtleHover: "#3f3b85",
    lightBackgroundElevated: "#f4f4f3",
    lightBackgroundElevatedDisabled: "#f4f4f399",
    lightBackgroundElevatedHover: "#a6a6a5",
    lightBackgroundFloating: "#e8e7e6",
    lightBackgroundFloatingDisabled: "#e8e7e699",
    lightBackgroundFloatingHover: "#9e9d9c",
    lightBackgroundHighest: "#c3c4c4",
    lightBackgroundHighestDisabled: "#c3c4c499",
    lightBackgroundHighestHover: "#848585",
    lightBackgroundInfo: "#00b8e6",
    lightBackgroundInfoDisabled: "#00b8e699",
    lightBackgroundInfoHover: "#007fab",
    lightBackgroundInfoSubtle: "#007496",
    lightBackgroundInfoSubtleDisabled: "#00749699",
    lightBackgroundInfoSubtleHover: "#004e6f",
    lightBackgroundLink: "#468ae2",
    lightBackgroundLinkDisabled: "#468ae299",
    lightBackgroundLinkHover: "#115aad",
    lightBackgroundPage: "#ffffff",
    lightBackgroundPageDisabled: "#ffffff99",
    lightBackgroundPageHover: "#aeaeae",
    lightBackgroundPrimary: "#f4f4f4",
    lightBackgroundPrimaryDisabled: "#f4f4f499",
    lightBackgroundPrimaryHover: "#a6a6a6",
    lightBackgroundSecondary: "#1c1c1c",
    lightBackgroundSecondaryDisabled: "#1c1c1c99",
    lightBackgroundSecondaryHover: "#2a2a2a",
    lightBackgroundSuccess: "#00a469",
    lightBackgroundSuccessDisabled: "#00a46999",
    lightBackgroundSuccessHover: "#00733c",
    lightBackgroundSuccessSubtle: "#007a4d",
    lightBackgroundSuccessSubtleDisabled: "#007a4d99",
    lightBackgroundSuccessSubtleHover: "#00552b",
    lightBackgroundTertiary: "#181818",
    lightBackgroundTertiaryDisabled: "#18181899",
    lightBackgroundTertiaryHover: "#242424",
    lightBackgroundWarning: "#d49400",
    lightBackgroundWarningDisabled: "#d4940099",
    lightBackgroundWarningHover: "#9a5e00",
    lightBackgroundWarningSubtle: "#8f6300",
    lightBackgroundWarningSubtleDisabled: "#8f630099",
    lightBackgroundWarningSubtleHover: "#673d00",
    lightBase1: "#f4f4f4",
    lightBase2: "#c1c1c1",
    lightBase3: "#949494",
    lightBase4: "#6e6e6e",
    lightBase5: "#4f4f4f",
    lightBase6: "#373737",
    lightBase7: "#262626",
    lightBase8: "#1c1c1c",
    lightBase9: "#181818",
    lightBlack: "#0c0c0d",
    lightBlue1: "#83baff",
    lightBlue2: "#7bb7ff",
    lightBlue3: "#68acff",
    lightBlue4: "#59a2ff",
    lightBlue5: "#4f99f9",
    lightBlue6: "#4c90e8",
    lightBlue7: "#468ae2",
    lightBlue8: "#3f7ecf",
    lightBlue9: "#3669ac",
    lightBorderAccent: "#1fb2a6",
    lightBorderAccentDisabled: "#1fb2a699",
    lightBorderAccentHover: "#007c72",
    lightBorderAccentSubtle: "#003832",
    lightBorderAccentSubtleDisabled: "#00383299",
    lightBorderAccentSubtleHover: "#1b4c46",
    lightBorderDanger: "#d86164",
    lightBorderDangerDisabled: "#d8616499",
    lightBorderDangerHover: "#a12e37",
    lightBorderDangerSubtle: "#a94e50",
    lightBorderDangerSubtleDisabled: "#a94e5099",
    lightBorderDangerSubtleHover: "#7d262c",
    lightBorderDiscovery: "#7f7ee4",
    lightBorderDiscoveryDisabled: "#7f7ee499",
    lightBorderDiscoveryHover: "#534dae",
    lightBorderDiscoverySubtle: "#6261af",
    lightBorderDiscoverySubtleDisabled: "#6261af99",
    lightBorderDiscoverySubtleHover: "#3f3b85",
    lightBorderInfo: "#00b8e6",
    lightBorderInfoDisabled: "#00b8e699",
    lightBorderInfoHover: "#007fab",
    lightBorderInfoSubtle: "#007496",
    lightBorderInfoSubtleDisabled: "#00749699",
    lightBorderInfoSubtleHover: "#004e6f",
    lightBorderPrimary: "#262626",
    lightBorderPrimaryDisabled: "#26262699",
    lightBorderPrimaryHover: "#373737",
    lightBorderSecondary: "#1c1c1c",
    lightBorderSecondaryDisabled: "#1c1c1c99",
    lightBorderSecondaryHover: "#2a2a2a",
    lightBorderSuccess: "#00a469",
    lightBorderSuccessDisabled: "#00a46999",
    lightBorderSuccessHover: "#00733c",
    lightBorderSuccessSubtle: "#007a4d",
    lightBorderSuccessSubtleDisabled: "#007a4d99",
    lightBorderSuccessSubtleHover: "#00552b",
    lightBorderTertiary: "#181818",
    lightBorderTertiaryDisabled: "#18181899",
    lightBorderTertiaryHover: "#242424",
    lightBorderWarning: "#d49400",
    lightBorderWarningDisabled: "#d4940099",
    lightBorderWarningHover: "#9a5e00",
    lightBorderWarningSubtle: "#8f6300",
    lightBorderWarningSubtleDisabled: "#8f630099",
    lightBorderWarningSubtleHover: "#673d00",
    lightBrand1: "#1fb2a6",
    lightBrand2: "#003832",
    lightDataBaseEmphasis: "#4f4f4f",
    lightDataBaseSubtle: "#f4f4f4",
    lightDataBlueEmphasis: "#4c90e8",
    lightDataBlueSubtle: "#83baff",
    lightDataBrandEmphasis: "#1fb2a6",
    lightDataBrandSubtle: "#003832",
    lightDataGreenEmphasis: "#00a469",
    lightDataGreenSubtle: "#67cc9a",
    lightDataOrangeEmphasis: "#de743a",
    lightDataOrangeSubtle: "#faa276",
    lightDataPinkEmphasis: "#db6a98",
    lightDataPinkSubtle: "#fb9cc0",
    lightDataPurpleEmphasis: "#8584eb",
    lightDataPurpleSubtle: "#aeb1ff",
    lightDataRedEmphasis: "#e26a6c",
    lightDataRedSubtle: "#ff9e9c",
    lightDataSkyEmphasis: "#009ecb",
    lightDataSkySubtle: "#47c5ea",
    lightDataYellowEmphasis: "#c08600",
    lightDataYellowSubtle: "#e2b259",
    lightForegroundAccent: "#1fb2a6",
    lightForegroundAccentDisabled: "#1fb2a699",
    lightForegroundAccentHover: "#007c72",
    lightForegroundBody: "#6e6e6e",
    lightForegroundBodyDisabled: "#6e6e6e99",
    lightForegroundBodyHover: "#494949",
    lightForegroundDanger: "#d86164",
    lightForegroundDangerDisabled: "#d8616499",
    lightForegroundDangerHover: "#a12e37",
    lightForegroundDiscovery: "#7f7ee4",
    lightForegroundDiscoveryDisabled: "#7f7ee499",
    lightForegroundDiscoveryHover: "#534dae",
    lightForegroundInfo: "#00b8e6",
    lightForegroundInfoDisabled: "#00b8e699",
    lightForegroundInfoHover: "#007fab",
    lightForegroundLink: "#468ae2",
    lightForegroundLinkDisabled: "#468ae299",
    lightForegroundLinkHover: "#115aad",
    lightForegroundOnAccent: "#f4f4f4",
    lightForegroundOnAccentDisabled: "#f4f4f499",
    lightForegroundOnAccentHover: "#a6a6a6",
    lightForegroundOnDanger: "#f4f4f4",
    lightForegroundOnDangerDisabled: "#f4f4f499",
    lightForegroundOnDangerHover: "#a6a6a6",
    lightForegroundOnDiscovery: "#f4f4f4",
    lightForegroundOnDiscoveryDisabled: "#f4f4f499",
    lightForegroundOnDiscoveryHover: "#a6a6a6",
    lightForegroundOnInfo: "#f4f4f4",
    lightForegroundOnInfoDisabled: "#f4f4f499",
    lightForegroundOnInfoHover: "#a6a6a6",
    lightForegroundOnPrimary: "#181818",
    lightForegroundOnPrimaryDisabled: "#18181899",
    lightForegroundOnPrimaryHover: "#242424",
    lightForegroundOnSecondary: "#f4f4f4",
    lightForegroundOnSecondaryDisabled: "#f4f4f499",
    lightForegroundOnSecondaryHover: "#a6a6a6",
    lightForegroundOnSuccess: "#f4f4f4",
    lightForegroundOnSuccessDisabled: "#f4f4f499",
    lightForegroundOnSuccessHover: "#a6a6a6",
    lightForegroundOnTertiary: "#f4f4f4",
    lightForegroundOnTertiaryDisabled: "#f4f4f499",
    lightForegroundOnTertiaryHover: "#a6a6a6",
    lightForegroundOnWarning: "#181818",
    lightForegroundOnWarningDisabled: "#18181899",
    lightForegroundOnWarningHover: "#242424",
    lightForegroundPrimary: "#f4f4f4",
    lightForegroundPrimaryDisabled: "#f4f4f499",
    lightForegroundPrimaryHover: "#a6a6a6",
    lightForegroundSecondary: "#1c1c1c",
    lightForegroundSecondaryDisabled: "#1c1c1c99",
    lightForegroundSecondaryHover: "#2a2a2a",
    lightForegroundSuccess: "#00a469",
    lightForegroundSuccessDisabled: "#00a46999",
    lightForegroundSuccessHover: "#00733c",
    lightForegroundTertiary: "#181818",
    lightForegroundTertiaryDisabled: "#18181899",
    lightForegroundTertiaryHover: "#242424",
    lightForegroundWarning: "#d49400",
    lightForegroundWarningDisabled: "#d4940099",
    lightForegroundWarningHover: "#9a5e00",
    lightGreen1: "#67cc9a",
    lightGreen2: "#57c791",
    lightGreen3: "#2fc183",
    lightGreen4: "#00b575",
    lightGreen5: "#00af6f",
    lightGreen6: "#00a469",
    lightGreen7: "#009d63",
    lightGreen8: "#008f5a",
    lightGreen9: "#007a4d",
    lightOrange1: "#faa276",
    lightOrange2: "#fb9c6c",
    lightOrange3: "#fa8d54",
    lightOrange4: "#f38042",
    lightOrange5: "#e97737",
    lightOrange6: "#de743a",
    lightOrange7: "#d36b2f",
    lightOrange8: "#c2612b",
    lightOrange9: "#a25226",
    lightOverlayBackdrop: "#1a1c1f66",
    lightOverlayBackground: "#e8e7e6",
    lightOverlayBackgroundDisabled: "#e8e7e699",
    lightOverlayBackgroundHover: "#9e9d9c",
    lightOverlayBorder: "#262626",
    lightOverlayBorderDisabled: "#26262699",
    lightOverlayBorderHover: "#373737",
    lightPink1: "#fb9cc0",
    lightPink2: "#f993ba",
    lightPink3: "#f782b1",
    lightPink4: "#f075a8",
    lightPink5: "#e96fa2",
    lightPink6: "#db6a98",
    lightPink7: "#d1608f",
    lightPink8: "#c25b86",
    lightPink9: "#a34e71",
    lightPurple1: "#aeb1ff",
    lightPurple2: "#a7a9ff",
    lightPurple3: "#a0a0ff",
    lightPurple4: "#9695ff",
    lightPurple5: "#8d8cfb",
    lightPurple6: "#8584eb",
    lightPurple7: "#7f7ee4",
    lightPurple8: "#7473d1",
    lightPurple9: "#6261af",
    lightRed1: "#ff9e9c",
    lightRed2: "#ff9493",
    lightRed3: "#ff8484",
    lightRed4: "#f97678",
    lightRed5: "#f17072",
    lightRed6: "#e26a6c",
    lightRed7: "#d86164",
    lightRed8: "#c95c5e",
    lightRed9: "#a94e50",
    lightSky1: "#47c5ea",
    lightSky2: "#2ec3eb",
    lightSky3: "#00b8e6",
    lightSky4: "#00afe0",
    lightSky5: "#00a6d6",
    lightSky6: "#009ecb",
    lightSky7: "#0095c2",
    lightSky8: "#008bb4",
    lightSky9: "#007496",
    lightSurface1: "#ffffff",
    lightSurface2: "#f4f4f3",
    lightSurface3: "#e8e7e6",
    lightSurface4: "#c3c4c4",
    lightTransparent: "#ffffff00",
    lightWhite: "#ffffff",
    lightYellow1: "#e2b259",
    lightYellow2: "#deab47",
    lightYellow3: "#db9f10",
    lightYellow4: "#d49400",
    lightYellow5: "#ca8b00",
    lightYellow6: "#c08600",
    lightYellow7: "#b77d00",
    lightYellow8: "#a77200",
    lightYellow9: "#8f6300"
  },
  space: {
    "2xl": 10,
    "3xl": 13,
    "4xl": 16,
    "5xl": 18,
    "6xl": 21,
    "7xl": 24,
    "8xl": 32,
    "9xl": 39,
    "10xl": 46,
    "11xl": 53,
    "12xl": 60,
    "13xl": 74,
    "14xl": 88,
    "15xl": 102,
    "16xl": 116,
    "17xl": 130,
    "18xl": 144,
    "19xl": 144,
    "20xl": 158,
    "21xl": 172,
    "22xl": 186,
    lg: 4,
    md: 2,
    none: 0,
    sm: 1.5,
    xl: 7,
    xs: 1,
    xxs: 0.5
  },
  size: {
    "2xl": 32,
    "3xl": 36,
    "4xl": 40,
    "5xl": 44,
    "6xl": 48,
    "7xl": 52,
    "8xl": 64,
    "9xl": 74,
    "10xl": 84,
    "11xl": 94,
    "12xl": 104,
    "13xl": 124,
    "14xl": 144,
    "15xl": 164,
    "16xl": 184,
    "17xl": 204,
    "18xl": 224,
    "19xl": 224,
    "20xl": 244,
    "21xl": 264,
    "22xl": 284,
    lg: 24,
    md: 20,
    none: 0,
    sm: 8,
    xl: 28,
    xs: 4,
    xxs: 2
  },
  radius: {
    "2xl": 16,
    "3xl": 24,
    "4xl": 32,
    card: 6,
    container: 6,
    control: 2,
    dialog: 2,
    full: "100%",
    lg: 8,
    md: 6,
    none: 0,
    popover: 2,
    sm: 4,
    tooltip: 2,
    trigger: 4,
    xl: 12,
    xs: 2
  },
  zIndex: {
    "0": 0,
    "10": 100,
    "20": 200,
    "30": 300,
    "40": 400,
    "50": 500,
    "60": 600,
    "70": 700,
    "80": 800,
    "90": 900
  },
  blur: {
    "2xl": px(40),
    "3xl": px(64),
    lg: px(16),
    md: px(12),
    sm: px(8),
    xl: px(24),
    xs: px(4)
  },
  fontSize: {
    "2xl": px(24),
    "3xl": px(30),
    "4xl": px(36),
    "5xl": px(48),
    "6xl": px(60),
    "7xl": px(72),
    "8xl": px(96),
    "9xl": px(128),
    lg: px(18),
    md: px(16),
    sm: px(14),
    xl: px(20),
    xs: px(12)
  },
  shadow: {
    "2xl": "0px 25px 50px -12px #00000040",
    "2xs": "0px 1px 0px 0px #0000000d",
    lg: "0px 10px 15px -3px #0000001a, 0px 4px 6px -4px #0000001a",
    md: "0px 4px 6px -1px #0000001a, 0px 2px 4px -2px #0000001a",
    sm: "0px 1px 3px 0px #0000001a, 0px 1px 2px -1px #0000001a",
    xl: "0px 20px 25px -5px #0000001a, 0px 8px 10px -6px #0000001a",
    xs: "0px 1px 2px 0px #0000000d"
  },
  insetShadow: {
    "2xs": "inset 0px 1px 0px 0px #0000000d",
    sm: "inset 0px 2px 4px 0px #0000000d",
    xs: "inset 0px 1px 1px 0px #0000000d"
  },
  dropShadow: {
    "2xl": "drop-shadow(0px 25px 25px #00000026)",
    lg: "drop-shadow(0px 4px 4px #00000026)",
    md: "drop-shadow(0px 3px 3px #0000001f)",
    sm: "drop-shadow(0px 1px 2px #00000026)",
    xl: "drop-shadow(0px 9px 7px #0000001a)",
    xs: "drop-shadow(0px 1px 1px #0000000d)"
  },
  textShadow: {
    "2xs": "0px 1px 0px 0px #00000026",
    lg: "0px 1px 2px 0px #0000001a, 0px 3px 2px 0px #0000001a, 0px 4px 8px 0px #0000001a",
    md: "0px 1px 1px 0px #0000001a, 0px 1px 2px 0px #0000001a, 0px 2px 4px 0px #0000001a",
    sm: "0px 1px 0px 0px #00000013, 0px 1px 1px 0px #00000013, 0px 2px 2px 0px #00000013",
    xs: "0px 1px 1px 0px #00000033"
  },
  fontWeight: {
    black: 900,
    bold: 700,
    extrabold: 800,
    extralight: 200,
    light: 300,
    medium: 500,
    normal: 400,
    semibold: 600,
    thin: 100
  }
});

const SEMANTIC_ROLES = new Set(["accent", "danger", "discovery", "info", "success", "warning"]);

const themes = createV5Theme({
  lightPalette: [tokens.color.lightBase1.val,tokens.color.lightBase2.val,tokens.color.lightBase3.val,tokens.color.lightBase4.val,tokens.color.lightBase5.val,tokens.color.lightBase6.val,tokens.color.lightBase7.val,tokens.color.lightBase8.val,tokens.color.lightBase9.val,tokens.color.lightBase9.val,tokens.color.lightBase9.val,tokens.color.lightBase9.val],
  darkPalette: [tokens.color.darkBase9.val,tokens.color.darkBase8.val,tokens.color.darkBase7.val,tokens.color.darkBase6.val,tokens.color.darkBase5.val,tokens.color.darkBase4.val,tokens.color.darkBase3.val,tokens.color.darkBase2.val,tokens.color.darkBase1.val,tokens.color.darkBase1.val,tokens.color.darkBase1.val,tokens.color.darkBase1.val],
  childrenThemes: {
    accent: {
      light: {
        accent1: tokens.color.lightForegroundAccent.val,
        accent2: tokens.color.lightForegroundOnAccent.val,
        accent3: tokens.color.lightForegroundAccentHover.val,
        accent4: tokens.color.lightForegroundAccentDisabled.val,
        accent5: tokens.color.lightForegroundOnAccentHover.val,
        accent6: tokens.color.lightForegroundOnAccentDisabled.val,
        accent7: tokens.color.lightBackgroundAccent.val,
        accent8: tokens.color.lightBackgroundAccentSubtle.val,
        accent9: tokens.color.lightBackgroundAccentHover.val,
        accent10: tokens.color.lightBackgroundAccentDisabled.val,
        accent11: tokens.color.lightBackgroundAccentSubtleHover.val,
        accent12: tokens.color.lightBackgroundAccentSubtleDisabled.val,
        accent13: tokens.color.lightBorderAccent.val,
        accent14: tokens.color.lightBorderAccentSubtle.val,
        accent15: tokens.color.lightBorderAccentHover.val,
        accent16: tokens.color.lightBorderAccentDisabled.val,
        accent17: tokens.color.lightBorderAccentSubtleHover.val,
        accent18: tokens.color.lightBorderAccentSubtleDisabled.val
      },
      dark: {
        accent1: tokens.color.darkForegroundAccent.val,
        accent2: tokens.color.darkForegroundOnAccent.val,
        accent3: tokens.color.darkForegroundAccentHover.val,
        accent4: tokens.color.darkForegroundAccentDisabled.val,
        accent5: tokens.color.darkForegroundOnAccentHover.val,
        accent6: tokens.color.darkForegroundOnAccentDisabled.val,
        accent7: tokens.color.darkBackgroundAccent.val,
        accent8: tokens.color.darkBackgroundAccentSubtle.val,
        accent9: tokens.color.darkBackgroundAccentHover.val,
        accent10: tokens.color.darkBackgroundAccentDisabled.val,
        accent11: tokens.color.darkBackgroundAccentSubtleHover.val,
        accent12: tokens.color.darkBackgroundAccentSubtleDisabled.val,
        accent13: tokens.color.darkBorderAccent.val,
        accent14: tokens.color.darkBorderAccentSubtle.val,
        accent15: tokens.color.darkBorderAccentHover.val,
        accent16: tokens.color.darkBorderAccentDisabled.val,
        accent17: tokens.color.darkBorderAccentSubtleHover.val,
        accent18: tokens.color.darkBorderAccentSubtleDisabled.val
      }
    },
    base: {
      light: {
        base1: tokens.color.lightBase1.val,
        base2: tokens.color.lightBase2.val,
        base3: tokens.color.lightBase3.val,
        base4: tokens.color.lightBase4.val,
        base5: tokens.color.lightBase5.val,
        base6: tokens.color.lightBase6.val,
        base7: tokens.color.lightBase7.val,
        base8: tokens.color.lightBase8.val,
        base9: tokens.color.lightBase9.val
      },
      dark: {
        base1: tokens.color.darkBase9.val,
        base2: tokens.color.darkBase8.val,
        base3: tokens.color.darkBase7.val,
        base4: tokens.color.darkBase6.val,
        base5: tokens.color.darkBase5.val,
        base6: tokens.color.darkBase4.val,
        base7: tokens.color.darkBase3.val,
        base8: tokens.color.darkBase2.val,
        base9: tokens.color.darkBase1.val
      }
    },
    blue: {
      light: {
        blue1: tokens.color.lightBlue1.val,
        blue2: tokens.color.lightBlue2.val,
        blue3: tokens.color.lightBlue3.val,
        blue4: tokens.color.lightBlue4.val,
        blue5: tokens.color.lightBlue5.val,
        blue6: tokens.color.lightBlue6.val,
        blue7: tokens.color.lightBlue7.val,
        blue8: tokens.color.lightBlue8.val,
        blue9: tokens.color.lightBlue9.val
      },
      dark: {
        blue1: tokens.color.darkBlue9.val,
        blue2: tokens.color.darkBlue8.val,
        blue3: tokens.color.darkBlue7.val,
        blue4: tokens.color.darkBlue6.val,
        blue5: tokens.color.darkBlue5.val,
        blue6: tokens.color.darkBlue4.val,
        blue7: tokens.color.darkBlue3.val,
        blue8: tokens.color.darkBlue2.val,
        blue9: tokens.color.darkBlue1.val
      }
    },
    danger: {
      light: {
        danger1: tokens.color.lightForegroundDanger.val,
        danger2: tokens.color.lightForegroundOnDanger.val,
        danger3: tokens.color.lightForegroundDangerHover.val,
        danger4: tokens.color.lightForegroundDangerDisabled.val,
        danger5: tokens.color.lightForegroundOnDangerHover.val,
        danger6: tokens.color.lightForegroundOnDangerDisabled.val,
        danger7: tokens.color.lightBackgroundDanger.val,
        danger8: tokens.color.lightBackgroundDangerSubtle.val,
        danger9: tokens.color.lightBackgroundDangerHover.val,
        danger10: tokens.color.lightBackgroundDangerDisabled.val,
        danger11: tokens.color.lightBackgroundDangerSubtleHover.val,
        danger12: tokens.color.lightBackgroundDangerSubtleDisabled.val,
        danger13: tokens.color.lightBorderDanger.val,
        danger14: tokens.color.lightBorderDangerSubtle.val,
        danger15: tokens.color.lightBorderDangerHover.val,
        danger16: tokens.color.lightBorderDangerDisabled.val,
        danger17: tokens.color.lightBorderDangerSubtleHover.val,
        danger18: tokens.color.lightBorderDangerSubtleDisabled.val
      },
      dark: {
        danger1: tokens.color.darkForegroundDanger.val,
        danger2: tokens.color.darkForegroundOnDanger.val,
        danger3: tokens.color.darkForegroundDangerHover.val,
        danger4: tokens.color.darkForegroundDangerDisabled.val,
        danger5: tokens.color.darkForegroundOnDangerHover.val,
        danger6: tokens.color.darkForegroundOnDangerDisabled.val,
        danger7: tokens.color.darkBackgroundDanger.val,
        danger8: tokens.color.darkBackgroundDangerSubtle.val,
        danger9: tokens.color.darkBackgroundDangerHover.val,
        danger10: tokens.color.darkBackgroundDangerDisabled.val,
        danger11: tokens.color.darkBackgroundDangerSubtleHover.val,
        danger12: tokens.color.darkBackgroundDangerSubtleDisabled.val,
        danger13: tokens.color.darkBorderDanger.val,
        danger14: tokens.color.darkBorderDangerSubtle.val,
        danger15: tokens.color.darkBorderDangerHover.val,
        danger16: tokens.color.darkBorderDangerDisabled.val,
        danger17: tokens.color.darkBorderDangerSubtleHover.val,
        danger18: tokens.color.darkBorderDangerSubtleDisabled.val
      }
    },
    discovery: {
      light: {
        discovery1: tokens.color.lightForegroundDiscovery.val,
        discovery2: tokens.color.lightForegroundOnDiscovery.val,
        discovery3: tokens.color.lightForegroundDiscoveryHover.val,
        discovery4: tokens.color.lightForegroundDiscoveryDisabled.val,
        discovery5: tokens.color.lightForegroundOnDiscoveryHover.val,
        discovery6: tokens.color.lightForegroundOnDiscoveryDisabled.val,
        discovery7: tokens.color.lightBackgroundDiscovery.val,
        discovery8: tokens.color.lightBackgroundDiscoverySubtle.val,
        discovery9: tokens.color.lightBackgroundDiscoveryHover.val,
        discovery10: tokens.color.lightBackgroundDiscoveryDisabled.val,
        discovery11: tokens.color.lightBackgroundDiscoverySubtleHover.val,
        discovery12: tokens.color.lightBackgroundDiscoverySubtleDisabled.val,
        discovery13: tokens.color.lightBorderDiscovery.val,
        discovery14: tokens.color.lightBorderDiscoverySubtle.val,
        discovery15: tokens.color.lightBorderDiscoveryHover.val,
        discovery16: tokens.color.lightBorderDiscoveryDisabled.val,
        discovery17: tokens.color.lightBorderDiscoverySubtleHover.val,
        discovery18: tokens.color.lightBorderDiscoverySubtleDisabled.val
      },
      dark: {
        discovery1: tokens.color.darkForegroundDiscovery.val,
        discovery2: tokens.color.darkForegroundOnDiscovery.val,
        discovery3: tokens.color.darkForegroundDiscoveryHover.val,
        discovery4: tokens.color.darkForegroundDiscoveryDisabled.val,
        discovery5: tokens.color.darkForegroundOnDiscoveryHover.val,
        discovery6: tokens.color.darkForegroundOnDiscoveryDisabled.val,
        discovery7: tokens.color.darkBackgroundDiscovery.val,
        discovery8: tokens.color.darkBackgroundDiscoverySubtle.val,
        discovery9: tokens.color.darkBackgroundDiscoveryHover.val,
        discovery10: tokens.color.darkBackgroundDiscoveryDisabled.val,
        discovery11: tokens.color.darkBackgroundDiscoverySubtleHover.val,
        discovery12: tokens.color.darkBackgroundDiscoverySubtleDisabled.val,
        discovery13: tokens.color.darkBorderDiscovery.val,
        discovery14: tokens.color.darkBorderDiscoverySubtle.val,
        discovery15: tokens.color.darkBorderDiscoveryHover.val,
        discovery16: tokens.color.darkBorderDiscoveryDisabled.val,
        discovery17: tokens.color.darkBorderDiscoverySubtleHover.val,
        discovery18: tokens.color.darkBorderDiscoverySubtleDisabled.val
      }
    },
    green: {
      light: {
        green1: tokens.color.lightGreen1.val,
        green2: tokens.color.lightGreen2.val,
        green3: tokens.color.lightGreen3.val,
        green4: tokens.color.lightGreen4.val,
        green5: tokens.color.lightGreen5.val,
        green6: tokens.color.lightGreen6.val,
        green7: tokens.color.lightGreen7.val,
        green8: tokens.color.lightGreen8.val,
        green9: tokens.color.lightGreen9.val
      },
      dark: {
        green1: tokens.color.darkGreen9.val,
        green2: tokens.color.darkGreen8.val,
        green3: tokens.color.darkGreen7.val,
        green4: tokens.color.darkGreen6.val,
        green5: tokens.color.darkGreen5.val,
        green6: tokens.color.darkGreen4.val,
        green7: tokens.color.darkGreen3.val,
        green8: tokens.color.darkGreen2.val,
        green9: tokens.color.darkGreen1.val
      }
    },
    info: {
      light: {
        info1: tokens.color.lightForegroundInfo.val,
        info2: tokens.color.lightForegroundOnInfo.val,
        info3: tokens.color.lightForegroundInfoHover.val,
        info4: tokens.color.lightForegroundInfoDisabled.val,
        info5: tokens.color.lightForegroundOnInfoHover.val,
        info6: tokens.color.lightForegroundOnInfoDisabled.val,
        info7: tokens.color.lightBackgroundInfo.val,
        info8: tokens.color.lightBackgroundInfoSubtle.val,
        info9: tokens.color.lightBackgroundInfoHover.val,
        info10: tokens.color.lightBackgroundInfoDisabled.val,
        info11: tokens.color.lightBackgroundInfoSubtleHover.val,
        info12: tokens.color.lightBackgroundInfoSubtleDisabled.val,
        info13: tokens.color.lightBorderInfo.val,
        info14: tokens.color.lightBorderInfoSubtle.val,
        info15: tokens.color.lightBorderInfoHover.val,
        info16: tokens.color.lightBorderInfoDisabled.val,
        info17: tokens.color.lightBorderInfoSubtleHover.val,
        info18: tokens.color.lightBorderInfoSubtleDisabled.val
      },
      dark: {
        info1: tokens.color.darkForegroundInfo.val,
        info2: tokens.color.darkForegroundOnInfo.val,
        info3: tokens.color.darkForegroundInfoHover.val,
        info4: tokens.color.darkForegroundInfoDisabled.val,
        info5: tokens.color.darkForegroundOnInfoHover.val,
        info6: tokens.color.darkForegroundOnInfoDisabled.val,
        info7: tokens.color.darkBackgroundInfo.val,
        info8: tokens.color.darkBackgroundInfoSubtle.val,
        info9: tokens.color.darkBackgroundInfoHover.val,
        info10: tokens.color.darkBackgroundInfoDisabled.val,
        info11: tokens.color.darkBackgroundInfoSubtleHover.val,
        info12: tokens.color.darkBackgroundInfoSubtleDisabled.val,
        info13: tokens.color.darkBorderInfo.val,
        info14: tokens.color.darkBorderInfoSubtle.val,
        info15: tokens.color.darkBorderInfoHover.val,
        info16: tokens.color.darkBorderInfoDisabled.val,
        info17: tokens.color.darkBorderInfoSubtleHover.val,
        info18: tokens.color.darkBorderInfoSubtleDisabled.val
      }
    },
    orange: {
      light: {
        orange1: tokens.color.lightOrange1.val,
        orange2: tokens.color.lightOrange2.val,
        orange3: tokens.color.lightOrange3.val,
        orange4: tokens.color.lightOrange4.val,
        orange5: tokens.color.lightOrange5.val,
        orange6: tokens.color.lightOrange6.val,
        orange7: tokens.color.lightOrange7.val,
        orange8: tokens.color.lightOrange8.val,
        orange9: tokens.color.lightOrange9.val
      },
      dark: {
        orange1: tokens.color.darkOrange9.val,
        orange2: tokens.color.darkOrange8.val,
        orange3: tokens.color.darkOrange7.val,
        orange4: tokens.color.darkOrange6.val,
        orange5: tokens.color.darkOrange5.val,
        orange6: tokens.color.darkOrange4.val,
        orange7: tokens.color.darkOrange3.val,
        orange8: tokens.color.darkOrange2.val,
        orange9: tokens.color.darkOrange1.val
      }
    },
    pink: {
      light: {
        pink1: tokens.color.lightPink1.val,
        pink2: tokens.color.lightPink2.val,
        pink3: tokens.color.lightPink3.val,
        pink4: tokens.color.lightPink4.val,
        pink5: tokens.color.lightPink5.val,
        pink6: tokens.color.lightPink6.val,
        pink7: tokens.color.lightPink7.val,
        pink8: tokens.color.lightPink8.val,
        pink9: tokens.color.lightPink9.val
      },
      dark: {
        pink1: tokens.color.darkPink9.val,
        pink2: tokens.color.darkPink8.val,
        pink3: tokens.color.darkPink7.val,
        pink4: tokens.color.darkPink6.val,
        pink5: tokens.color.darkPink5.val,
        pink6: tokens.color.darkPink4.val,
        pink7: tokens.color.darkPink3.val,
        pink8: tokens.color.darkPink2.val,
        pink9: tokens.color.darkPink1.val
      }
    },
    purple: {
      light: {
        purple1: tokens.color.lightPurple1.val,
        purple2: tokens.color.lightPurple2.val,
        purple3: tokens.color.lightPurple3.val,
        purple4: tokens.color.lightPurple4.val,
        purple5: tokens.color.lightPurple5.val,
        purple6: tokens.color.lightPurple6.val,
        purple7: tokens.color.lightPurple7.val,
        purple8: tokens.color.lightPurple8.val,
        purple9: tokens.color.lightPurple9.val
      },
      dark: {
        purple1: tokens.color.darkPurple9.val,
        purple2: tokens.color.darkPurple8.val,
        purple3: tokens.color.darkPurple7.val,
        purple4: tokens.color.darkPurple6.val,
        purple5: tokens.color.darkPurple5.val,
        purple6: tokens.color.darkPurple4.val,
        purple7: tokens.color.darkPurple3.val,
        purple8: tokens.color.darkPurple2.val,
        purple9: tokens.color.darkPurple1.val
      }
    },
    red: {
      light: {
        red1: tokens.color.lightRed1.val,
        red2: tokens.color.lightRed2.val,
        red3: tokens.color.lightRed3.val,
        red4: tokens.color.lightRed4.val,
        red5: tokens.color.lightRed5.val,
        red6: tokens.color.lightRed6.val,
        red7: tokens.color.lightRed7.val,
        red8: tokens.color.lightRed8.val,
        red9: tokens.color.lightRed9.val
      },
      dark: {
        red1: tokens.color.darkRed9.val,
        red2: tokens.color.darkRed8.val,
        red3: tokens.color.darkRed7.val,
        red4: tokens.color.darkRed6.val,
        red5: tokens.color.darkRed5.val,
        red6: tokens.color.darkRed4.val,
        red7: tokens.color.darkRed3.val,
        red8: tokens.color.darkRed2.val,
        red9: tokens.color.darkRed1.val
      }
    },
    sky: {
      light: {
        sky1: tokens.color.lightSky1.val,
        sky2: tokens.color.lightSky2.val,
        sky3: tokens.color.lightSky3.val,
        sky4: tokens.color.lightSky4.val,
        sky5: tokens.color.lightSky5.val,
        sky6: tokens.color.lightSky6.val,
        sky7: tokens.color.lightSky7.val,
        sky8: tokens.color.lightSky8.val,
        sky9: tokens.color.lightSky9.val
      },
      dark: {
        sky1: tokens.color.darkSky9.val,
        sky2: tokens.color.darkSky8.val,
        sky3: tokens.color.darkSky7.val,
        sky4: tokens.color.darkSky6.val,
        sky5: tokens.color.darkSky5.val,
        sky6: tokens.color.darkSky4.val,
        sky7: tokens.color.darkSky3.val,
        sky8: tokens.color.darkSky2.val,
        sky9: tokens.color.darkSky1.val
      }
    },
    success: {
      light: {
        success1: tokens.color.lightForegroundSuccess.val,
        success2: tokens.color.lightForegroundOnSuccess.val,
        success3: tokens.color.lightForegroundSuccessHover.val,
        success4: tokens.color.lightForegroundSuccessDisabled.val,
        success5: tokens.color.lightForegroundOnSuccessHover.val,
        success6: tokens.color.lightForegroundOnSuccessDisabled.val,
        success7: tokens.color.lightBackgroundSuccess.val,
        success8: tokens.color.lightBackgroundSuccessSubtle.val,
        success9: tokens.color.lightBackgroundSuccessHover.val,
        success10: tokens.color.lightBackgroundSuccessDisabled.val,
        success11: tokens.color.lightBackgroundSuccessSubtleHover.val,
        success12: tokens.color.lightBackgroundSuccessSubtleDisabled.val,
        success13: tokens.color.lightBorderSuccess.val,
        success14: tokens.color.lightBorderSuccessSubtle.val,
        success15: tokens.color.lightBorderSuccessHover.val,
        success16: tokens.color.lightBorderSuccessDisabled.val,
        success17: tokens.color.lightBorderSuccessSubtleHover.val,
        success18: tokens.color.lightBorderSuccessSubtleDisabled.val
      },
      dark: {
        success1: tokens.color.darkForegroundSuccess.val,
        success2: tokens.color.darkForegroundOnSuccess.val,
        success3: tokens.color.darkForegroundSuccessHover.val,
        success4: tokens.color.darkForegroundSuccessDisabled.val,
        success5: tokens.color.darkForegroundOnSuccessHover.val,
        success6: tokens.color.darkForegroundOnSuccessDisabled.val,
        success7: tokens.color.darkBackgroundSuccess.val,
        success8: tokens.color.darkBackgroundSuccessSubtle.val,
        success9: tokens.color.darkBackgroundSuccessHover.val,
        success10: tokens.color.darkBackgroundSuccessDisabled.val,
        success11: tokens.color.darkBackgroundSuccessSubtleHover.val,
        success12: tokens.color.darkBackgroundSuccessSubtleDisabled.val,
        success13: tokens.color.darkBorderSuccess.val,
        success14: tokens.color.darkBorderSuccessSubtle.val,
        success15: tokens.color.darkBorderSuccessHover.val,
        success16: tokens.color.darkBorderSuccessDisabled.val,
        success17: tokens.color.darkBorderSuccessSubtleHover.val,
        success18: tokens.color.darkBorderSuccessSubtleDisabled.val
      }
    },
    surface: {
      light: {
        surface1: tokens.color.lightSurface1.val,
        surface2: tokens.color.lightSurface2.val,
        surface3: tokens.color.lightSurface3.val,
        surface4: tokens.color.lightSurface4.val
      },
      dark: {
        surface1: tokens.color.darkSurface1.val,
        surface2: tokens.color.darkSurface2.val,
        surface3: tokens.color.darkSurface3.val,
        surface4: tokens.color.darkSurface4.val
      }
    },
    warning: {
      light: {
        warning1: tokens.color.lightForegroundWarning.val,
        warning2: tokens.color.lightForegroundOnWarning.val,
        warning3: tokens.color.lightForegroundWarningHover.val,
        warning4: tokens.color.lightForegroundWarningDisabled.val,
        warning5: tokens.color.lightForegroundOnWarningHover.val,
        warning6: tokens.color.lightForegroundOnWarningDisabled.val,
        warning7: tokens.color.lightBackgroundWarning.val,
        warning8: tokens.color.lightBackgroundWarningSubtle.val,
        warning9: tokens.color.lightBackgroundWarningHover.val,
        warning10: tokens.color.lightBackgroundWarningDisabled.val,
        warning11: tokens.color.lightBackgroundWarningSubtleHover.val,
        warning12: tokens.color.lightBackgroundWarningSubtleDisabled.val,
        warning13: tokens.color.lightBorderWarning.val,
        warning14: tokens.color.lightBorderWarningSubtle.val,
        warning15: tokens.color.lightBorderWarningHover.val,
        warning16: tokens.color.lightBorderWarningDisabled.val,
        warning17: tokens.color.lightBorderWarningSubtleHover.val,
        warning18: tokens.color.lightBorderWarningSubtleDisabled.val
      },
      dark: {
        warning1: tokens.color.darkForegroundWarning.val,
        warning2: tokens.color.darkForegroundOnWarning.val,
        warning3: tokens.color.darkForegroundWarningHover.val,
        warning4: tokens.color.darkForegroundWarningDisabled.val,
        warning5: tokens.color.darkForegroundOnWarningHover.val,
        warning6: tokens.color.darkForegroundOnWarningDisabled.val,
        warning7: tokens.color.darkBackgroundWarning.val,
        warning8: tokens.color.darkBackgroundWarningSubtle.val,
        warning9: tokens.color.darkBackgroundWarningHover.val,
        warning10: tokens.color.darkBackgroundWarningDisabled.val,
        warning11: tokens.color.darkBackgroundWarningSubtleHover.val,
        warning12: tokens.color.darkBackgroundWarningSubtleDisabled.val,
        warning13: tokens.color.darkBorderWarning.val,
        warning14: tokens.color.darkBorderWarningSubtle.val,
        warning15: tokens.color.darkBorderWarningHover.val,
        warning16: tokens.color.darkBorderWarningDisabled.val,
        warning17: tokens.color.darkBorderWarningSubtleHover.val,
        warning18: tokens.color.darkBorderWarningSubtleDisabled.val
      }
    },
    yellow: {
      light: {
        yellow1: tokens.color.lightYellow1.val,
        yellow2: tokens.color.lightYellow2.val,
        yellow3: tokens.color.lightYellow3.val,
        yellow4: tokens.color.lightYellow4.val,
        yellow5: tokens.color.lightYellow5.val,
        yellow6: tokens.color.lightYellow6.val,
        yellow7: tokens.color.lightYellow7.val,
        yellow8: tokens.color.lightYellow8.val,
        yellow9: tokens.color.lightYellow9.val
      },
      dark: {
        yellow1: tokens.color.darkYellow9.val,
        yellow2: tokens.color.darkYellow8.val,
        yellow3: tokens.color.darkYellow7.val,
        yellow4: tokens.color.darkYellow6.val,
        yellow5: tokens.color.darkYellow5.val,
        yellow6: tokens.color.darkYellow4.val,
        yellow7: tokens.color.darkYellow3.val,
        yellow8: tokens.color.darkYellow2.val,
        yellow9: tokens.color.darkYellow1.val
      }
    }
  },
  getTheme: ({ theme, scheme, name }: { theme: AppTheme; scheme: "light" | "dark"; name?: string }) => {
    const values: Record<string, string> = scheme === "dark"
      ? {
        ...theme,
        backgroundAccent: "#36dec0",
        backgroundAccentDisabled: "#36dec099",
        backgroundAccentHover: "#009c82",
        backgroundAccentSubtle: "#003832",
        backgroundAccentSubtleDisabled: "#00383299",
        backgroundAccentSubtleHover: "#1b4c46",
        backgroundDanger: theme.red3,
        backgroundDangerDisabled: "#f5737799",
        backgroundDangerHover: "#b73a44",
        backgroundDangerSubtle: theme.red1,
        backgroundDangerSubtleDisabled: "#b7535799",
        backgroundDangerSubtleHover: "#882830",
        backgroundDiscovery: theme.purple3,
        backgroundDiscoveryDisabled: "#908ffe99",
        backgroundDiscoveryHover: "#5f59c2",
        backgroundDiscoverySubtle: theme.purple1,
        backgroundDiscoverySubtleDisabled: "#6c6bc199",
        backgroundDiscoverySubtleHover: "#464193",
        backgroundElevated: theme.surface2,
        backgroundElevatedDisabled: "#181b1b99",
        backgroundElevatedHover: "#252828",
        backgroundFloating: theme.surface3,
        backgroundFloatingDisabled: "#22242499",
        backgroundFloatingHover: "#323434",
        backgroundHighest: theme.surface4,
        backgroundHighestDisabled: "#2e303099",
        backgroundHighestHover: "#424444",
        backgroundInfo: theme.sky7,
        backgroundInfoDisabled: "#5ccbeb99",
        backgroundInfoHover: "#008cab",
        backgroundInfoSubtle: theme.sky1,
        backgroundInfoSubtleDisabled: "#0081a599",
        backgroundInfoSubtleHover: "#00587a",
        backgroundLink: theme.blue3,
        backgroundLinkDisabled: "#529cfc99",
        backgroundLinkHover: "#1866c1",
        backgroundPage: theme.surface1,
        backgroundPageDisabled: "#00010199",
        backgroundPageHover: "#000202",
        backgroundPrimary: theme.base9,
        backgroundPrimaryDisabled: "#fafafa99",
        backgroundPrimaryHover: "#aaaaaa",
        backgroundSecondary: theme.base2,
        backgroundSecondaryDisabled: "#090c0c99",
        backgroundSecondaryHover: "#111414",
        backgroundSuccess: theme.green4,
        backgroundSuccessDisabled: "#3bb97499",
        backgroundSuccessHover: "#008241",
        backgroundSuccessSubtle: theme.green1,
        backgroundSuccessSubtleDisabled: "#14874e99",
        backgroundSuccessSubtleHover: "#005e28",
        backgroundTertiary: theme.base1,
        backgroundTertiaryDisabled: "#090b0c99",
        backgroundTertiaryHover: "#111314",
        backgroundWarning: theme.yellow6,
        backgroundWarningDisabled: "#dfaf5699",
        backgroundWarningHover: "#a07302",
        backgroundWarningSubtle: theme.yellow1,
        backgroundWarningSubtleDisabled: "#9b6a0099",
        backgroundWarningSubtleHover: "#704200",
        black: "#0c0c0d",
        borderAccent: "#36dec0",
        borderAccentDisabled: "#36dec099",
        borderAccentHover: "#009c82",
        borderAccentSubtle: "#003832",
        borderAccentSubtleDisabled: "#00383299",
        borderAccentSubtleHover: "#1b4c46",
        borderDanger: theme.red3,
        borderDangerDisabled: "#f5737799",
        borderDangerHover: "#b73a44",
        borderDangerSubtle: theme.red1,
        borderDangerSubtleDisabled: "#b7535799",
        borderDangerSubtleHover: "#882830",
        borderDiscovery: theme.purple3,
        borderDiscoveryDisabled: "#908ffe99",
        borderDiscoveryHover: "#5f59c2",
        borderDiscoverySubtle: theme.purple1,
        borderDiscoverySubtleDisabled: "#6c6bc199",
        borderDiscoverySubtleHover: "#464193",
        borderInfo: theme.sky7,
        borderInfoDisabled: "#5ccbeb99",
        borderInfoHover: "#008cab",
        borderInfoSubtle: theme.sky1,
        borderInfoSubtleDisabled: "#0081a599",
        borderInfoSubtleHover: "#00587a",
        borderPrimary: theme.base5,
        borderPrimaryDisabled: "#27292a99",
        borderPrimaryHover: "#383b3c",
        borderSecondary: theme.base4,
        borderSecondaryDisabled: "#16181999",
        borderSecondaryHover: "#222425",
        borderSuccess: theme.green4,
        borderSuccessDisabled: "#3bb97499",
        borderSuccessHover: "#008241",
        borderSuccessSubtle: theme.green1,
        borderSuccessSubtleDisabled: "#14874e99",
        borderSuccessSubtleHover: "#005e28",
        borderTertiary: theme.base3,
        borderTertiaryDisabled: "#0d0f1099",
        borderTertiaryHover: "#161819",
        borderWarning: theme.yellow6,
        borderWarningDisabled: "#dfaf5699",
        borderWarningHover: "#a07302",
        borderWarningSubtle: theme.yellow1,
        borderWarningSubtleDisabled: "#9b6a0099",
        borderWarningSubtleHover: "#704200",
        brand1: "#36dec0",
        brand2: "#003832",
        dataBaseEmphasis: theme.base9,
        dataBaseSubtle: theme.base2,
        dataBlueEmphasis: theme.blue5,
        dataBlueSubtle: theme.blue1,
        dataBrandEmphasis: "#36dec0",
        dataBrandSubtle: "#003832",
        dataGreenEmphasis: theme.green5,
        dataGreenSubtle: theme.green1,
        dataOrangeEmphasis: theme.orange5,
        dataOrangeSubtle: theme.orange1,
        dataPinkEmphasis: theme.pink5,
        dataPinkSubtle: theme.pink1,
        dataPurpleEmphasis: theme.purple5,
        dataPurpleSubtle: theme.purple1,
        dataRedEmphasis: theme.red5,
        dataRedSubtle: theme.red1,
        dataSkyEmphasis: theme.sky5,
        dataSkySubtle: theme.sky1,
        dataYellowEmphasis: theme.yellow5,
        dataYellowSubtle: theme.yellow1,
        foregroundAccent: "#36dec0",
        foregroundAccentDisabled: "#36dec099",
        foregroundAccentHover: "#009c82",
        foregroundBody: theme.base8,
        foregroundBodyDisabled: "#abacac99",
        foregroundBodyHover: "#737474",
        foregroundDanger: theme.red3,
        foregroundDangerDisabled: "#f5737799",
        foregroundDangerHover: "#b73a44",
        foregroundDiscovery: theme.purple3,
        foregroundDiscoveryDisabled: "#908ffe99",
        foregroundDiscoveryHover: "#5f59c2",
        foregroundInfo: theme.sky7,
        foregroundInfoDisabled: "#5ccbeb99",
        foregroundInfoHover: "#008cab",
        foregroundLink: theme.blue3,
        foregroundLinkDisabled: "#529cfc99",
        foregroundLinkHover: "#1866c1",
        foregroundOnAccent: theme.base9,
        foregroundOnAccentDisabled: "#fafafa99",
        foregroundOnAccentHover: "#aaaaaa",
        foregroundOnDanger: theme.base9,
        foregroundOnDangerDisabled: "#fafafa99",
        foregroundOnDangerHover: "#aaaaaa",
        foregroundOnDiscovery: theme.base9,
        foregroundOnDiscoveryDisabled: "#fafafa99",
        foregroundOnDiscoveryHover: "#aaaaaa",
        foregroundOnInfo: theme.base9,
        foregroundOnInfoDisabled: "#fafafa99",
        foregroundOnInfoHover: "#aaaaaa",
        foregroundOnPrimary: theme.base1,
        foregroundOnPrimaryDisabled: "#090b0c99",
        foregroundOnPrimaryHover: "#111314",
        foregroundOnSecondary: theme.base9,
        foregroundOnSecondaryDisabled: "#fafafa99",
        foregroundOnSecondaryHover: "#aaaaaa",
        foregroundOnSuccess: theme.base9,
        foregroundOnSuccessDisabled: "#fafafa99",
        foregroundOnSuccessHover: "#aaaaaa",
        foregroundOnTertiary: theme.base9,
        foregroundOnTertiaryDisabled: "#fafafa99",
        foregroundOnTertiaryHover: "#aaaaaa",
        foregroundOnWarning: theme.base1,
        foregroundOnWarningDisabled: "#090b0c99",
        foregroundOnWarningHover: "#111314",
        foregroundPrimary: theme.base9,
        foregroundPrimaryDisabled: "#fafafa99",
        foregroundPrimaryHover: "#aaaaaa",
        foregroundSecondary: theme.base5,
        foregroundSecondaryDisabled: "#27292a99",
        foregroundSecondaryHover: "#383b3c",
        foregroundSuccess: theme.green4,
        foregroundSuccessDisabled: "#3bb97499",
        foregroundSuccessHover: "#008241",
        foregroundTertiary: theme.base4,
        foregroundTertiaryDisabled: "#16181999",
        foregroundTertiaryHover: "#222425",
        foregroundWarning: theme.yellow6,
        foregroundWarningDisabled: "#dfaf5699",
        foregroundWarningHover: "#a07302",
        overlayBackdrop: "#0c0c0d66",
        overlayBackground: theme.surface3,
        overlayBackgroundDisabled: "#22242499",
        overlayBackgroundHover: "#323434",
        overlayBorder: theme.base5,
        overlayBorderDisabled: "#27292a99",
        overlayBorderHover: "#383b3c",
        ringAccent: "0px 0px 0px 3px #36dec0",
        ringAccentSubtle: "0px 0px 0px 1px #36dec0",
        ringDanger: `0px 0px 0px 3px ${theme.red3}`,
        ringDangerSubtle: `0px 0px 0px 1px ${theme.red3}`,
        ringDiscovery: `0px 0px 0px 3px ${theme.purple3}`,
        ringDiscoverySubtle: `0px 0px 0px 1px ${theme.purple3}`,
        ringInfo: `0px 0px 0px 3px ${theme.sky7}`,
        ringInfoSubtle: `0px 0px 0px 1px ${theme.sky7}`,
        ringPrimary: `0px 0px 0px 3px ${theme.base5}`,
        ringPrimarySubtle: `0px 0px 0px 1px ${theme.base5}`,
        ringSecondary: `0px 0px 0px 3px ${theme.base4}`,
        ringSecondarySubtle: `0px 0px 0px 1px ${theme.base4}`,
        ringSuccess: `0px 0px 0px 3px ${theme.green4}`,
        ringSuccessSubtle: `0px 0px 0px 1px ${theme.green4}`,
        ringTertiary: `0px 0px 0px 3px ${theme.base3}`,
        ringTertiarySubtle: `0px 0px 0px 1px ${theme.base3}`,
        ringWarning: `0px 0px 0px 3px ${theme.yellow6}`,
        ringWarningSubtle: `0px 0px 0px 1px ${theme.yellow6}`,
        transparent: "#ffffff00",
        white: "#ffffff"
      }
      : {
        ...theme,
        backgroundAccent: "#1fb2a6",
        backgroundAccentDisabled: "#1fb2a699",
        backgroundAccentHover: "#007c72",
        backgroundAccentSubtle: "#003832",
        backgroundAccentSubtleDisabled: "#00383299",
        backgroundAccentSubtleHover: "#1b4c46",
        backgroundDanger: theme.red7,
        backgroundDangerDisabled: "#d8616499",
        backgroundDangerHover: "#a12e37",
        backgroundDangerSubtle: theme.red9,
        backgroundDangerSubtleDisabled: "#a94e5099",
        backgroundDangerSubtleHover: "#7d262c",
        backgroundDiscovery: theme.purple7,
        backgroundDiscoveryDisabled: "#7f7ee499",
        backgroundDiscoveryHover: "#534dae",
        backgroundDiscoverySubtle: theme.purple9,
        backgroundDiscoverySubtleDisabled: "#6261af99",
        backgroundDiscoverySubtleHover: "#3f3b85",
        backgroundElevated: theme.surface2,
        backgroundElevatedDisabled: "#f4f4f399",
        backgroundElevatedHover: "#a6a6a5",
        backgroundFloating: theme.surface3,
        backgroundFloatingDisabled: "#e8e7e699",
        backgroundFloatingHover: "#9e9d9c",
        backgroundHighest: theme.surface4,
        backgroundHighestDisabled: "#c3c4c499",
        backgroundHighestHover: "#848585",
        backgroundInfo: theme.sky3,
        backgroundInfoDisabled: "#00b8e699",
        backgroundInfoHover: "#007fab",
        backgroundInfoSubtle: theme.sky9,
        backgroundInfoSubtleDisabled: "#00749699",
        backgroundInfoSubtleHover: "#004e6f",
        backgroundLink: theme.blue7,
        backgroundLinkDisabled: "#468ae299",
        backgroundLinkHover: "#115aad",
        backgroundPage: theme.surface1,
        backgroundPageDisabled: "#ffffff99",
        backgroundPageHover: "#aeaeae",
        backgroundPrimary: theme.base1,
        backgroundPrimaryDisabled: "#f4f4f499",
        backgroundPrimaryHover: "#a6a6a6",
        backgroundSecondary: theme.base8,
        backgroundSecondaryDisabled: "#1c1c1c99",
        backgroundSecondaryHover: "#2a2a2a",
        backgroundSuccess: theme.green6,
        backgroundSuccessDisabled: "#00a46999",
        backgroundSuccessHover: "#00733c",
        backgroundSuccessSubtle: theme.green9,
        backgroundSuccessSubtleDisabled: "#007a4d99",
        backgroundSuccessSubtleHover: "#00552b",
        backgroundTertiary: theme.base9,
        backgroundTertiaryDisabled: "#18181899",
        backgroundTertiaryHover: "#242424",
        backgroundWarning: theme.yellow4,
        backgroundWarningDisabled: "#d4940099",
        backgroundWarningHover: "#9a5e00",
        backgroundWarningSubtle: theme.yellow9,
        backgroundWarningSubtleDisabled: "#8f630099",
        backgroundWarningSubtleHover: "#673d00",
        black: "#0c0c0d",
        borderAccent: "#1fb2a6",
        borderAccentDisabled: "#1fb2a699",
        borderAccentHover: "#007c72",
        borderAccentSubtle: "#003832",
        borderAccentSubtleDisabled: "#00383299",
        borderAccentSubtleHover: "#1b4c46",
        borderDanger: theme.red7,
        borderDangerDisabled: "#d8616499",
        borderDangerHover: "#a12e37",
        borderDangerSubtle: theme.red9,
        borderDangerSubtleDisabled: "#a94e5099",
        borderDangerSubtleHover: "#7d262c",
        borderDiscovery: theme.purple7,
        borderDiscoveryDisabled: "#7f7ee499",
        borderDiscoveryHover: "#534dae",
        borderDiscoverySubtle: theme.purple9,
        borderDiscoverySubtleDisabled: "#6261af99",
        borderDiscoverySubtleHover: "#3f3b85",
        borderInfo: theme.sky3,
        borderInfoDisabled: "#00b8e699",
        borderInfoHover: "#007fab",
        borderInfoSubtle: theme.sky9,
        borderInfoSubtleDisabled: "#00749699",
        borderInfoSubtleHover: "#004e6f",
        borderPrimary: theme.base7,
        borderPrimaryDisabled: "#26262699",
        borderPrimaryHover: "#373737",
        borderSecondary: theme.base8,
        borderSecondaryDisabled: "#1c1c1c99",
        borderSecondaryHover: "#2a2a2a",
        borderSuccess: theme.green6,
        borderSuccessDisabled: "#00a46999",
        borderSuccessHover: "#00733c",
        borderSuccessSubtle: theme.green9,
        borderSuccessSubtleDisabled: "#007a4d99",
        borderSuccessSubtleHover: "#00552b",
        borderTertiary: theme.base9,
        borderTertiaryDisabled: "#18181899",
        borderTertiaryHover: "#242424",
        borderWarning: theme.yellow4,
        borderWarningDisabled: "#d4940099",
        borderWarningHover: "#9a5e00",
        borderWarningSubtle: theme.yellow9,
        borderWarningSubtleDisabled: "#8f630099",
        borderWarningSubtleHover: "#673d00",
        brand1: "#1fb2a6",
        brand2: "#003832",
        dataBaseEmphasis: theme.base5,
        dataBaseSubtle: theme.base1,
        dataBlueEmphasis: theme.blue6,
        dataBlueSubtle: theme.blue1,
        dataBrandEmphasis: "#1fb2a6",
        dataBrandSubtle: "#003832",
        dataGreenEmphasis: theme.green6,
        dataGreenSubtle: theme.green1,
        dataOrangeEmphasis: theme.orange6,
        dataOrangeSubtle: theme.orange1,
        dataPinkEmphasis: theme.pink6,
        dataPinkSubtle: theme.pink1,
        dataPurpleEmphasis: theme.purple6,
        dataPurpleSubtle: theme.purple1,
        dataRedEmphasis: theme.red6,
        dataRedSubtle: theme.red1,
        dataSkyEmphasis: theme.sky6,
        dataSkySubtle: theme.sky1,
        dataYellowEmphasis: theme.yellow6,
        dataYellowSubtle: theme.yellow1,
        foregroundAccent: "#1fb2a6",
        foregroundAccentDisabled: "#1fb2a699",
        foregroundAccentHover: "#007c72",
        foregroundBody: theme.base4,
        foregroundBodyDisabled: "#6e6e6e99",
        foregroundBodyHover: "#494949",
        foregroundDanger: theme.red7,
        foregroundDangerDisabled: "#d8616499",
        foregroundDangerHover: "#a12e37",
        foregroundDiscovery: theme.purple7,
        foregroundDiscoveryDisabled: "#7f7ee499",
        foregroundDiscoveryHover: "#534dae",
        foregroundInfo: theme.sky3,
        foregroundInfoDisabled: "#00b8e699",
        foregroundInfoHover: "#007fab",
        foregroundLink: theme.blue7,
        foregroundLinkDisabled: "#468ae299",
        foregroundLinkHover: "#115aad",
        foregroundOnAccent: theme.base1,
        foregroundOnAccentDisabled: "#f4f4f499",
        foregroundOnAccentHover: "#a6a6a6",
        foregroundOnDanger: theme.base1,
        foregroundOnDangerDisabled: "#f4f4f499",
        foregroundOnDangerHover: "#a6a6a6",
        foregroundOnDiscovery: theme.base1,
        foregroundOnDiscoveryDisabled: "#f4f4f499",
        foregroundOnDiscoveryHover: "#a6a6a6",
        foregroundOnInfo: theme.base1,
        foregroundOnInfoDisabled: "#f4f4f499",
        foregroundOnInfoHover: "#a6a6a6",
        foregroundOnPrimary: theme.base9,
        foregroundOnPrimaryDisabled: "#18181899",
        foregroundOnPrimaryHover: "#242424",
        foregroundOnSecondary: theme.base1,
        foregroundOnSecondaryDisabled: "#f4f4f499",
        foregroundOnSecondaryHover: "#a6a6a6",
        foregroundOnSuccess: theme.base1,
        foregroundOnSuccessDisabled: "#f4f4f499",
        foregroundOnSuccessHover: "#a6a6a6",
        foregroundOnTertiary: theme.base1,
        foregroundOnTertiaryDisabled: "#f4f4f499",
        foregroundOnTertiaryHover: "#a6a6a6",
        foregroundOnWarning: theme.base9,
        foregroundOnWarningDisabled: "#18181899",
        foregroundOnWarningHover: "#242424",
        foregroundPrimary: theme.base1,
        foregroundPrimaryDisabled: "#f4f4f499",
        foregroundPrimaryHover: "#a6a6a6",
        foregroundSecondary: theme.base8,
        foregroundSecondaryDisabled: "#1c1c1c99",
        foregroundSecondaryHover: "#2a2a2a",
        foregroundSuccess: theme.green6,
        foregroundSuccessDisabled: "#00a46999",
        foregroundSuccessHover: "#00733c",
        foregroundTertiary: theme.base9,
        foregroundTertiaryDisabled: "#18181899",
        foregroundTertiaryHover: "#242424",
        foregroundWarning: theme.yellow4,
        foregroundWarningDisabled: "#d4940099",
        foregroundWarningHover: "#9a5e00",
        overlayBackdrop: "#1a1c1f66",
        overlayBackground: theme.surface3,
        overlayBackgroundDisabled: "#e8e7e699",
        overlayBackgroundHover: "#9e9d9c",
        overlayBorder: theme.base7,
        overlayBorderDisabled: "#26262699",
        overlayBorderHover: "#373737",
        ringAccent: "0px 0px 0px 3px #1fb2a6",
        ringAccentSubtle: "0px 0px 0px 1px #1fb2a6",
        ringDanger: `0px 0px 0px 3px ${theme.red7}`,
        ringDangerSubtle: `0px 0px 0px 1px ${theme.red7}`,
        ringDiscovery: `0px 0px 0px 3px ${theme.purple7}`,
        ringDiscoverySubtle: `0px 0px 0px 1px ${theme.purple7}`,
        ringInfo: `0px 0px 0px 3px ${theme.sky3}`,
        ringInfoSubtle: `0px 0px 0px 1px ${theme.sky3}`,
        ringPrimary: `0px 0px 0px 3px ${theme.base7}`,
        ringPrimarySubtle: `0px 0px 0px 1px ${theme.base7}`,
        ringSecondary: `0px 0px 0px 3px ${theme.base8}`,
        ringSecondarySubtle: `0px 0px 0px 1px ${theme.base8}`,
        ringSuccess: `0px 0px 0px 3px ${theme.green6}`,
        ringSuccessSubtle: `0px 0px 0px 1px ${theme.green6}`,
        ringTertiary: `0px 0px 0px 3px ${theme.base9}`,
        ringTertiarySubtle: `0px 0px 0px 1px ${theme.base9}`,
        ringWarning: `0px 0px 0px 3px ${theme.yellow4}`,
        ringWarningSubtle: `0px 0px 0px 1px ${theme.yellow4}`,
        transparent: "#ffffff00",
        white: "#ffffff"
      };
    const child = name?.split("_")[1];
    const role =
      child && SEMANTIC_ROLES.has(child)
        ? child.charAt(0).toUpperCase() + child.slice(1)
        : "Primary";
    const overlay: Record<string, string> = {};
    const assign = (alias: string, source: string) => {
      const value = values[source];
      if (value !== undefined) {
        overlay[alias] = value;
      }
    };
    assign("background", `background${role}`);
    assign("backgroundDisabled", `background${role}Disabled`);
    assign("backgroundHover", `background${role}Hover`);
    assign("backgroundSubtle", role === "Primary" ? "backgroundSecondary" : `background${role}Subtle`);
    assign("border", `border${role}`);
    assign("borderDisabled", `border${role}Disabled`);
    assign("borderHover", `border${role}Hover`);
    assign("borderSubtle", role === "Primary" ? "borderSecondary" : `border${role}Subtle`);
    assign("foreground", `foreground${role}`);
    assign("foregroundDisabled", `foreground${role}Disabled`);
    assign("foregroundHover", `foreground${role}Hover`);
    assign("foregroundOn", `foregroundOn${role}`);
    assign("foregroundOnDisabled", `foregroundOn${role}Disabled`);
    assign("foregroundOnHover", `foregroundOn${role}Hover`);
    return {
      ...values,
      ...overlay
    };
  }
});

const assetsFont = createFont({
  family: "Assets",
  size: {
    1: 12,
    2: 14,
    3: 16,
    4: 18,
    5: 20,
    6: 24,
    7: 28,
    8: 32,
    9: 40,
    10: 48
  },
  face: {
    400: { normal: "transparent" }
  }
});

const bodyFont = createFont({
  family: "Space Grotesk",
  size: {
    md: 16,
    true: 16
  },
  lineHeight: {
    md: 24,
    true: 24
  },
  weight: {
    light: "300",
    md: "300",
    true: "300"
  }
});

const captionFont = createFont({
  family: "Space Grotesk",
  size: {
    true: 12,
    xs: 12
  },
  lineHeight: {
    true: 16,
    xs: 16
  },
  weight: {
    light: "300",
    true: "300",
    xs: "300"
  }
});

const codeFont = createFont({
  family: "Space Mono",
  size: {
    sm: 14,
    true: 14
  },
  lineHeight: {
    sm: 20,
    true: 20
  },
  weight: {
    normal: "400",
    sm: "400",
    true: "400"
  }
});

const displayLgFont = createFont({
  family: "Permanent Marker",
  size: {
    "5xl": 48,
    true: 48
  },
  lineHeight: {
    "5xl": 48,
    true: 48
  },
  weight: {
    "5xl": "400",
    normal: "400",
    true: "400"
  }
});

const displayMdFont = createFont({
  family: "Permanent Marker",
  size: {
    "3xl": 30,
    true: 30
  },
  lineHeight: {
    "3xl": 36,
    true: 36
  },
  weight: {
    "3xl": "400",
    normal: "400",
    true: "400"
  }
});

const displaySmFont = createFont({
  family: "Permanent Marker",
  size: {
    "2xl": 24,
    true: 24
  },
  lineHeight: {
    "2xl": 32,
    true: 32
  },
  weight: {
    "2xl": "400",
    normal: "400",
    true: "400"
  }
});

const heading2xlFont = createFont({
  family: "Space Grotesk",
  size: {
    "3xl": 30,
    true: 30
  },
  lineHeight: {
    "3xl": 36,
    true: 36
  },
  weight: {
    "3xl": "700",
    bold: "700",
    true: "700"
  }
});

const headingLgFont = createFont({
  family: "Space Grotesk",
  size: {
    true: 20,
    xl: 20
  },
  lineHeight: {
    true: 28,
    xl: 28
  },
  weight: {
    bold: "700",
    true: "700",
    xl: "700"
  }
});

const headingMdFont = createFont({
  family: "Space Grotesk",
  size: {
    lg: 18,
    true: 18
  },
  lineHeight: {
    lg: 28,
    true: 28
  },
  weight: {
    lg: "600",
    semibold: "600",
    true: "600"
  }
});

const headingSmFont = createFont({
  family: "Space Grotesk",
  size: {
    md: 16,
    true: 16
  },
  lineHeight: {
    md: 24,
    true: 24
  },
  weight: {
    md: "600",
    semibold: "600",
    true: "600"
  }
});

const headingXlFont = createFont({
  family: "Space Grotesk",
  size: {
    "2xl": 24,
    true: 24
  },
  lineHeight: {
    "2xl": 32,
    true: 32
  },
  weight: {
    "2xl": "700",
    bold: "700",
    true: "700"
  }
});


/**
 * Theme values available on `useTheme()` and `$` style props for the cyclone-ui.
 *
 * Derived from design tokens mapped by `createV5Theme` and `getTheme`.
 *
 * @see https://tamagui.dev/docs/guides/theme-builder#gettheme
 */
export interface AppTheme {
  accent1: string;
  accent2: string;
  accent3: string;
  accent4: string;
  accent5: string;
  accent6: string;
  accent7: string;
  accent8: string;
  accent9: string;
  accent10: string;
  accent11: string;
  accent12: string;
  accent13: string;
  accent14: string;
  accent15: string;
  accent16: string;
  accent17: string;
  accent18: string;
  background: string;
  backgroundAccent: string;
  backgroundAccentDisabled: string;
  backgroundAccentHover: string;
  backgroundAccentSubtle: string;
  backgroundAccentSubtleDisabled: string;
  backgroundAccentSubtleHover: string;
  backgroundDanger: string;
  backgroundDangerDisabled: string;
  backgroundDangerHover: string;
  backgroundDangerSubtle: string;
  backgroundDangerSubtleDisabled: string;
  backgroundDangerSubtleHover: string;
  backgroundDisabled: string;
  backgroundDiscovery: string;
  backgroundDiscoveryDisabled: string;
  backgroundDiscoveryHover: string;
  backgroundDiscoverySubtle: string;
  backgroundDiscoverySubtleDisabled: string;
  backgroundDiscoverySubtleHover: string;
  backgroundElevated: string;
  backgroundElevatedDisabled: string;
  backgroundElevatedHover: string;
  backgroundFloating: string;
  backgroundFloatingDisabled: string;
  backgroundFloatingHover: string;
  backgroundHighest: string;
  backgroundHighestDisabled: string;
  backgroundHighestHover: string;
  backgroundHover: string;
  backgroundInfo: string;
  backgroundInfoDisabled: string;
  backgroundInfoHover: string;
  backgroundInfoSubtle: string;
  backgroundInfoSubtleDisabled: string;
  backgroundInfoSubtleHover: string;
  backgroundLink: string;
  backgroundLinkDisabled: string;
  backgroundLinkHover: string;
  backgroundPage: string;
  backgroundPageDisabled: string;
  backgroundPageHover: string;
  backgroundPrimary: string;
  backgroundPrimaryDisabled: string;
  backgroundPrimaryHover: string;
  backgroundSecondary: string;
  backgroundSecondaryDisabled: string;
  backgroundSecondaryHover: string;
  backgroundSubtle: string;
  backgroundSuccess: string;
  backgroundSuccessDisabled: string;
  backgroundSuccessHover: string;
  backgroundSuccessSubtle: string;
  backgroundSuccessSubtleDisabled: string;
  backgroundSuccessSubtleHover: string;
  backgroundTertiary: string;
  backgroundTertiaryDisabled: string;
  backgroundTertiaryHover: string;
  backgroundWarning: string;
  backgroundWarningDisabled: string;
  backgroundWarningHover: string;
  backgroundWarningSubtle: string;
  backgroundWarningSubtleDisabled: string;
  backgroundWarningSubtleHover: string;
  base1: string;
  base2: string;
  base3: string;
  base4: string;
  base5: string;
  base6: string;
  base7: string;
  base8: string;
  base9: string;
  base10: string;
  base11: string;
  base12: string;
  black: string;
  blue1: string;
  blue2: string;
  blue3: string;
  blue4: string;
  blue5: string;
  blue6: string;
  blue7: string;
  blue8: string;
  blue9: string;
  border: string;
  borderAccent: string;
  borderAccentDisabled: string;
  borderAccentHover: string;
  borderAccentSubtle: string;
  borderAccentSubtleDisabled: string;
  borderAccentSubtleHover: string;
  borderDanger: string;
  borderDangerDisabled: string;
  borderDangerHover: string;
  borderDangerSubtle: string;
  borderDangerSubtleDisabled: string;
  borderDangerSubtleHover: string;
  borderDisabled: string;
  borderDiscovery: string;
  borderDiscoveryDisabled: string;
  borderDiscoveryHover: string;
  borderDiscoverySubtle: string;
  borderDiscoverySubtleDisabled: string;
  borderDiscoverySubtleHover: string;
  borderHover: string;
  borderInfo: string;
  borderInfoDisabled: string;
  borderInfoHover: string;
  borderInfoSubtle: string;
  borderInfoSubtleDisabled: string;
  borderInfoSubtleHover: string;
  borderPrimary: string;
  borderPrimaryDisabled: string;
  borderPrimaryHover: string;
  borderSecondary: string;
  borderSecondaryDisabled: string;
  borderSecondaryHover: string;
  borderSubtle: string;
  borderSuccess: string;
  borderSuccessDisabled: string;
  borderSuccessHover: string;
  borderSuccessSubtle: string;
  borderSuccessSubtleDisabled: string;
  borderSuccessSubtleHover: string;
  borderTertiary: string;
  borderTertiaryDisabled: string;
  borderTertiaryHover: string;
  borderWarning: string;
  borderWarningDisabled: string;
  borderWarningHover: string;
  borderWarningSubtle: string;
  borderWarningSubtleDisabled: string;
  borderWarningSubtleHover: string;
  brand1: string;
  brand2: string;
  danger1: string;
  danger2: string;
  danger3: string;
  danger4: string;
  danger5: string;
  danger6: string;
  danger7: string;
  danger8: string;
  danger9: string;
  danger10: string;
  danger11: string;
  danger12: string;
  danger13: string;
  danger14: string;
  danger15: string;
  danger16: string;
  danger17: string;
  danger18: string;
  dataBaseEmphasis: string;
  dataBaseSubtle: string;
  dataBlueEmphasis: string;
  dataBlueSubtle: string;
  dataBrandEmphasis: string;
  dataBrandSubtle: string;
  dataGreenEmphasis: string;
  dataGreenSubtle: string;
  dataOrangeEmphasis: string;
  dataOrangeSubtle: string;
  dataPinkEmphasis: string;
  dataPinkSubtle: string;
  dataPurpleEmphasis: string;
  dataPurpleSubtle: string;
  dataRedEmphasis: string;
  dataRedSubtle: string;
  dataSkyEmphasis: string;
  dataSkySubtle: string;
  dataYellowEmphasis: string;
  dataYellowSubtle: string;
  discovery1: string;
  discovery2: string;
  discovery3: string;
  discovery4: string;
  discovery5: string;
  discovery6: string;
  discovery7: string;
  discovery8: string;
  discovery9: string;
  discovery10: string;
  discovery11: string;
  discovery12: string;
  discovery13: string;
  discovery14: string;
  discovery15: string;
  discovery16: string;
  discovery17: string;
  discovery18: string;
  foreground: string;
  foregroundAccent: string;
  foregroundAccentDisabled: string;
  foregroundAccentHover: string;
  foregroundBody: string;
  foregroundBodyDisabled: string;
  foregroundBodyHover: string;
  foregroundDanger: string;
  foregroundDangerDisabled: string;
  foregroundDangerHover: string;
  foregroundDisabled: string;
  foregroundDiscovery: string;
  foregroundDiscoveryDisabled: string;
  foregroundDiscoveryHover: string;
  foregroundHover: string;
  foregroundInfo: string;
  foregroundInfoDisabled: string;
  foregroundInfoHover: string;
  foregroundLink: string;
  foregroundLinkDisabled: string;
  foregroundLinkHover: string;
  foregroundOn: string;
  foregroundOnAccent: string;
  foregroundOnAccentDisabled: string;
  foregroundOnAccentHover: string;
  foregroundOnDanger: string;
  foregroundOnDangerDisabled: string;
  foregroundOnDangerHover: string;
  foregroundOnDisabled: string;
  foregroundOnDiscovery: string;
  foregroundOnDiscoveryDisabled: string;
  foregroundOnDiscoveryHover: string;
  foregroundOnHover: string;
  foregroundOnInfo: string;
  foregroundOnInfoDisabled: string;
  foregroundOnInfoHover: string;
  foregroundOnPrimary: string;
  foregroundOnPrimaryDisabled: string;
  foregroundOnPrimaryHover: string;
  foregroundOnSecondary: string;
  foregroundOnSecondaryDisabled: string;
  foregroundOnSecondaryHover: string;
  foregroundOnSuccess: string;
  foregroundOnSuccessDisabled: string;
  foregroundOnSuccessHover: string;
  foregroundOnTertiary: string;
  foregroundOnTertiaryDisabled: string;
  foregroundOnTertiaryHover: string;
  foregroundOnWarning: string;
  foregroundOnWarningDisabled: string;
  foregroundOnWarningHover: string;
  foregroundPrimary: string;
  foregroundPrimaryDisabled: string;
  foregroundPrimaryHover: string;
  foregroundSecondary: string;
  foregroundSecondaryDisabled: string;
  foregroundSecondaryHover: string;
  foregroundSuccess: string;
  foregroundSuccessDisabled: string;
  foregroundSuccessHover: string;
  foregroundTertiary: string;
  foregroundTertiaryDisabled: string;
  foregroundTertiaryHover: string;
  foregroundWarning: string;
  foregroundWarningDisabled: string;
  foregroundWarningHover: string;
  green1: string;
  green2: string;
  green3: string;
  green4: string;
  green5: string;
  green6: string;
  green7: string;
  green8: string;
  green9: string;
  info1: string;
  info2: string;
  info3: string;
  info4: string;
  info5: string;
  info6: string;
  info7: string;
  info8: string;
  info9: string;
  info10: string;
  info11: string;
  info12: string;
  info13: string;
  info14: string;
  info15: string;
  info16: string;
  info17: string;
  info18: string;
  orange1: string;
  orange2: string;
  orange3: string;
  orange4: string;
  orange5: string;
  orange6: string;
  orange7: string;
  orange8: string;
  orange9: string;
  overlayBackdrop: string;
  overlayBackground: string;
  overlayBackgroundDisabled: string;
  overlayBackgroundHover: string;
  overlayBorder: string;
  overlayBorderDisabled: string;
  overlayBorderHover: string;
  pink1: string;
  pink2: string;
  pink3: string;
  pink4: string;
  pink5: string;
  pink6: string;
  pink7: string;
  pink8: string;
  pink9: string;
  purple1: string;
  purple2: string;
  purple3: string;
  purple4: string;
  purple5: string;
  purple6: string;
  purple7: string;
  purple8: string;
  purple9: string;
  red1: string;
  red2: string;
  red3: string;
  red4: string;
  red5: string;
  red6: string;
  red7: string;
  red8: string;
  red9: string;
  ringAccent: string;
  ringAccentSubtle: string;
  ringDanger: string;
  ringDangerSubtle: string;
  ringDiscovery: string;
  ringDiscoverySubtle: string;
  ringInfo: string;
  ringInfoSubtle: string;
  ringPrimary: string;
  ringPrimarySubtle: string;
  ringSecondary: string;
  ringSecondarySubtle: string;
  ringSuccess: string;
  ringSuccessSubtle: string;
  ringTertiary: string;
  ringTertiarySubtle: string;
  ringWarning: string;
  ringWarningSubtle: string;
  sky1: string;
  sky2: string;
  sky3: string;
  sky4: string;
  sky5: string;
  sky6: string;
  sky7: string;
  sky8: string;
  sky9: string;
  success1: string;
  success2: string;
  success3: string;
  success4: string;
  success5: string;
  success6: string;
  success7: string;
  success8: string;
  success9: string;
  success10: string;
  success11: string;
  success12: string;
  success13: string;
  success14: string;
  success15: string;
  success16: string;
  success17: string;
  success18: string;
  surface1: string;
  surface2: string;
  surface3: string;
  surface4: string;
  transparent: string;
  warning1: string;
  warning2: string;
  warning3: string;
  warning4: string;
  warning5: string;
  warning6: string;
  warning7: string;
  warning8: string;
  warning9: string;
  warning10: string;
  warning11: string;
  warning12: string;
  warning13: string;
  warning14: string;
  warning15: string;
  warning16: string;
  warning17: string;
  warning18: string;
  white: string;
  yellow1: string;
  yellow2: string;
  yellow3: string;
  yellow4: string;
  yellow5: string;
  yellow6: string;
  yellow7: string;
  yellow8: string;
  yellow9: string;
}

/**
 * The Tamagui v5 config for the cyclone-ui.
 *
 * @see https://tamagui.dev/docs/core/config-v5
 */
export const config = createTamagui({
  animations,
  tokens,
  themes,
  fonts: {
    assets: assetsFont,
    body: bodyFont,
    caption: captionFont,
    code: codeFont,
    "display-lg": displayLgFont,
    "display-md": displayMdFont,
    "display-sm": displaySmFont,
    "heading-2xl": heading2xlFont,
    "heading-lg": headingLgFont,
    "heading-md": headingMdFont,
    "heading-sm": headingSmFont,
    "heading-xl": headingXlFont
  },
  defaultFont: "Space Grotesk"
, ...userConfig 
});

export type AppConfig = typeof config;

declare module "@tamagui/core" {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface TamaguiCustomConfig extends AppConfig {}
}

export default config;
