/* eslint-disable */
/* oxlint-disable */
// biome-ignore lint: disable

import { showBanner } from "shell-shock:banner/guidelines";
import { textColors, writeLine } from "shell-shock:console";
import { env, isDebug, isDevelopment } from "shell-shock:env";
import { showHelp } from "shell-shock:help/guidelines";
import {
  type GlobalOptions,
  hasFlag,
  isHelp,
  useArgs,
  useGlobalOptions,
  withCommand
} from "shell-shock:state";
import { executeUpdate } from "shell-shock:update";
import { isInteractive } from "shell-shock:utils";
import handleGuidelines from "./command";

// Generated by Power Plant
// Please do not edit this file manually - it will be automatically overwritten
// the next time the generator is run.

export interface GuidelinesOptions extends GlobalOptions {
  /**
   * Search terms matched against guideline keywords, titles and body (fuzzy). Omit to return all guidelines.
   */
  terms?: string[] | undefined;
  /**
   * Maximum matches per term when searching.
   */
  limit?: number | undefined;
}

/**
 * The Guidelines (cyclone-ui guidelines) command.
 *
 * @remarks
 * Return design-system guidelines as Markdown: an overview of the token groups, one section per component (with usage examples), typography, the design-system style guidelines, and any bundled guideline documents. Pass --terms to search; omit for the full set.
 *
 * @title Guidelines
 *
 * @param args - The command-line arguments passed to the command.
 */
export async function handler(args: string[] = useArgs()) {
  const options = {
    ...useGlobalOptions(),
    terms: [],
    limit: 1
  } as unknown as GuidelinesOptions;

  for (let i = 0; i < args.slice(0).length; i++) {
    const arg: string =
      args[i].length > 3 && args[i].startsWith("--")
        ? `--${args[i].slice(2).replaceAll("-", "").toLowerCase().replaceAll("-", "").replaceAll("_", "")}`
        : args[i].length > 2 && args[i].startsWith("-")
          ? `-${args[i].slice(1).replaceAll("-", "")}`
          : args[i];
    if (
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("terms=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "terms" ||
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("terms=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "terms"
    ) {
      options.terms ??= [];
      if (
        /^--?(terms)=/.test(
          "-" + arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
        )
      ) {
        options.terms.push(
          ...arg
            .replace(/^--?(terms)=/, "")
            .split(",")
            .map(item =>
              item
                .trim()
                .replace(/^("|')/, "")
                .replace(/("|')$/, "")
            )
            .filter(Boolean)
        );
      } else if (args.length > i + 1) {
        options.terms.push(
          ...args[++i]
            .split(",")
            .map(item =>
              item
                .trim()
                .replace(/^("|')/, "")
                .replace(/("|')$/, "")
            )
            .filter(Boolean)
        );
      }
    } else if (
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("limit=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "limit" ||
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("limit=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "limit"
    ) {
      if (
        /^--?(limit)=/.test(
          "-" + arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
        )
      ) {
        const value = Number(
          arg
            .replace(/^--?(limit)=/, "")
            .trim()
            .replace(/^("|')/, "")
            .replace(/("|')$/, "")
        );
        if (!Number.isNaN(value)) {
          options.limit = value;
        }
      } else if (args.length > i + 1) {
        const value = Number(
          args[++i]
            .trim()
            .replace(/^("|')/, "")
            .replace(/("|')$/, "")
        );
        if (!Number.isNaN(value)) {
          options.limit = value;
        }
      }
    }
  }

  if (!hasFlag("quiet")) {
    await showBanner();
    await executeUpdate();
  }

  if (!isHelp() && !hasFlag("quiet")) {
    writeLine("");
    if (isDevelopment || isDebug || env.LOG_LEVEL === "debug") {
      writeLine(
        textColors.body.tertiary(
          "Debug mode is enabled. Additional debug information may be logged to the console."
        )
      );
    }
  }

  if (!isInteractive) {
    const failures: string[] = [];
    if (options.limit && Number.isNaN(options.limit)) {
      failures.push('Invalid numeric value provided for the "limit" option');
    }
  }

  if (options.help) {
    return showHelp();
  } else {
    return withCommand(
      "guidelines",
      ["guidelines"],
      [options],
      handleGuidelines
    );
  }
}
