/* eslint-disable */
/* oxlint-disable */
// biome-ignore lint: disable

import { McpServer } from "@modelcontextprotocol/server";
import { StdioServerTransport } from "@modelcontextprotocol/server/stdio";
import { defineMetadata, defineOptions } from "@shell-shock/core";
import { spawn } from "shell-shock:exec";
import { z } from "zod/v4";

// Generated by Power Plant
// Please do not edit this file manually - it will be automatically overwritten
// the next time the generator is run.

const COMMAND_NAME = "mcp";
const APP_NAME = "cyclone-ui";

const COMMANDS = [
  {
    id: "add",
    name: "add",
    path: "add",
    segments: ["add"],
    title: "Add",
    description:
      "Adds a new component to the project.\nOptions: --cwd (string), --overwrite (boolean), --all (boolean), --path (string), --dry-run (boolean), --diff (boolean), --view (boolean), --silent (boolean), --registry (string)\nArgs: components:string[]",
    toolName: "add",
    options: [
      {
        name: "cwd",
        title: "Current Working Directory",
        description: "The working directory.",
        type: "string",
        required: false,
        variadic: false
      },
      {
        name: "overwrite",
        title: "Overwrite",
        description: "Overwrite existing files.",
        type: "boolean",
        required: false,
        variadic: false
      },
      {
        name: "all",
        title: "All",
        description: "Add every available component.",
        type: "boolean",
        required: false,
        variadic: false
      },
      {
        name: "path",
        title: "Path",
        description: "Override the configured component output path.",
        type: "string",
        required: false,
        variadic: false
      },
      {
        name: "dryRun",
        title: "Dry Run",
        description: "Preview changes without writing files.",
        type: "boolean",
        required: false,
        variadic: false
      },
      {
        name: "diff",
        title: "Diff",
        description: "Show the changes as a diff without writing files.",
        type: "boolean",
        required: false,
        variadic: false
      },
      {
        name: "view",
        title: "View",
        description: "Show resolved file contents without writing files.",
        type: "boolean",
        required: false,
        variadic: false
      },
      {
        name: "silent",
        title: "Silent",
        description: "Mute non-essential output.",
        type: "boolean",
        required: false,
        variadic: false
      },
      {
        name: "registry",
        title: "Registry",
        description: "Override the configured registry API URL.",
        type: "string",
        required: false,
        variadic: false
      }
    ],
    args: [
      {
        name: "components",
        title: "Components",
        description: "Component names to add.",
        type: "string",
        required: false,
        variadic: true
      }
    ]
  },
  {
    id: "analyze-a11y",
    name: "analyze-a11y",
    path: "analyze-a11y",
    segments: ["analyze-a11y"],
    title: "Analyze Accessibility",
    description:
      "Analyze a React/JSX source string (or file) for likely accessibility issues and hard-coded colors, suggesting the nearest design tokens for each color.\nOptions: --code (string), --file (string), --component-name (string), --context (string), --pattern-analysis (boolean)",
    toolName: "analyze-a11y",
    options: [
      {
        name: "code",
        title: "Code",
        description:
          "Source code of a React component or JSX snippet to analyze.",
        type: "string",
        required: false,
        variadic: false
      },
      {
        name: "file",
        title: "File",
        description:
          "Path to a source file to analyze (alternative to --code).",
        type: "string",
        required: false,
        variadic: false
      },
      {
        name: "componentName",
        title: "Component Name",
        description: "Optional label for the component under review.",
        type: "string",
        required: false,
        variadic: false
      },
      {
        name: "context",
        title: "Context",
        description:
          'Optional usage context (for example "in a form" or "modal").',
        type: "string",
        required: false,
        variadic: false
      },
      {
        name: "patternAnalysis",
        title: "Pattern Analysis",
        description:
          "Run regex-based heuristics (unlabeled buttons, missing alt, …).",
        type: "boolean",
        required: false,
        variadic: false
      }
    ],
    args: []
  },
  {
    id: "build",
    name: "build",
    path: "build",
    segments: ["build"],
    title: "Build Registry",
    description:
      "Build registry item JSON files for distribution.\nOptions: --cwd (string), --output (string)\nArgs: registry:string",
    toolName: "build",
    options: [
      {
        name: "cwd",
        title: "Current Working Directory",
        description: "The working directory.",
        type: "string",
        required: false,
        variadic: false
      },
      {
        name: "output",
        title: "Output",
        description: "Output directory.",
        type: "string",
        required: false,
        variadic: false
      }
    ],
    args: [
      {
        name: "registry",
        title: "Registry",
        description: "Registry manifest path.",
        type: "string",
        required: false,
        variadic: false
      }
    ]
  },
  {
    id: "completions-bash-config",
    name: "config",
    path: "completions/bash/config",
    segments: ["completions", "bash", "config"],
    title: "Completions - Bash Configuration",
    description:
      "Update the current system's bash shell configuration to include completions for the Cyclone User Interface command-line interface.\nOptions: --display (boolean)\nArgs: path:string",
    toolName: "completions_bash_config",
    options: [
      {
        name: "display",
        title: "Display",
        description:
          "Should the generated completion script be written to console output instead of an actual file on disk? This is useful for debugging purposes or if you want to manually handle the output.",
        type: "boolean",
        required: false,
        variadic: false
      }
    ],
    args: [
      {
        name: "path",
        title: "Path",
        description:
          "An argument that allows the user to specify a custom Path string value.",
        type: "string",
        required: false,
        variadic: false
      }
    ]
  },
  {
    id: "completions-bash-script",
    name: "script",
    path: "completions/bash/script",
    segments: ["completions", "bash", "script"],
    title: "Completions - Bash Script",
    description:
      "Generate a bash completion script for the Cyclone User Interface command-line interface.\nOptions: --display (boolean)\nArgs: path:string",
    toolName: "completions_bash_script",
    options: [
      {
        name: "display",
        title: "Display",
        description:
          "Should the generated completion script be written to console output instead of an actual file on disk? This is useful for debugging purposes or if you want to manually handle the output.",
        type: "boolean",
        required: false,
        variadic: false
      }
    ],
    args: [
      {
        name: "path",
        title: "Path",
        description:
          "An argument that allows the user to specify a custom Path string value.",
        type: "string",
        required: false,
        variadic: false
      }
    ]
  },
  {
    id: "completions-fish-config",
    name: "config",
    path: "completions/fish/config",
    segments: ["completions", "fish", "config"],
    title: "Completions - Fish Configuration",
    description:
      "Update the current system's Fish shell configuration to include completions for the Cyclone User Interface command-line interface.\nOptions: --display (boolean)\nArgs: path:string",
    toolName: "completions_fish_config",
    options: [
      {
        name: "display",
        title: "Display",
        description:
          "Should the generated completion script be written to console output instead of an actual file on disk? This is useful for debugging purposes or if you want to manually handle the output.",
        type: "boolean",
        required: false,
        variadic: false
      }
    ],
    args: [
      {
        name: "path",
        title: "Path",
        description:
          "An argument that allows the user to specify a custom Path string value.",
        type: "string",
        required: false,
        variadic: false
      }
    ]
  },
  {
    id: "completions-fish-script",
    name: "script",
    path: "completions/fish/script",
    segments: ["completions", "fish", "script"],
    title: "Completions - Fish Script",
    description:
      "Generate a Fish completion script for the Cyclone User Interface command-line interface.\nOptions: --display (boolean)\nArgs: path:string",
    toolName: "completions_fish_script",
    options: [
      {
        name: "display",
        title: "Display",
        description:
          "Should the generated completion script be written to console output instead of an actual file on disk? This is useful for debugging purposes or if you want to manually handle the output.",
        type: "boolean",
        required: false,
        variadic: false
      }
    ],
    args: [
      {
        name: "path",
        title: "Path",
        description:
          "An argument that allows the user to specify a custom Path string value.",
        type: "string",
        required: false,
        variadic: false
      }
    ]
  },
  {
    id: "completions-powershell-config",
    name: "config",
    path: "completions/powershell/config",
    segments: ["completions", "powershell", "config"],
    title: "Completions - PowerShell Configuration",
    description:
      "Update the current system's PowerShell configuration to include completions for the Cyclone User Interface command-line interface.\nOptions: --display (boolean)\nArgs: path:string",
    toolName: "completions_powershell_config",
    options: [
      {
        name: "display",
        title: "Display",
        description:
          "Should the generated completion script be written to console output instead of an actual file on disk? This is useful for debugging purposes or if you want to manually handle the output.",
        type: "boolean",
        required: false,
        variadic: false
      }
    ],
    args: [
      {
        name: "path",
        title: "Path",
        description:
          "An argument that allows the user to specify a custom Path string value.",
        type: "string",
        required: false,
        variadic: false
      }
    ]
  },
  {
    id: "completions-powershell-script",
    name: "script",
    path: "completions/powershell/script",
    segments: ["completions", "powershell", "script"],
    title: "Completions - PowerShell Script",
    description:
      "Generate a PowerShell completion script for the Cyclone User Interface command-line interface.\nOptions: --display (boolean)\nArgs: path:string",
    toolName: "completions_powershell_script",
    options: [
      {
        name: "display",
        title: "Display",
        description:
          "Should the generated completion script be written to console output instead of an actual file on disk? This is useful for debugging purposes or if you want to manually handle the output.",
        type: "boolean",
        required: false,
        variadic: false
      }
    ],
    args: [
      {
        name: "path",
        title: "Path",
        description:
          "An argument that allows the user to specify a custom Path string value.",
        type: "string",
        required: false,
        variadic: false
      }
    ]
  },
  {
    id: "completions-zsh-config",
    name: "config",
    path: "completions/zsh/config",
    segments: ["completions", "zsh", "config"],
    title: "Completions - Zsh Configuration",
    description:
      "Update the current system's Zsh shell configuration to include completions for the Cyclone User Interface command-line interface.\nOptions: --display (boolean)\nArgs: path:string",
    toolName: "completions_zsh_config",
    options: [
      {
        name: "display",
        title: "Display",
        description:
          "Should the generated completion script be written to console output instead of an actual file on disk? This is useful for debugging purposes or if you want to manually handle the output.",
        type: "boolean",
        required: false,
        variadic: false
      }
    ],
    args: [
      {
        name: "path",
        title: "Path",
        description:
          "An argument that allows the user to specify a custom Path string value.",
        type: "string",
        required: false,
        variadic: false
      }
    ]
  },
  {
    id: "completions-zsh-script",
    name: "script",
    path: "completions/zsh/script",
    segments: ["completions", "zsh", "script"],
    title: "Completions - Zsh Script",
    description:
      "Generate a Zsh completion script for the Cyclone User Interface command-line interface.\nOptions: --display (boolean)\nArgs: path:string",
    toolName: "completions_zsh_script",
    options: [
      {
        name: "display",
        title: "Display",
        description:
          "Should the generated completion script be written to console output instead of an actual file on disk? This is useful for debugging purposes or if you want to manually handle the output.",
        type: "boolean",
        required: false,
        variadic: false
      }
    ],
    args: [
      {
        name: "path",
        title: "Path",
        description:
          "An argument that allows the user to specify a custom Path string value.",
        type: "string",
        required: false,
        variadic: false
      }
    ]
  },
  {
    id: "diff",
    name: "diff",
    path: "diff",
    segments: ["diff"],
    title: "Diff Components",
    description:
      "Compare installed components with the registry.\nOptions: --cwd (string), --registry (string)\nArgs: components:string[]",
    toolName: "diff",
    options: [
      {
        name: "cwd",
        title: "Current Working Directory",
        description: "The working directory.",
        type: "string",
        required: false,
        variadic: false
      },
      {
        name: "registry",
        title: "Registry",
        description: "Registry API URL.",
        type: "string",
        required: false,
        variadic: false
      }
    ],
    args: [
      {
        name: "components",
        title: "Components",
        description: "Installed component names to compare.",
        type: "string",
        required: false,
        variadic: true
      }
    ]
  },
  {
    id: "docs",
    name: "docs",
    path: "docs",
    segments: ["docs"],
    title: "Component Documentation",
    description:
      "Get documentation links for registry components.\nOptions: --cwd (string), --registry (string), --json (boolean)\nArgs: components:string (required)[]",
    toolName: "docs",
    options: [
      {
        name: "cwd",
        title: "Current Working Directory",
        description: "The working directory.",
        type: "string",
        required: false,
        variadic: false
      },
      {
        name: "registry",
        title: "Registry",
        description: "Registry API URL.",
        type: "string",
        required: false,
        variadic: false
      },
      {
        name: "json",
        title: "JavaScript Object Notation",
        description: "Output machine-readable JSON.",
        type: "boolean",
        required: false,
        variadic: false
      }
    ],
    args: [
      {
        name: "components",
        title: "Components",
        description: "Component names to document.",
        type: "string",
        required: true,
        variadic: true
      }
    ]
  },
  {
    id: "guidelines",
    name: "guidelines",
    path: "guidelines",
    segments: ["guidelines"],
    title: "Guidelines",
    description:
      "Return design-system guidelines as Markdown: an overview of the token groups, one section per component (with usage examples), typography, the design-system style guidelines, and any bundled guideline documents. Pass --terms to search; omit for the full set.\nOptions: --terms (string), --limit (number)",
    toolName: "guidelines",
    options: [
      {
        name: "terms",
        title: "Terms",
        description:
          "Search terms matched against guideline keywords, titles and body (fuzzy). Omit to return all guidelines.",
        type: "string",
        required: false,
        variadic: true
      },
      {
        name: "limit",
        title: "Limit",
        description: "Maximum matches per term when searching.",
        type: "number",
        required: false,
        variadic: false
      }
    ],
    args: []
  },
  {
    id: "help",
    name: "help",
    path: "help",
    segments: ["help"],
    title: "Help",
    description:
      "Display command usage details and other useful information to the user.\nArgs: commands:string[]",
    toolName: "help",
    options: [],
    args: [
      {
        name: "commands",
        title: "Commands",
        description:
          "- The command segments for the command to show help for. This\nis used to determine which command's help information to display. If no\ncommands are provided, general help information about the CLI application\nwill be displayed.",
        type: "string",
        required: false,
        variadic: true
      }
    ]
  },
  {
    id: "info",
    name: "info",
    path: "info",
    segments: ["info"],
    title: "Project Information",
    description:
      "Show Cyclone UI project configuration and installed components.\nOptions: --cwd (string), --json (boolean)",
    toolName: "info",
    options: [
      {
        name: "cwd",
        title: "Current Working Directory",
        description: "The working directory.",
        type: "string",
        required: false,
        variadic: false
      },
      {
        name: "json",
        title: "JavaScript Object Notation",
        description: "Output machine-readable JSON.",
        type: "boolean",
        required: false,
        variadic: false
      }
    ],
    args: []
  },
  {
    id: "init",
    name: "init",
    path: "init",
    segments: ["init"],
    title: "Initialize",
    description:
      "Initialize Cyclone UI in a project.\nOptions: --cwd (string), --path (string), --registry (string), --force (boolean), --silent (boolean)\nArgs: components:string[]",
    toolName: "init",
    options: [
      {
        name: "cwd",
        title: "Current Working Directory",
        description: "The working directory.",
        type: "string",
        required: false,
        variadic: false
      },
      {
        name: "path",
        title: "Path",
        description:
          "Component output path, relative to the working directory.",
        type: "string",
        required: false,
        variadic: false
      },
      {
        name: "registry",
        title: "Registry",
        description: "Registry API URL.",
        type: "string",
        required: false,
        variadic: false
      },
      {
        name: "force",
        title: "Force",
        description: "Overwrite an existing Cyclone configuration.",
        type: "boolean",
        required: false,
        variadic: false
      },
      {
        name: "silent",
        title: "Silent",
        description: "Mute non-essential output.",
        type: "boolean",
        required: false,
        variadic: false
      }
    ],
    args: [
      {
        name: "components",
        title: "Components",
        description: "Components to install after initialization.",
        type: "string",
        required: false,
        variadic: true
      }
    ]
  },
  {
    id: "list-components",
    name: "list-components",
    path: "list-components",
    segments: ["list-components"],
    title: "List Components",
    description:
      "Return every design-system component record. Large output - prefer search-components for normal use.",
    toolName: "list-components",
    options: [],
    args: []
  },
  {
    id: "list-fonts",
    name: "list-fonts",
    path: "list-fonts",
    segments: ["list-fonts"],
    title: "List Fonts",
    description: "Return every design-system font record.",
    toolName: "list-fonts",
    options: [],
    args: []
  },
  {
    id: "list-icons",
    name: "list-icons",
    path: "list-icons",
    segments: ["list-icons"],
    title: "List Icons",
    description:
      "Return every design-system icon record. Large output - prefer search-icons for normal use.",
    toolName: "list-icons",
    options: [],
    args: []
  },
  {
    id: "list-tokens",
    name: "list-tokens",
    path: "list-tokens",
    segments: ["list-tokens"],
    title: "List Tokens",
    description:
      "Return every design token (name, value, type, description, CSS variable). Large output - prefer search-tokens for normal use.",
    toolName: "list-tokens",
    options: [],
    args: []
  },
  {
    id: "mcp",
    name: "mcp",
    path: "mcp",
    segments: ["mcp"],
    title: "MCP Server",
    description:
      "Starts an MCP stdio server that exposes this Shell Shock application's commands as tools.\nOptions: --include-self (boolean)",
    toolName: "mcp",
    options: [
      {
        name: "includeSelf",
        title: "Include MCP Command",
        description:
          "Whether to expose the MCP command itself as a tool in the generated server.",
        type: "boolean",
        required: false,
        variadic: false
      }
    ],
    args: []
  },
  {
    id: "plan",
    name: "plan",
    path: "plan",
    segments: ["plan"],
    title: "Plan",
    description:
      "Search tokens, icons, components and fonts in one call to plan what to build. Provide terms for at least one list.\nOptions: --tokens (string), --icons (string), --components (string), --fonts (string), --limit (number)",
    toolName: "plan",
    options: [
      {
        name: "tokens",
        title: "Tokens",
        description:
          "Search terms for design tokens. Prefer at least two terms when known.",
        type: "string",
        required: false,
        variadic: true
      },
      {
        name: "icons",
        title: "Icons",
        description: "Search terms for icons.",
        type: "string",
        required: false,
        variadic: true
      },
      {
        name: "components",
        title: "Components",
        description: "Search terms for components.",
        type: "string",
        required: false,
        variadic: true
      },
      {
        name: "fonts",
        title: "Fonts",
        description: "Search terms for fonts.",
        type: "string",
        required: false,
        variadic: true
      },
      {
        name: "limit",
        title: "Limit",
        description: "Maximum matches per term for each list.",
        type: "number",
        required: false,
        variadic: false
      }
    ],
    args: []
  },
  {
    id: "registry-validate",
    name: "validate",
    path: "registry/validate",
    segments: ["registry", "validate"],
    title: "Validate Registry",
    description:
      "Validate a local registry manifest and its source files.\nOptions: --cwd (string)\nArgs: registry:string",
    toolName: "registry_validate",
    options: [
      {
        name: "cwd",
        title: "Current Working Directory",
        description: "The working directory.",
        type: "string",
        required: false,
        variadic: false
      }
    ],
    args: [
      {
        name: "registry",
        title: "Registry",
        description: "Registry manifest path.",
        type: "string",
        required: false,
        variadic: false
      }
    ]
  },
  {
    id: "search",
    name: "search",
    path: "search",
    segments: ["search"],
    title: "Search Registry",
    description:
      "Search components in the Cyclone registry.\nOptions: --cwd (string), --query (string), --limit (number), --offset (number), --json (boolean), --registry (string)",
    toolName: "search",
    options: [
      {
        name: "cwd",
        title: "Current Working Directory",
        description: "The working directory.",
        type: "string",
        required: false,
        variadic: false
      },
      {
        name: "query",
        title: "Query",
        description: "Text to match against names, descriptions, and tags.",
        type: "string",
        required: false,
        variadic: false
      },
      {
        name: "limit",
        title: "Limit",
        description: "Maximum number of results.",
        type: "number",
        required: false,
        variadic: false
      },
      {
        name: "offset",
        title: "Offset",
        description: "Number of results to skip.",
        type: "number",
        required: false,
        variadic: false
      },
      {
        name: "json",
        title: "JavaScript Object Notation",
        description: "Output machine-readable JSON.",
        type: "boolean",
        required: false,
        variadic: false
      },
      {
        name: "registry",
        title: "Registry",
        description: "Registry API URL.",
        type: "string",
        required: false,
        variadic: false
      }
    ],
    args: []
  },
  {
    id: "search-components",
    name: "search-components",
    path: "search-components",
    segments: ["search-components"],
    title: "Search Components",
    description:
      "Search design-system components by name, title, category, description and tags. Returns name, files, dependencies and usage examples for each match.\nOptions: --terms (string, required), --limit (number)",
    toolName: "search-components",
    options: [
      {
        name: "terms",
        title: "Terms",
        description:
          'One or more search terms (fuzzy match). Example: ["button", "modal", "select"].',
        type: "string",
        required: true,
        variadic: true
      },
      {
        name: "limit",
        title: "Limit",
        description: "Maximum matches per term.",
        type: "number",
        required: false,
        variadic: false
      }
    ],
    args: []
  },
  {
    id: "search-fonts",
    name: "search-fonts",
    path: "search-fonts",
    segments: ["search-fonts"],
    title: "Search Fonts",
    description:
      "Search design-system fonts by name, family, role, tags and category. Returns the CSS font-family stack, weights and files for each match.\nOptions: --terms (string, required), --limit (number)",
    toolName: "search-fonts",
    options: [
      {
        name: "terms",
        title: "Terms",
        description:
          'One or more search terms (fuzzy match). Example: ["heading", "mono", "inter"].',
        type: "string",
        required: true,
        variadic: true
      },
      {
        name: "limit",
        title: "Limit",
        description: "Maximum matches per term.",
        type: "number",
        required: false,
        variadic: false
      }
    ],
    args: []
  },
  {
    id: "search-icons",
    name: "search-icons",
    path: "search-icons",
    segments: ["search-icons"],
    title: "Search Icons",
    description:
      "Search design-system icons by name, title, aliases, tags and category. Returns name and asset files for each match.\nOptions: --terms (string, required), --limit (number)",
    toolName: "search-icons",
    options: [
      {
        name: "terms",
        title: "Terms",
        description:
          'One or more search terms (fuzzy match). Example: ["search", "folder", "user"].',
        type: "string",
        required: true,
        variadic: true
      },
      {
        name: "limit",
        title: "Limit",
        description: "Maximum matches per term.",
        type: "number",
        required: false,
        variadic: false
      }
    ],
    args: []
  },
  {
    id: "search-tokens",
    name: "search-tokens",
    path: "search-tokens",
    segments: ["search-tokens"],
    title: "Search Tokens",
    description:
      "Search design tokens by name, path, description, type and value. Returns compact JSON records with name and value for each match; set --include-metadata for descriptions and CSS variables.\nOptions: --terms (string, required), --limit (number), --include-metadata (boolean)",
    toolName: "search-tokens",
    options: [
      {
        name: "terms",
        title: "Terms",
        description:
          'One or more search terms (fuzzy match). Example: ["spacing", "color.text", "background"].',
        type: "string",
        required: true,
        variadic: true
      },
      {
        name: "limit",
        title: "Limit",
        description: "Maximum matches per term.",
        type: "number",
        required: false,
        variadic: false
      },
      {
        name: "includeMetadata",
        title: "Include Metadata",
        description:
          "Include type, description, hex value and CSS variable in each result.",
        type: "boolean",
        required: false,
        variadic: false
      }
    ],
    args: []
  },
  {
    id: "update",
    name: "update",
    path: "update",
    segments: ["update"],
    title: "Update",
    description:
      "A command for checking and updating the version of the Cyclone User Interface command-line interface application.\nOptions: --latest (boolean), --version (string)",
    toolName: "update",
    options: [
      {
        name: "latest",
        title: "Latest",
        description: "Whether to update to the latest version.",
        type: "boolean",
        required: false,
        variadic: false
      },
      {
        name: "version",
        title: "Version",
        description: "A specific application version to update to.",
        type: "string",
        required: false,
        variadic: false
      }
    ],
    args: []
  },
  {
    id: "view",
    name: "view",
    path: "view",
    segments: ["view"],
    title: "View Registry Components",
    description:
      "View component metadata and files from the registry.\nOptions: --cwd (string), --registry (string)\nArgs: components:string (required)[]",
    toolName: "view",
    options: [
      {
        name: "cwd",
        title: "Current Working Directory",
        description: "The working directory.",
        type: "string",
        required: false,
        variadic: false
      },
      {
        name: "registry",
        title: "Registry",
        description: "Registry API URL.",
        type: "string",
        required: false,
        variadic: false
      }
    ],
    args: [
      {
        name: "components",
        title: "Components",
        description: "Component names to view.",
        type: "string",
        required: true,
        variadic: true
      }
    ]
  }
];

export const metadata = defineMetadata({
  title: "MCP Server",
  description:
    "Starts an MCP stdio server that exposes this Shell Shock application's commands as tools.",
  icon: "🔌",
  tags: ["Utility", "MCP"]
});

export const options = defineOptions({
  includeSelf: {
    type: "boolean",
    title: "Include MCP Command",
    description:
      "Whether to expose the MCP command itself as a tool in the generated server.",
    default: false,
    required: false,
    variadic: false
  }
});

function toFlagName(input: string): string {
  return input
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[^a-z0-9-]/gi, "-")
    .replace(/-{2,}/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
}

function toCliArgs(optionsMap: Record<string, unknown>): string[] {
  const args: string[] = [];

  for (const [rawName, rawValue] of Object.entries(optionsMap ?? {})) {
    if (!/^[a-zA-Z0-9_-]+$/.test(rawName)) {
      continue;
    }

    const flag = toFlagName(rawName);
    if (!flag) {
      continue;
    }

    if (rawValue === undefined || rawValue === null) {
      continue;
    }

    if (typeof rawValue === "boolean") {
      args.push(rawValue ? "--" + flag : "--no-" + flag);
      continue;
    }

    if (Array.isArray(rawValue)) {
      for (const item of rawValue) {
        if (item === undefined || item === null) {
          continue;
        }

        args.push("--" + flag, String(item));
      }
      continue;
    }

    args.push("--" + flag, String(rawValue));
  }

  return args;
}

export default async function handler(options: { includeSelf?: boolean }) {
  const commandMap = new Map<string, (typeof COMMANDS)[number]>();
  const usedToolNames = new Set<string>();
  const includeSelf = options.includeSelf === true;

  for (const command of COMMANDS) {
    if (!includeSelf && command.path === COMMAND_NAME) {
      continue;
    }

    let toolName = command.toolName;
    if (usedToolNames.has(toolName)) {
      let index = 2;
      while (usedToolNames.has(toolName + "_" + String(index))) {
        index += 1;
      }

      toolName = toolName + "_" + String(index);
    }

    usedToolNames.add(toolName);
    commandMap.set(toolName, command);
  }

  const server = new McpServer({
    name: APP_NAME + "-shell-shock",
    version: "1.0.0"
  });

  for (const [toolName, command] of commandMap.entries()) {
    server.registerTool(
      toolName,
      {
        title: command.title,
        description: command.description,
        inputSchema: z.object({
          options: z.record(z.unknown()).optional(),
          args: z.array(z.string()).optional(),
          cwd: z.string().optional(),
          timeoutMs: z.number().int().positive().optional()
        })
      },
      async input => {
        const commandArgv = [
          ...command.segments,
          ...toCliArgs((input.options ?? {}) as Record<string, unknown>),
          "--no-banner",
          "--quiet",
          ...((input.args ?? []) as string[])
        ];

        const launchArgv =
          process.argv.length >= 2
            ? [process.argv[0]!, process.argv[1]!, ...commandArgv]
            : [COMMAND_NAME, ...commandArgv];

        const result = await spawn(launchArgv, {
          cwd: input.cwd,
          timeoutMs: input.timeoutMs ?? 300_000
        });

        const isError = (result.code ?? 0) !== 0;
        const output = [result.stdout, isError ? result.stderr : ""]
          .filter(Boolean)
          .join("\n")
          .trim();

        return {
          isError,
          content: [
            {
              type: "text" as const,
              text:
                output.length > 0
                  ? output
                  : isError
                    ? "Command failed with exit code " +
                      String(result.code ?? 1) +
                      "."
                    : "Command completed successfully."
            }
          ]
        };
      }
    );
  }

  await server.connect(new StdioServerTransport());
}
