/* -------------------------------------------------------------------

                   🗲 Storm Software - Cyclone UI

 This code was released as part of the Cyclone UI project. Cyclone UI
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/cyclone-ui.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/cyclone-ui
 Documentation:            https://docs.stormsoftware.com/projects/cyclone-ui
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

// This file is generated by `scripts/generate.ts` from @phosphor-icons/core@2.1.1 (MIT). Do not edit it manually.

import { Path as SvgPath } from "react-native-svg";
import { createIcon } from "../create-icon";

/**
 * The Phosphor `dot` icon.
 *
 * @see https://phosphoricons.com/?q=dot
 */
export const Dot = createIcon("Dot", {
  thin: <SvgPath d="M136,128a8,8,0,1,1-8-8A8,8,0,0,1,136,128Z" />,
  light: <SvgPath d="M138,128a10,10,0,1,1-10-10A10,10,0,0,1,138,128Z" />,
  regular: <SvgPath d="M140,128a12,12,0,1,1-12-12A12,12,0,0,1,140,128Z" />,
  bold: <SvgPath d="M144,128a16,16,0,1,1-16-16A16,16,0,0,1,144,128Z" />,
  fill: (
    <SvgPath d="M128,80a48,48,0,1,0,48,48A48,48,0,0,0,128,80Zm0,60a12,12,0,1,1,12-12A12,12,0,0,1,128,140Z" />
  ),
  duotone: (
    <>
      <SvgPath
        d="M176,128a48,48,0,1,1-48-48A48,48,0,0,1,176,128Z"
        opacity={0.2}
      />
      <SvgPath d="M140,128a12,12,0,1,1-12-12A12,12,0,0,1,140,128Z" />
    </>
  )
});
