/* -------------------------------------------------------------------

                   🗲 Storm Software - Cyclone UI

 This code was released as part of the Cyclone UI project. Cyclone UI
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/cyclone-ui.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/cyclone-ui
 Documentation:            https://docs.stormsoftware.com/projects/cyclone-ui
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

// This file is generated by `scripts/generate.ts` from @phosphor-icons/core@2.1.1 (MIT). Do not edit it manually.

import { Path as SvgPath } from "react-native-svg";
import { createIcon } from "../create-icon";

/**
 * The Phosphor `line-vertical` icon.
 *
 * @see https://phosphoricons.com/?q=line-vertical
 */
export const LineVertical = createIcon("LineVertical", {
  thin: <SvgPath d="M132,24V232a4,4,0,0,1-8,0V24a4,4,0,0,1,8,0Z" />,
  light: <SvgPath d="M134,24V232a6,6,0,0,1-12,0V24a6,6,0,0,1,12,0Z" />,
  regular: <SvgPath d="M136,24V232a8,8,0,0,1-16,0V24a8,8,0,0,1,16,0Z" />,
  bold: <SvgPath d="M140,24V232a12,12,0,0,1-24,0V24a12,12,0,0,1,24,0Z" />,
  fill: (
    <SvgPath d="M208,32H48A16,16,0,0,0,32,48V208a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V48A16,16,0,0,0,208,32ZM136,192a8,8,0,0,1-16,0V64a8,8,0,0,1,16,0Z" />
  ),
  duotone: (
    <>
      <SvgPath
        d="M224,48V208a16,16,0,0,1-16,16H48a16,16,0,0,1-16-16V48A16,16,0,0,1,48,32H208A16,16,0,0,1,224,48Z"
        opacity={0.2}
      />
      <SvgPath d="M136,24V232a8,8,0,0,1-16,0V24a8,8,0,0,1,16,0Z" />
    </>
  )
});
