/* -------------------------------------------------------------------

                   🗲 Storm Software - Cyclone UI

 This code was released as part of the Cyclone UI project. Cyclone UI
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/cyclone-ui.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/cyclone-ui
 Documentation:            https://docs.stormsoftware.com/projects/cyclone-ui
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

// This file is generated by `scripts/generate.ts` from @phosphor-icons/core@2.1.1 (MIT). Do not edit it manually.

import { Path as SvgPath } from "react-native-svg";
import { createIcon } from "../create-icon";

/**
 * The Phosphor `wifi-none` icon.
 *
 * @see https://phosphoricons.com/?q=wifi-none
 */
export const WifiNone = createIcon("WifiNone", {
  thin: <SvgPath d="M136,204a8,8,0,1,1-8-8A8,8,0,0,1,136,204Z" />,
  light: <SvgPath d="M138,204a10,10,0,1,1-10-10A10,10,0,0,1,138,204Z" />,
  regular: <SvgPath d="M140,204a12,12,0,1,1-12-12A12,12,0,0,1,140,204Z" />,
  bold: <SvgPath d="M144,204a16,16,0,1,1-16-16A16,16,0,0,1,144,204Z" />,
  fill: (
    <SvgPath d="M247.89,80.91a15.93,15.93,0,0,0-6.17-10.81A186.67,186.67,0,0,0,128,32,186.67,186.67,0,0,0,14.28,70.1,15.93,15.93,0,0,0,8.11,80.91,15.65,15.65,0,0,0,11.65,92.8l104,125.43A15.93,15.93,0,0,0,128,224h0a15.93,15.93,0,0,0,12.31-5.77h0l104-125.43A15.65,15.65,0,0,0,247.89,80.91ZM128,208,24.09,82.74A170.76,170.76,0,0,1,128,48,170.76,170.76,0,0,1,231.91,82.74Z" />
  ),
  duotone: (
    <SvgPath d="M247.89,80.91a15.93,15.93,0,0,0-6.17-10.81A186.67,186.67,0,0,0,128,32,186.67,186.67,0,0,0,14.28,70.1,15.93,15.93,0,0,0,8.11,80.91,15.65,15.65,0,0,0,11.65,92.8l104,125.43A15.93,15.93,0,0,0,128,224h0a15.93,15.93,0,0,0,12.31-5.77h0l104-125.43A15.65,15.65,0,0,0,247.89,80.91ZM128,208,24.09,82.74A170.76,170.76,0,0,1,128,48,170.76,170.76,0,0,1,231.91,82.74Z" />
  )
});
