/* eslint-disable */
/* oxlint-disable */
// biome-ignore lint: disable

import { showBanner } from "shell-shock:banner/search";
import { textColors, writeLine } from "shell-shock:console";
import { env, isDebug, isDevelopment } from "shell-shock:env";
import { showHelp } from "shell-shock:help/search";
import {
  type GlobalOptions,
  isHelp,
  useArgs,
  useGlobalOptions,
  withCommand
} from "shell-shock:state";
import { executeUpdate } from "shell-shock:update";
import { isInteractive } from "shell-shock:utils";
import handleSearch from "../../../src/commands/search/command";

// Generated by Power Plant
// Please do not edit this file manually - it will be automatically overwritten
// the next time the generator is run.

export interface SearchOptions extends GlobalOptions {
  /**
   * The working directory.
   */
  cwd?: string | undefined;
  /**
   * Text to match against names, descriptions, and tags.
   */
  query?: string | undefined;
  /**
   * Maximum number of results.
   */
  limit?: number | undefined;
  /**
   * Number of results to skip.
   */
  offset?: number | undefined;
  /**
   * Output machine-readable JSON.
   */
  json?: boolean | undefined;
  /**
   * Registry API URL.
   */
  registry?: string | undefined;
}

/**
 * The Search Registry (cyclone-ui search) command.
 *
 * @remarks
 * Search components in the Cyclone registry.
 *
 * @title Search Registry
 *
 * @param args - The command-line arguments passed to the command.
 */
export async function handler(args: string[] = useArgs()) {
  const options = {
    ...useGlobalOptions()
  } as unknown as SearchOptions;

  for (let i = 0; i < args.slice(0).length; i++) {
    const arg: string =
      args[i].length > 3 && args[i].startsWith("--")
        ? `--${args[i].slice(2).replaceAll("-", "").toLowerCase().replaceAll("-", "").replaceAll("_", "")}`
        : args[i].length > 2 && args[i].startsWith("-")
          ? `-${args[i].slice(1).replaceAll("-", "")}`
          : args[i];
    if (
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("cwd=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "cwd" ||
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("cwd=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "cwd"
    ) {
      if (
        /^--?(cwd)=/.test(
          "-" + arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
        )
      ) {
        options.cwd = arg
          .replace(/^--?(cwd)=/, "")
          .trim()
          .replace(/^("|')/, "")
          .replace(/("|')$/, "");
      } else if (args.length > i + 1) {
        options.cwd = args[++i]
          .trim()
          .replace(/^("|')/, "")
          .replace(/("|')$/, "");
      }
    } else if (
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("query=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "query" ||
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("query=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "query"
    ) {
      if (
        /^--?(query)=/.test(
          "-" + arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
        )
      ) {
        options.query = arg
          .replace(/^--?(query)=/, "")
          .trim()
          .replace(/^("|')/, "")
          .replace(/("|')$/, "");
      } else if (args.length > i + 1) {
        options.query = args[++i]
          .trim()
          .replace(/^("|')/, "")
          .replace(/("|')$/, "");
      }
    } else if (
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("limit=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "limit" ||
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("limit=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "limit"
    ) {
      if (
        /^--?(limit)=/.test(
          "-" + arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
        )
      ) {
        const value = Number(
          arg
            .replace(/^--?(limit)=/, "")
            .trim()
            .replace(/^("|')/, "")
            .replace(/("|')$/, "")
        );
        if (!Number.isNaN(value)) {
          options.limit = value;
        }
      } else if (args.length > i + 1) {
        const value = Number(
          args[++i]
            .trim()
            .replace(/^("|')/, "")
            .replace(/("|')$/, "")
        );
        if (!Number.isNaN(value)) {
          options.limit = value;
        }
      }
    } else if (
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("offset=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "offset" ||
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("offset=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "offset"
    ) {
      if (
        /^--?(offset)=/.test(
          "-" + arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
        )
      ) {
        const value = Number(
          arg
            .replace(/^--?(offset)=/, "")
            .trim()
            .replace(/^("|')/, "")
            .replace(/("|')$/, "")
        );
        if (!Number.isNaN(value)) {
          options.offset = value;
        }
      } else if (args.length > i + 1) {
        const value = Number(
          args[++i]
            .trim()
            .replace(/^("|')/, "")
            .replace(/("|')$/, "")
        );
        if (!Number.isNaN(value)) {
          options.offset = value;
        }
      }
    } else if (
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("json=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "json" ||
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("json=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "json"
    ) {
      if (
        /^--?(json)=/.test(
          "-" + arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
        )
      ) {
        const value = arg
          .replace(/^--?(json)=/, "")
          .trim()
          .replace(/^("|')/, "")
          .replace(/("|')$/, "")
          .toLowerCase();
        options.json =
          !!value &&
          value.toLowerCase() !== "false" &&
          value.toLowerCase() !== "f" &&
          value.toLowerCase() !== "no" &&
          value !== "n" &&
          value.toLowerCase() !== "0" &&
          value.toLowerCase() !== "off" &&
          value !== "disable" &&
          value.toLowerCase() !== "disabled" &&
          value.toLowerCase() !== "never" &&
          (Number.isNaN(Number.parseFloat(value)) ||
            Number.parseFloat(value) > 0);
      } else {
        options.json = true;
      }
    } else if (
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("registry=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") ===
        "registry" ||
      arg
        .toLowerCase()
        .replaceAll("-", "")
        .replaceAll("_", "")
        .startsWith("registry=") ||
      arg.toLowerCase().replaceAll("-", "").replaceAll("_", "") === "registry"
    ) {
      if (
        /^--?(registry)=/.test(
          "-" + arg.toLowerCase().replaceAll("-", "").replaceAll("_", "")
        )
      ) {
        options.registry = arg
          .replace(/^--?(registry)=/, "")
          .trim()
          .replace(/^("|')/, "")
          .replace(/("|')$/, "");
      } else if (args.length > i + 1) {
        options.registry = args[++i]
          .trim()
          .replace(/^("|')/, "")
          .replace(/("|')$/, "");
      }
    }
  }

  await showBanner();
  await executeUpdate();

  if (!isHelp()) {
    writeLine("");
    if (isDevelopment || isDebug || env.LOG_LEVEL === "debug") {
      writeLine(
        textColors.body.tertiary(
          "Debug mode is enabled. Additional debug information may be logged to the console."
        )
      );
    }
  }

  if (!isInteractive) {
    const failures: string[] = [];
    if (options.limit && Number.isNaN(options.limit)) {
      failures.push('Invalid numeric value provided for the "limit" option');
    }

    if (options.offset && Number.isNaN(options.offset)) {
      failures.push('Invalid numeric value provided for the "offset" option');
    }
  }

  if (options.help) {
    return showHelp();
  } else {
    return withCommand("search", ["search"], [options], handleSearch);
  }
}
