/* eslint-disable */
/* oxlint-disable */
// biome-ignore lint: disable

import { writeFile } from "node:fs/promises";
import { bold, help, success, writeLine } from "shell-shock:console";
import { SHELL_COMPLETIONS, SHELL_COMPLETIONS_DISPLAY } from "../shared";

// Generated by Shell Shock
// Do not edit this file manually - it will be overwritten automatically.
// Automatic overwrites can be disabled by using the `output.overwrite` option.

/**
 * Options for the Fish Completions - Script command.
 */
export interface FishScriptCompletionsOptions {
  /**
   * Should the generated completion script be written to console output instead of an actual file on disk? This is useful for debugging purposes or if you want to manually handle the output.
   *
   * @defaultValue false
   */
  display?: boolean;
}

/**
 * Handler logic for the \`completions fish script\` command.
 */
export default async function handler(
  options: FishScriptCompletionsOptions = {},
  path: string = "./powerlines-completions.fish"
) {
  if (options.display !== true) {
    const scriptPath: string = path.includes(".") ? `${path}.fish` : path;
    await writeFile(
      scriptPath,
      `# Fish script to add completions for Powerlines\n\n${SHELL_COMPLETIONS}`
    );

    success(
      `Powerlines Fish completion script has been generated at ${bold(scriptPath)}.`
    );
  } else {
    writeLine(" ------------------------------------------------- ");
    writeLine("");
    writeLine(`# Fish completion for Powerlines`);
    writeLine("");
    SHELL_COMPLETIONS_DISPLAY.split("\n").map(line => writeLine(line));
    writeLine("");
    writeLine(" ------------------------------------------------- ");

    writeLine("");
    help(`To enable these completions, perform one of the following actions:

    1) Copy and paste the above script into your shell configuration file (e.g., ~/.config/fish/config.fish)
    2) Save the above script to a file and source it from your shell configuration file `);
  }
}
