import "./global.css";
import { NextTamaguiProvider } from "../components/NextTamaguiProvider";

export const metadata = {
  title: "Welcome to website",
  description: "Generated by create-nx-workspace"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextTamaguiProvider>
        <body>{children}</body>
      </NextTamaguiProvider>
    </html>
  );
}
