name: "CI"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: override release tag
        required: false
  push:
    branches:
      - "main"
      - "next"
      - "alpha"
      - "beta"

env:
  CYCLONE_REGISTRY_ACCESS_KEY: ${{ secrets.CYCLONE_REGISTRY_ACCESS_KEY }}
  CYCLONE_REGISTRY_SECRET_KEY: ${{ secrets.CYCLONE_REGISTRY_SECRET_KEY }}

jobs:
  release:
    uses: storm-software/storm-ops/.github/workflows/ci-reusable.yml@main
    with:
      tag: ${{ inputs.TAG }}
      stormBot: Stormie-Bot
    secrets:
      githubToken: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
      npmToken: ${{ secrets.STORM_BOT_NPM_TOKEN }}
      cargoToken: ${{ secrets.STORM_BOT_CARGO_TOKEN }}
      slackToken: ${{ secrets.STORM_BOT_SLACK_TOKEN }}
      discordWebhook: ${{ secrets.STORM_BOT_DISCORD_WEBHOOK }}

  registry:
    name: Publish design components
    needs:
      - release
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Publish design components to Storm CDN Registry
        run: pnpm nx run-many -t registry --projects=components/* --parallel=5
        shell: bash
