name: "CI"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: override release tag
        required: false
  push:
    branches:
      - "main"
      - "next"
      - "alpha"
      - "beta"

jobs:
  release:
    uses: storm-software/storm-ops/.github/workflows/ci-reusable.yml@main
    with:
      tag: ${{ inputs.TAG }}
      stormBot: Stormie-Bot
    secrets:
      githubToken: ${{ github.token }}
      npmToken: ${{ secrets.STORM_BOT_NPM_TOKEN }}
      cargoToken: ${{ secrets.STORM_BOT_CARGO_TOKEN }}
      slackToken: ${{ secrets.STORM_BOT_SLACK_TOKEN }}
      discordWebhook: ${{ secrets.STORM_BOT_DISCORD_WEBHOOK }}
