on:
  schedule:
    - cron: "0 0 * * *"

name: Stale Bot workflow

permissions:
  issues: write

jobs:
  build:
    if: ${{ github.repository_owner == 'storm-software' }}
    permissions:
      issues: write #  to close stale issues (actions/stale)
      pull-requests: write #  to close stale PRs (actions/stale)

    name: stale
    runs-on: ubuntu-latest
    steps:
      - name: stale-more-info-needed
        id: stale-more-info-needed
        uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          days-before-stale: 14
          days-before-close: 14
          stale-issue-label: "stale"
          operations-per-run: 300
          remove-stale-when-updated: true
          only-labels: "blocked: more info needed"
          stale-issue-message: |
            This issue has been automatically marked as stale because it hasn't had any recent activity. It will be closed in 14 days if no further activity occurs.
            If we missed this issue please reply to keep it active.
            Thanks for being a part of the Storm Software community! 🙏

      - name: stale-needs-rebase
        id: stale-needs-rebase
        uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          days-before-stale: 14
          days-before-close: 14
          stale-issue-label: "stale"
          operations-per-run: 300
          remove-stale-when-updated: true
          only-labels: "blocked: needs rebased"
          stale-issue-message: |
            This issue has been automatically marked as stale because it hasn't had any recent activity. It will be closed in 14 days if no further activity occurs.
            If we missed this issue please reply to keep it active.
            Thanks for being a part of the Storm Software community! 🙏

      - name: stale-repro-needed
        id: stale-repro-needed
        uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          days-before-stale: 14
          days-before-close: 14
          stale-issue-label: "stale"
          operations-per-run: 300
          remove-stale-when-updated: true
          only-labels: "blocked: repro needed"
          stale-issue-message: |
            This issue has been automatically marked as stale because it hasn't had any recent activity. It will be closed in 14 days if no further activity occurs.
            If we missed this issue please reply to keep it active.
            Thanks for being a part of the Storm Software community! 🙏

      - name: stale-retry-with-latest
        id: stale-retry-with-latest
        uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          days-before-stale: 14
          days-before-close: 14
          stale-issue-label: "stale"
          operations-per-run: 300
          remove-stale-when-updated: true
          only-labels: "blocked: retry with latest"
          stale-issue-message: |
            This issue has been automatically marked as stale because it hasn't had any recent activity. It will be closed in 14 days if no further activity occurs.
            If we missed this issue please reply to keep it active.
            Thanks for being a part of the Storm Software community! 🙏

      - name: stale-bug
        id: stale-bug
        uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          days-before-stale: 180
          days-before-close: 14
          stale-issue-label: "stale"
          operations-per-run: 300
          remove-stale-when-updated: true
          only-labels: "type: bug"
          stale-issue-message: |
            This issue has been automatically marked as stale because it hasn't had any recent activity. It will be closed in 14 days if no further activity occurs.
            If we missed this issue please reply to keep it active.
            Thanks for being a part of the Storm Software community! 🙏

      - name: stale-cleanup
        id: stale-cleanup
        uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          days-before-stale: 180
          days-before-close: 14
          stale-issue-label: "stale"
          operations-per-run: 300
          remove-stale-when-updated: true
          only-labels: "type: cleanup"
          stale-issue-message: |
            This issue has been automatically marked as stale because it hasn't had any recent activity. It will be closed in 14 days if no further activity occurs.
            If we missed this issue please reply to keep it active.
            Thanks for being a part of the Storm Software community! 🙏

      - name: stale-docs
        id: stale-docs
        uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          days-before-stale: 180
          days-before-close: 14
          stale-issue-label: "stale"
          operations-per-run: 300
          remove-stale-when-updated: true
          only-labels: "type: docs"
          stale-issue-message: |
            This issue has been automatically marked as stale because it hasn't had any recent activity. It will be closed in 14 days if no further activity occurs.
            If we missed this issue please reply to keep it active.
            Thanks for being a part of the Storm Software community! 🙏

      - name: stale-enhancement
        id: stale-enhancement
        uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          days-before-stale: 250
          days-before-close: 14
          stale-issue-label: "stale"
          operations-per-run: 300
          remove-stale-when-updated: true
          only-labels: "type: enhancement"
          stale-issue-message: |
            This issue has been automatically marked as stale because it hasn't had any recent activity. It will be closed in 14 days if no further activity occurs.
            If we missed this issue please reply to keep it active.
            Thanks for being a part of the Storm Software community! 🙏

      - name: stale-feature
        id: stale-feature
        uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          days-before-stale: 250
          days-before-close: 14
          stale-issue-label: "stale"
          operations-per-run: 300
          remove-stale-when-updated: true
          only-labels: "type: feature"
          stale-issue-message: |
            This issue has been automatically marked as stale because it hasn't had any recent activity. It will be closed in 14 days if no further activity occurs.
            If we missed this issue please reply to keep it active.
            Thanks for being a part of the Storm Software community! 🙏

      - name: stale-question
        id: stale-question
        uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          days-before-stale: 45
          days-before-close: 14
          stale-issue-label: "stale"
          operations-per-run: 300
          remove-stale-when-updated: true
          only-labels: "type: question / discussion"
          stale-issue-message: |
            This issue has been automatically marked as stale because it hasn't had any recent activity. It will be closed in 14 days if no further activity occurs.
            If we missed this issue please reply to keep it active.
            Thanks for being a part of the Storm Software community! 🙏
