name: Syncpack

on:
  pull_request:
    branches:
      - main
      - canary
      - experimental
    paths-ignore:
      - "!**/package.json"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  syncpack:
    name: Syncpack
    uses: storm-ops/.github/workflows/syncpack-reusable.yml
    secrets:
      STORM_BOT_GITHUB_TOKEN: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
      STORM_BOT_NPM_TOKEN: ${{ secrets.STORM_BOT_NPM_TOKEN }}
      STORM_BOT_CARGO_TOKEN: ${{ secrets.STORM_BOT_CARGO_TOKEN }}
